// cards/ct-d03/D03003 怪盗キッド (キャラ) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 13-keywords.md, 17-icons.md, 24-qa-naming-stun.md
//
// 公式テキスト: 【パートナー白】〚迅速〛（登場したターンからすぐに推理かアクションできる）

import type { CardDef } from '@/engine/types';
import { partnerColorKeyword } from '../_shared/index.js';

export const D03003: CardDef = {
  id: 'D03003',
  no: '0120/D03003',
  kind: 'character',
  names: ['怪盗キッド'],
  colors: ['白'],
  level: 7,
  ap: 6000,
  lp: 1,
  traits: ['怪盗'],
  keywords: [],
  rarity: 'D',
  imageUrl: '1714013117401793.jpg',
  abilities: [
  partnerColorKeyword({ color: '白', kw: '迅速', abilityId: 'a1' }),
  ],
  ruleRefs: ['rules/13-keywords.md', 'rules/17-icons.md'],
};
