// cards/ct-d03/D03001 怪盗キッド (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const D03001: CardDef = {
  id: 'D03001',
  no: 'P004/D03001',
  kind: 'partner',
  names: ['怪盗キッド'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'D',
  imageUrl: '1714013117395180.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
