// cards/ct-d03/D03016 邂逅 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const D03016: CardDef = {
  id: 'D03016',
  no: '0132/D03016',
  kind: 'case',
  names: ['邂逅'],
  colors: ['白'],
  traits: [],
  rarity: 'D',
  imageUrl: '1714013132373311.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
