import { describe, expect, it } from 'vitest';
import { ALL_CARDS } from '../../src/cards/index';
import { DECK_LEGALITY_CATALOG } from '../../src/shared/deck-legality-catalog.generated';
import {
  deckLegalityCatalogIsCurrent,
  renderDeckLegalityCatalog,
} from '../../scripts/gen-deck-legality-catalog';

describe('generated deck-legality catalog artifact', () => {
  it('is an exact printing-ID bijection and metadata projection of ALL_CARDS', () => {
    const sourceIds = ALL_CARDS.map(({ id }) => id).sort();
    const catalogIds = Object.keys(DECK_LEGALITY_CATALOG).sort();
    expect(catalogIds).toEqual(sourceIds);
    expect(new Set(catalogIds).size).toBe(ALL_CARDS.length);

    for (const card of ALL_CARDS) {
      expect(DECK_LEGALITY_CATALOG[card.id], card.id).toEqual([
        card.no.split('/')[0],
        card.kind,
        card.deckLimit ?? 3,
      ]);
    }
  });

  it.each([
    ['kind', { id: 'PRINT-B', no: '0001/PRINT-B', kind: 'event' as const, deckLimit: 3 }],
    ['deck limit', { id: 'PRINT-B', no: '0001/PRINT-B', kind: 'character' as const, deckLimit: 2 }],
  ])('rejects conflicting %s metadata across reprints', (_label, conflicting) => {
    expect(() => renderDeckLegalityCatalog([
      { id: 'PRINT-A', no: '0001/PRINT-A', kind: 'character', deckLimit: 3 },
      conflicting,
    ])).toThrow(/conflicting metadata.*0001/i);
  });

  it('detects stale generated bytes without relying on git tracking state', () => {
    const rendered = renderDeckLegalityCatalog([
      { id: 'PRINT-A', no: '0001/PRINT-A', kind: 'character', deckLimit: 3 },
    ]);

    expect(deckLegalityCatalogIsCurrent(rendered.replaceAll('\n', '\r\n'), rendered)).toBe(true);
    expect(deckLegalityCatalogIsCurrent(`${rendered}\n// stale`, rendered)).toBe(false);
  });
});
