// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B03080  |  scenarios: 2  |  fixtures: 3

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B03080 } from '@/cards/ct-p03/B03080';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_color",
    "no": "__DE_0_color",
    "kind": "character",
    "names": [
      "__DE_0_color"
    ],
    "colors": [
      "黒"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_kind",
    "no": "__DE_0_kind",
    "kind": "event",
    "names": [
      "__DE_0_kind"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B03080 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_color",
          "uid": "__DE_0_color_u",
          "state": "active"
        },
        {
          "cardId": "__DE_0_kind",
          "uid": "__DE_0_kind_u",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [
        "B03080"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseColors": [
        "赤"
      ],
      "fileCount": 7
    },
    "drive": {
      "kind": "event-use",
      "cardId": "B03080"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      },
      "optional:take"
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_color"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_kind"
      },
      {
        "kind": "zone",
        "cardId": "B03080",
        "zone": "hand",
        "side": "self",
        "present": false
      }
    ]
  },
  {
    "name": "B03080 optional-decline (inner effect does not fire)",
    "setup": {
      "selfScene": [],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_color",
          "uid": "__DE_0_color_u",
          "state": "active"
        },
        {
          "cardId": "__DE_0_kind",
          "uid": "__DE_0_kind_u",
          "state": "active"
        }
      ],
      "hand": [
        "B03080"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseColors": [
        "赤"
      ],
      "fileCount": 7
    },
    "drive": {
      "kind": "event-use",
      "cardId": "B03080"
    },
    "script": [
      "optional:decline"
    ],
    "expect": [
      {
        "kind": "deckDelta",
        "side": "self",
        "n": 0
      }
    ]
  }
];

describe('B03080 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B03080, FIXTURES, sc);
    });
  }
});
