// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B04077  |  scenarios: 2  |  fixtures: 1

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B04077 } from '@/cards/ct-p04/B04077';

const FIXTURES: CardDef[] = [
  {
    "id": "__HAND_FODDER__",
    "no": "__HAND_FODDER__",
    "kind": "character",
    "names": [
      "__HAND_FODDER__"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B04077 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B04077",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [],
    "expect": []
  },
  {
    "name": "B04077 condition-off (caseStatus!=解決編) -> no prompt",
    "setup": {
      "selfScene": [
        {
          "cardId": "B04077",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "事件編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [],
    "expect": [
      {
        "kind": "noPromptSurfaced"
      }
    ]
  }
];

describe('B04077 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B04077, FIXTURES, sc);
    });
  }
});
