// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B04027  |  scenarios: 2  |  fixtures: 4

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B04027 } from '@/cards/ct-p04/B04027';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 7000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_apMin",
    "no": "__DE_0_apMin",
    "kind": "character",
    "names": [
      "__DE_0_apMin"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 6000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__IN_1",
    "no": "__IN_1",
    "kind": "character",
    "names": [
      "__IN_1"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_1_apMax",
    "no": "__DE_1_apMax",
    "kind": "character",
    "names": [
      "__DE_1_apMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 6000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B04027 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "partnerColors": [
        "緑"
      ],
      "caseStatus": "解決編",
      "selfScene": [],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMin",
          "uid": "__DE_0_apMin_u",
          "state": "active"
        },
        {
          "cardId": "__IN_1",
          "uid": "__INU_1",
          "state": "active"
        },
        {
          "cardId": "__DE_1_apMax",
          "uid": "__DE_1_apMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "B04027"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseColors": [
        "緑"
      ],
      "fileCount": 5
    },
    "drive": {
      "kind": "event-use",
      "cardId": "B04027"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      },
      {
        "pickCardId": "__IN_1"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_apMin"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": false
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 1,
        "cardId": "__DE_1_apMax"
      },
      {
        "kind": "zone",
        "cardId": "__IN_1",
        "zone": "scene",
        "side": "opp",
        "present": false
      },
      {
        "kind": "zone",
        "cardId": "B04027",
        "zone": "hand",
        "side": "self",
        "present": false
      }
    ]
  },
  {
    "name": "B04027 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "partnerColors": [
        "緑"
      ],
      "caseStatus": "解決編",
      "selfScene": [],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMin",
          "uid": "__DE_0_apMin_u",
          "state": "active"
        },
        {
          "cardId": "__IN_1",
          "uid": "__INU_1",
          "state": "active"
        },
        {
          "cardId": "__DE_1_apMax",
          "uid": "__DE_1_apMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "B04027"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseColors": [
        "緑"
      ],
      "fileCount": 5
    },
    "drive": {
      "kind": "event-use",
      "cardId": "B04027"
    },
    "script": [
      "pick:skip",
      {
        "pickCardId": "__IN_1"
      }
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  }
];

describe('B04027 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B04027, FIXTURES, sc);
    });
  }
});
