// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B04032  |  scenarios: 2  |  fixtures: 5

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B04032 } from '@/cards/ct-p04/B04032';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 7,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "探偵"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_levelMax",
    "no": "__DE_0_levelMax",
    "kind": "character",
    "names": [
      "__DE_0_levelMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 8,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "探偵"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_trait",
    "no": "__DE_0_trait",
    "kind": "character",
    "names": [
      "__DE_0_trait"
    ],
    "colors": [
      "赤"
    ],
    "level": 7,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "__DTRAIT__"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_kind",
    "no": "__DE_0_kind",
    "kind": "event",
    "names": [
      "__DE_0_kind"
    ],
    "colors": [
      "赤"
    ],
    "level": 7,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "探偵"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__HAND_FODDER__",
    "no": "__HAND_FODDER__",
    "kind": "character",
    "names": [
      "__HAND_FODDER__"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    // Overrides the harness filler def for opp deck top (registered first = wins).
    // souza(opp, x:2) reveals opp deck top 2 → this level-5 card makes
    // boundAnyMatchesFilter{$found, levelMin:5} true so the 突撃-grant pick surfaces.
    "id": "__DECK_O_0",
    "no": "__DECK_O_0",
    "kind": "character",
    "names": [
      "__DECK_O_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 5,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B04032 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B04032",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_levelMax",
          "uid": "__DE_0_levelMax_u",
          "state": "active"
        },
        {
          "cardId": "__DE_0_trait",
          "uid": "__DE_0_trait_u",
          "state": "active"
        },
        {
          "cardId": "__DE_0_kind",
          "uid": "__DE_0_kind_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a2"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_levelMax"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_trait"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_kind"
      }
    ]
  },
  {
    "name": "B04032 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B04032",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_levelMax",
          "uid": "__DE_0_levelMax_u",
          "state": "active"
        },
        {
          "cardId": "__DE_0_trait",
          "uid": "__DE_0_trait_u",
          "state": "active"
        },
        {
          "cardId": "__DE_0_kind",
          "uid": "__DE_0_kind_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a2"
    },
    "script": [
      "pick:skip"
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  }
];

describe('B04032 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B04032, FIXTURES, sc);
    });
  }
});
