// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B05081  |  scenarios: 2  |  fixtures: 1

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B05081 } from '@/cards/ct-p05/B05081';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B05081 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        }
      ],
      "hand": [
        "B05081"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseColors": [
        "赤"
      ],
      "fileCount": 7
    },
    "drive": {
      "kind": "event-use",
      "cardId": "B05081"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      }
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": false
      },
      {
        "kind": "zone",
        "cardId": "B05081",
        "zone": "hand",
        "side": "self",
        "present": false
      }
    ]
  },
  {
    "name": "B05081 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        }
      ],
      "hand": [
        "B05081"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseColors": [
        "赤"
      ],
      "fileCount": 7
    },
    "drive": {
      "kind": "event-use",
      "cardId": "B05081"
    },
    "script": [
      "pick:skip"
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  }
];

describe('B05081 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B05081, FIXTURES, sc);
    });
  }
});
