// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: PR289  |  scenarios: 1  |  fixtures: 2

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { PR289 } from '@/cards/pr-01/PR289';

const FIXTURES: CardDef[] = [
  {
    "id": "__HAND_FODDER__",
    "no": "__HAND_FODDER__",
    "kind": "character",
    "names": [
      "__HAND_FODDER__"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__COST_SCENE_0_0",
    "no": "__COST_SCENE_0_0",
    "kind": "character",
    "names": [
      "__COST_SCENE_0_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "少年探偵団"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "PR289 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "PR289",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__COST_SCENE_0_0",
          "uid": "__COST_SCENE_0_0_u",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a2"
    },
    "script": [],
    "expect": [
      {
        "kind": "deckDelta",
        "side": "self",
        "n": -1
      },
      {
        "kind": "zone",
        "cardId": "__COST_SCENE_0_0",
        "zone": "scene",
        "side": "self",
        "present": false
      },
      {
        "kind": "stacked",
        "hostUid": "__CARRIER__",
        "cardId": "__COST_SCENE_0_0",
        "present": true
      }
    ]
  }
];

describe('PR289 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(PR289, FIXTURES, sc);
    });
  }
});
