// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: PR292  |  scenarios: 3  |  fixtures: 3

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { PR292 } from '@/cards/pr-01/PR292';

// カットイン能力 shape (src/engine/read/keyword.ts abilityIsCutin と一致):
// type:'triggered' + scope:'on-hand' + trigger{hook:'effect:declared', optional:true}。
// defHasKeyword('カットイン') が true になる fixture を作るための最小 ability。
const CUTIN_ABILITY = {
  id: 'cutin',
  type: 'triggered',
  scope: 'on-hand',
  trigger: { hook: 'effect:declared', optional: true, selfOnly: true },
  effect: { kind: 'atom', verb: 'charModifyAP', args: { delta: 2000, scope: 'contact', uid: '$contact.byUid' } },
  description: '【カットイン】AP＋2000',
  ruleRefs: [],
} as unknown as CardDef['abilities'][number];

// PR292 a1 cost (removeDeckTop 3) で除去される 3 枚。costRemovedMatches{keyword:カットイン, color:黒, n:3}
// を満たすため、色=黒 かつ カットイン能力を持つ。deckTop で self デッキ最上部へ積む。
const CUTIN_BLACK = (n: number): CardDef => ({
  id: `__CUTIN_BLACK_${n}`,
  no: `__CUTIN_BLACK_${n}`,
  kind: 'character',
  names: [`__CUTIN_BLACK_${n}`],
  colors: ['黒'],
  level: 3,
  ap: 5000,
  lp: 1,
  traits: [],
  keywords: [],
  rarity: 'C',
  imageUrl: '',
  abilities: [CUTIN_ABILITY],
  ruleRefs: [],
});

const FIXTURES: CardDef[] = [
  CUTIN_BLACK(0),
  CUTIN_BLACK(1),
  CUTIN_BLACK(2),
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 7,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_levelMax",
    "no": "__DE_0_levelMax",
    "kind": "character",
    "names": [
      "__DE_0_levelMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 8,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__HAND_FODDER__",
    "no": "__HAND_FODDER__",
    "kind": "character",
    "names": [
      "__HAND_FODDER__"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "PR292 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "PR292",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_levelMax",
          "uid": "__DE_0_levelMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "deckTop": [
        "__CUTIN_BLACK_0",
        "__CUTIN_BLACK_1",
        "__CUTIN_BLACK_2"
      ],
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_levelMax"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": false
      }
    ]
  },
  {
    "name": "PR292 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [
        {
          "cardId": "PR292",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_levelMax",
          "uid": "__DE_0_levelMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "deckTop": [
        "__CUTIN_BLACK_0",
        "__CUTIN_BLACK_1",
        "__CUTIN_BLACK_2"
      ],
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      "pick:skip"
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  },
  {
    "name": "PR292 cost-gate: sleepSelf unpayable (self sleeping) -> canPay=false",
    "setup": {
      "selfScene": [
        {
          "cardId": "PR292",
          "uid": "__CARRIER__",
          "state": "sleep"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "cost-gate",
      "uid": "__CARRIER__",
      "abilityId": "a1",
      "expectCanPay": false
    },
    "script": [],
    "expect": []
  }
];

describe('PR292 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(PR292, FIXTURES, sc);
    });
  }
});
