// cards/ct-d01/D01001 江戸川コナン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const D01001: CardDef = {
  id: 'D01001',
  no: 'P001/D01001',
  kind: 'partner',
  names: ['江戸川コナン'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'D',
  imageUrl: '1714013100391822.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
