// cards/ct-d01/D01016 ピアノソナタ「月光」殺人事件 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const D01016: CardDef = {
  id: 'D01016',
  no: '0104/D01016',
  kind: 'case',
  names: ['ピアノソナタ「月光」殺人事件'],
  colors: ['青'],
  traits: [],
  rarity: 'D',
  imageUrl: '1714013100437938.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
