// cards/ct-d01/D01005 毛利小五郎 (キャラ) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 13-keywords.md, 17-icons.md, 24-qa-naming-stun.md
//
// 公式テキスト: 【パートナー青】〚突撃〛（登場したターンからすぐにアクションできる）

import type { CardDef } from '@/engine/types';
import { partnerColorKeyword } from '../_shared/index.js';

export const D01005: CardDef = {
  id: 'D01005',
  no: '0094/D01005',
  kind: 'character',
  names: ['毛利小五郎'],
  colors: ['青'],
  level: 5,
  ap: 5000,
  lp: 0,
  traits: ['探偵', '毛利探偵事務所'],
  keywords: [],
  rarity: 'D',
  imageUrl: '1714013100404259.jpg',
  abilities: [
  partnerColorKeyword({ color: '青', kw: '突撃', abilityId: 'a1' }),
  ],
  ruleRefs: ['rules/13-keywords.md', 'rules/17-icons.md'],
};
