// cards/ct-d04/D04001 赤井秀一 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const D04001: CardDef = {
  id: 'D04001',
  no: 'P005/D04001',
  kind: 'partner',
  names: ['赤井秀一'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'D',
  imageUrl: '1714013132375426.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
