// cards/ct-d04/D04003 赤井秀一 (キャラ) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 13-keywords.md, 17-icons.md, 24-qa-naming-stun.md
//
// 公式テキスト: 【パートナー赤】〚迅速〛（登場したターンからすぐに推理かアクションできる）

import type { CardDef } from '@/engine/types';
import { partnerColorKeyword } from '../_shared/index.js';

export const D04003: CardDef = {
  id: 'D04003',
  no: '0134/D04003',
  kind: 'character',
  names: ['赤井秀一'],
  colors: ['赤'],
  level: 7,
  ap: 6000,
  lp: 1,
  traits: ['FBI', '赤井家'],
  keywords: [],
  rarity: 'D',
  imageUrl: '1714013132382924.jpg',
  abilities: [
  partnerColorKeyword({ color: '赤', kw: '迅速', abilityId: 'a1' }),
  ],
  ruleRefs: ['rules/13-keywords.md', 'rules/17-icons.md'],
};
