// cards/ct-d04/D04001 赤井秀一 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const D04001: CardDef = {
  id: 'D04001',
  no: 'P005/D04001',
  kind: 'partner',
  names: ['赤井秀一'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'D',
  imageUrl: '1714013132375426.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
