// cards/ct-d04/D04013 アンドレ・キャメル (キャラ) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 13-keywords.md, 17-icons.md, 24-qa-naming-stun.md
//
// 公式テキスト: 【パートナー赤】〚突撃〛（登場したターンからすぐにアクションできる）

import type { CardDef } from '@/engine/types';
import { partnerColorKeyword } from '../_shared/index.js';

export const D04013: CardDef = {
  id: 'D04013',
  no: '0143/D04013',
  kind: 'character',
  names: ['アンドレ・キャメル'],
  colors: ['赤'],
  level: 5,
  ap: 5000,
  lp: 0,
  traits: ['FBI'],
  keywords: [],
  rarity: 'D',
  imageUrl: '1714013167754975.jpg',
  abilities: [
  partnerColorKeyword({ color: '赤', kw: '突撃', abilityId: 'a1' }),
  ],
  ruleRefs: ['rules/13-keywords.md', 'rules/17-icons.md'],
};
