// AUTO-GENERATED by scripts/gen-card-probes.cjs — then hand-fixed (see notes below).
// card: B01023  |  scenarios: 1  |  fixtures: 4
//
// Fixes: (1) deckTop places the picked card (__IN_0) into the deterministic top-5 so
//   deckRevealUntil surfaces it as a candidate; (2) __DE_0_kind is placed at deck index 5 (6th) so
//   candidatesExclude proves the reveal is bounded to top-5; (3) a self scene host (__HOST) is added
//   so a1's final charSetCard (fromSelf, n:1) has a target; (4) an opp scene char (__OPP) is added
//   so candidatesExclude proves charSetCard fromSelf excludes the opponent's scene.
// a2 (on-set-host contact:start AP+2000 rider) and a3 (【ヒラメキ】 evidence:remove-by-action draw)
//   are not driveable via this harness (no contact / evidence-remove flow) — no scenario generated
//   for them, which is correct (do not invent broken drives).

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B01023 } from '@/cards/ct-p01/B01023';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_kind",
    "no": "__DE_0_kind",
    "kind": "event",
    "names": [
      "__DE_0_kind"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__HOST",
    "no": "__HOST",
    "kind": "character",
    "names": [
      "__HOST"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 3000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__OPP",
    "no": "__OPP",
    "kind": "character",
    "names": [
      "__OPP"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 3000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B01023 a1 happy-path (reveal top-5, add 1 to hand, set event onto own scene char)",
    "setup": {
      "selfScene": [
        { "cardId": "__HOST", "uid": "__HOSTU__", "state": "active" }
      ],
      "oppScene": [
        { "cardId": "__OPP", "uid": "__OPPU__", "state": "active" }
      ],
      "hand": [
        "B01023"
      ],
      "deckTop": [
        "__IN_0",
        "__DECK_S_0",
        "__DECK_S_1",
        "__DECK_S_2",
        "__DECK_S_3",
        "__DE_0_kind"
      ],
      "deckSize": 6,
      "caseColors": [
        "青"
      ],
      "fileCount": 7
    },
    "drive": {
      "kind": "event-use",
      "cardId": "B01023"
    },
    "script": [
      { "pickCardId": "__IN_0" },
      { "pickCardId": "__HOST" }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_kind"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 1,
        "cardId": "__OPP"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "hand",
        "side": "self",
        "present": true
      },
      {
        "kind": "zone",
        "cardId": "B01023",
        "zone": "hand",
        "side": "self",
        "present": false
      },
      {
        "kind": "deckDelta",
        "side": "self",
        "n": -1
      }
    ]
  }
];

describe('B01023 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B01023, FIXTURES, sc);
    });
  }
});
