// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B03003  |  scenarios: 4  |  fixtures: 4 (hand-fixed: seed deckTop so cost-removed matches; +gate-off scenario)

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B03003 } from '@/cards/ct-p03/B03003';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 8,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_levelMax",
    "no": "__DE_0_levelMax",
    "kind": "character",
    "names": [
      "__DE_0_levelMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 9,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__HAND_FODDER__",
    "no": "__HAND_FODDER__",
    "kind": "character",
    "names": [
      "__HAND_FODDER__"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    // deckTop fixture: 特徴[少年探偵団] を持つキャラ。cost の removeDeckTop 3 でこれが
    // リムーブされると costRemovedMatches(trait 少年探偵団) が真 → conditional then が発火する。
    "id": "__DET_BOY__",
    "no": "__DET_BOY__",
    "kind": "character",
    "names": [
      "__DET_BOY__"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "少年探偵団"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B03003 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B03003",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_levelMax",
          "uid": "__DE_0_levelMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "deckTop": [
        "__DET_BOY__"
      ],
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_levelMax"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": false
      }
    ]
  },
  {
    "name": "B03003 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B03003",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_levelMax",
          "uid": "__DE_0_levelMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "deckTop": [
        "__DET_BOY__"
      ],
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      "pick:skip"
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  },
  {
    "name": "B03003 gate-off (no 阿笠博士/少年探偵団 in removed top-3 -> effect pick does not surface)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B03003",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_levelMax",
          "uid": "__DE_0_levelMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [],
    "expect": [
      {
        "kind": "noPromptSurfaced"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  },
  {
    "name": "B03003 cost-gate: sleepSelf unpayable (self sleeping) -> canPay=false",
    "setup": {
      "selfScene": [
        {
          "cardId": "B03003",
          "uid": "__CARRIER__",
          "state": "sleep"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "cost-gate",
      "uid": "__CARRIER__",
      "abilityId": "a1",
      "expectCanPay": false
    },
    "script": [],
    "expect": []
  }
];

describe('B03003 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B03003, FIXTURES, sc);
    });
  }
});
