// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B06078  |  scenarios: 3  |  fixtures: 4
// HAND-PATCHED (probe-fix): a1 cost = sleepChar(赤井家 lv>=6, self) + removeDeckTop 3 (both auto-pay,
//   no prompt). The effect (sceneRemove ap<=8000) only fires when the cost-removed top-3 CONTAINED a
//   赤井家 card (costRemovedMatches). Happy/skip seed deckTop with a 赤井家 fixture; the added negative
//   scenario omits it to prove the effect (and its prompt) does NOT fire.

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B06078 } from '@/cards/ct-p06/B06078';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 8000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_apMax",
    "no": "__DE_0_apMax",
    "kind": "character",
    "names": [
      "__DE_0_apMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 9000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__HAND_FODDER__",
    "no": "__HAND_FODDER__",
    "kind": "character",
    "names": [
      "__HAND_FODDER__"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__AKAI",
    "no": "__AKAI",
    "kind": "character",
    "names": [
      "__AKAI"
    ],
    "colors": [
      "赤"
    ],
    "level": 6,
    "ap": 9000,
    "lp": 1,
    "traits": [
      "赤井家"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B06078 happy-path (cost removes 赤井家 -> effect fires; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B06078",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__AKAI",
          "uid": "__AKAI_u",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "deckTop": [
        "__AKAI"
      ],
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_apMax"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": false
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "remove",
        "side": "opp",
        "present": true
      }
    ]
  },
  {
    "name": "B06078 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B06078",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__AKAI",
          "uid": "__AKAI_u",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "deckTop": [
        "__AKAI"
      ],
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      "pick:skip"
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  },
  {
    "name": "B06078 cost removed NO 赤井家 -> conditional off, no prompt, target unchanged",
    "setup": {
      "selfScene": [
        {
          "cardId": "B06078",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__AKAI",
          "uid": "__AKAI_u",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [],
    "expect": [
      {
        "kind": "noPromptSurfaced"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  }
];

describe('B06078 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B06078, FIXTURES, sc);
    });
  }
});
