// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B06062  |  scenarios: 2  |  fixtures: 6
// HAND-PATCHED (probe-fix): sequence has TWO surfacing effect picks —
//   pick#0 sceneRemove (either scene, ap<=8000) then pick#1 charSetCard (self scene, lv>=8 trait YAIBA).
//   charSetCard picks from SELF scene, so the lv8-YAIBA target + its decoys must live in selfScene.

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B06062 } from '@/cards/ct-p06/B06062';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 8000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_apMax",
    "no": "__DE_0_apMax",
    "kind": "character",
    "names": [
      "__DE_0_apMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 9000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__IN_1",
    "no": "__IN_1",
    "kind": "character",
    "names": [
      "__IN_1"
    ],
    "colors": [
      "赤"
    ],
    "level": 8,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "YAIBA"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_1_levelMin",
    "no": "__DE_1_levelMin",
    "kind": "character",
    "names": [
      "__DE_1_levelMin"
    ],
    "colors": [
      "赤"
    ],
    "level": 7,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "YAIBA"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_1_trait",
    "no": "__DE_1_trait",
    "kind": "character",
    "names": [
      "__DE_1_trait"
    ],
    "colors": [
      "赤"
    ],
    "level": 8,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "__DTRAIT__"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_1_kind",
    "no": "__DE_1_kind",
    "kind": "event",
    "names": [
      "__DE_1_kind"
    ],
    "colors": [
      "赤"
    ],
    "level": 8,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "YAIBA"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B06062 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "__IN_1",
          "uid": "__INU_1",
          "state": "active"
        },
        {
          "cardId": "__DE_1_levelMin",
          "uid": "__DE_1_levelMin_u",
          "state": "active"
        },
        {
          "cardId": "__DE_1_trait",
          "uid": "__DE_1_trait_u",
          "state": "active"
        },
        {
          "cardId": "__DE_1_kind",
          "uid": "__DE_1_kind_u",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "B06062"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseColors": [
        "白"
      ],
      "fileCount": 7
    },
    "drive": {
      "kind": "event-use",
      "cardId": "B06062"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      },
      {
        "pickCardId": "__IN_1"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_apMax"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": false
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 1,
        "cardId": "__DE_1_levelMin"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 1,
        "cardId": "__DE_1_trait"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 1,
        "cardId": "__DE_1_kind"
      },
      {
        "kind": "deckDelta",
        "side": "self",
        "n": -3
      },
      {
        "kind": "zone",
        "cardId": "B06062",
        "zone": "hand",
        "side": "self",
        "present": false
      }
    ]
  },
  {
    "name": "B06062 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [
        {
          "cardId": "__IN_1",
          "uid": "__INU_1",
          "state": "active"
        },
        {
          "cardId": "__DE_1_levelMin",
          "uid": "__DE_1_levelMin_u",
          "state": "active"
        },
        {
          "cardId": "__DE_1_trait",
          "uid": "__DE_1_trait_u",
          "state": "active"
        },
        {
          "cardId": "__DE_1_kind",
          "uid": "__DE_1_kind_u",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "B06062"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseColors": [
        "白"
      ],
      "fileCount": 7
    },
    "drive": {
      "kind": "event-use",
      "cardId": "B06062"
    },
    "script": [
      "pick:skip",
      {
        "pickCardId": "__IN_1"
      }
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      },
      {
        "kind": "deckDelta",
        "side": "self",
        "n": -3
      }
    ]
  }
];

describe('B06062 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B06062, FIXTURES, sc);
    });
  }
});
