// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B08025  |  scenarios: 3  |  fixtures: 5
// HAND-PATCHED (probe-fix): a1 condition = partnerColor 緑 (setup partnerColors:['緑']);
//   cost = removeDeckTop 3 (auto-pay, no prompt); effect fires ONLY when cost-removed top-3 contained
//   cardName 大岡紅葉 or 伊織無我 (costRemovedMatches). Happy/skip seed deckTop with a 大岡紅葉 fixture.
//   Effect = sequence(sceneRemove ap<=8000 pick, charSetCard fromDeckTop faceDown onto $self):
//   only sceneRemove surfaces a pick; deckDelta self = -3 (cost) -1 (set) = -4.
// MANUAL-NOTE: the condition-off scenario cannot truly isolate the partnerColor gate. useDeclaredAbility
//   (the harness's execution path) does NOT re-check ability.condition — that gate lives only in
//   canDeclaredAbility (UI/AI enumeration), which no harness drive exercises. So a mismatched
//   partnerColor still lets the effect fire IF the cost removes a named card. The scenario therefore
//   keeps its ORIGINAL no-named-deckTop setup: noPromptSurfaced here derives from costRemovedMatches=false
//   (no 大岡紅葉/伊織無我 removed), which is a genuine assertion, not from the partnerColor mismatch.

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B08025 } from '@/cards/ct-p08/B08025';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 8000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_apMax",
    "no": "__DE_0_apMax",
    "kind": "character",
    "names": [
      "__DE_0_apMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 9000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__IN_1",
    "no": "__IN_1",
    "kind": "character",
    "names": [
      "__IN_1"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__HAND_FODDER__",
    "no": "__HAND_FODDER__",
    "kind": "character",
    "names": [
      "__HAND_FODDER__"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__NAMED",
    "no": "__NAMED",
    "kind": "character",
    "names": [
      "大岡紅葉"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B08025 happy-path (cost removes 大岡紅葉 -> effect fires; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B08025",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        },
        {
          "cardId": "__IN_1",
          "uid": "__INU_1",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "deckTop": [
        "__NAMED"
      ],
      "caseStatus": "解決編",
      "partnerColors": [
        "緑"
      ]
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_apMax"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": false
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "remove",
        "side": "opp",
        "present": true
      },
      {
        "kind": "deckDelta",
        "side": "self",
        "n": -4
      }
    ]
  },
  {
    "name": "B08025 condition-off (partnerColor mismatch) -> no prompt",
    "setup": {
      "selfScene": [
        {
          "cardId": "B08025",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        },
        {
          "cardId": "__IN_1",
          "uid": "__INU_1",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編",
      "partnerColors": [
        "__NOMATCH__"
      ]
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [],
    "expect": [
      {
        "kind": "noPromptSurfaced"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  },
  {
    "name": "B08025 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B08025",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        },
        {
          "cardId": "__IN_1",
          "uid": "__INU_1",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "deckTop": [
        "__NAMED"
      ],
      "caseStatus": "解決編",
      "partnerColors": [
        "緑"
      ]
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      "pick:skip"
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      },
      {
        "kind": "deckDelta",
        "side": "self",
        "n": -4
      }
    ]
  }
];

describe('B08025 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B08025, FIXTURES, sc);
    });
  }
});
