// AUTO-GENERATED by scripts/gen-card-probes.cjs — then hand-fixed (see MANUAL-NOTE below).
// card: B08076  |  scenarios: 3  |  fixtures: 2
//
// MANUAL-NOTE (2026-07-10): The generated happy-path/negative scenarios drove a2 (declared) to
//   exercise its EFFECT (sceneEnter conditional / decoy exclusion / all-scene-named condition).
//   That effect is UN-DRIVABLE in this harness: a2's cost is `flipFaceUpEvidence n:{2,2}` and the
//   harness `declared` drive calls activateDeclaredAbility WITHOUT costParams. `flipFaceUpEvidence`
//   pay (src/engine/cost/pay.ts readFlipIndices) has NO auto-fill fallback — it reads only
//   ctx.dyn.costParams.flipFaceUpEvidence.indices and throws `picks 0 out of [2,2]` when absent
//   (verified empirically: adding 2 face-down evidence to setup does NOT fix pay; state evidence is
//   never auto-selected). Contrast sceneToDeckBottom, which DOES head-fix auto-pay from candidates.
//   => Strongest drivable coverage = `cost-gate` (canPay, which DOES read state evidence). The three
//   scenarios below pin both cost gates: (1) payable when 解決編 + ≥2 face-down evidence + ≥1 scene
//   character; (2) unpayable with only 1 face-down evidence (flipFaceUpEvidence gate); (3) unpayable
//   with no scene character (sceneToDeckBottom gate). The a2 effect body + declaration condition
//   (現場すべてが 佐藤美和子/高木渉、remove から lv≤4 を 1枚まで sleep 登場) cannot be exercised here.

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B08076 } from '@/cards/ct-p08/B08076';

const FIXTURES: CardDef[] = [
  {
    "id": "__SATO__",
    "no": "__SATO__",
    "kind": "character",
    "names": [
      "佐藤美和子"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 3000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__TAKAGI__",
    "no": "__TAKAGI__",
    "kind": "character",
    "names": [
      "高木渉"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 3000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

// carrier = B08076 (a case card) placed as a scene entry so the harness routes
// activateDeclaredAbility(uid) → the case's declared ability a2. It is kind:'case', so it is NOT
// counted by any {kind:'character'} cost/condition filter (verified empirically).
const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B08076 a2 cost-gate PASS (解決編 + 2 face-down evidence + >=1 scene char -> canPay)",
    "setup": {
      "caseStatus": "解決編",
      "selfScene": [
        { "cardId": "B08076", "uid": "__CARRIER__", "state": "active" },
        { "cardId": "__SATO__", "uid": "__C1__", "state": "active" },
        { "cardId": "__TAKAGI__", "uid": "__C2__", "state": "active" }
      ],
      "evidence": [
        { "cardId": "__EV0__", "faceUp": false },
        { "cardId": "__EV1__", "faceUp": false }
      ],
      "deckSize": 6
    },
    "drive": {
      "kind": "cost-gate",
      "uid": "__CARRIER__",
      "abilityId": "a2",
      "expectCanPay": true
    },
    "expect": []
  },
  {
    "name": "B08076 a2 cost-gate FAIL (only 1 face-down evidence -> flipFaceUpEvidence n:2 unpayable)",
    "setup": {
      "caseStatus": "解決編",
      "selfScene": [
        { "cardId": "B08076", "uid": "__CARRIER__", "state": "active" },
        { "cardId": "__SATO__", "uid": "__C1__", "state": "active" },
        { "cardId": "__TAKAGI__", "uid": "__C2__", "state": "active" }
      ],
      "evidence": [
        { "cardId": "__EV0__", "faceUp": false }
      ],
      "deckSize": 6
    },
    "drive": {
      "kind": "cost-gate",
      "uid": "__CARRIER__",
      "abilityId": "a2",
      "expectCanPay": false
    },
    "expect": []
  },
  {
    "name": "B08076 a2 cost-gate FAIL (no scene character -> sceneToDeckBottom pick 1 char unpayable)",
    "setup": {
      "caseStatus": "解決編",
      "selfScene": [
        { "cardId": "B08076", "uid": "__CARRIER__", "state": "active" }
      ],
      "evidence": [
        { "cardId": "__EV0__", "faceUp": false },
        { "cardId": "__EV1__", "faceUp": false }
      ],
      "deckSize": 6
    },
    "drive": {
      "kind": "cost-gate",
      "uid": "__CARRIER__",
      "abilityId": "a2",
      "expectCanPay": false
    },
    "expect": []
  }
];

describe('B08076 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B08076, FIXTURES, sc);
    });
  }
});
