// cards/ct-d05/D05016 緋色の疑惑 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const D05016: CardDef = {
  id: 'D05016',
  no: '0160/D05016',
  kind: 'case',
  names: ['緋色の疑惑'],
  colors: ['黄'],
  traits: [],
  rarity: 'D',
  imageUrl: '1714013167819235.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
