// cards/ct-d05/D05009 風見裕也 (キャラ) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 13-keywords.md, 17-icons.md, 24-qa-naming-stun.md
//
// 公式テキスト: 【パートナー黄】〚突撃〛（登場したターンからすぐにアクションできる）

import type { CardDef } from '@/engine/types';
import { partnerColorKeyword } from '../_shared/index.js';

export const D05009: CardDef = {
  id: 'D05009',
  no: '0154/D05009',
  kind: 'character',
  names: ['風見裕也'],
  colors: ['黄'],
  level: 5,
  ap: 5000,
  lp: 0,
  traits: ['警察', '警視庁', '公安'],
  keywords: [],
  rarity: 'D',
  imageUrl: '1714013167797743.jpg',
  abilities: [
  partnerColorKeyword({ color: '黄', kw: '突撃', abilityId: 'a1' }),
  ],
  ruleRefs: ['rules/13-keywords.md', 'rules/17-icons.md'],
};
