// cards/_generated/complex-cutins — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// 36 件の複雑カットイン (条件付きドロー / スケーリング / 全リムーブ / アクティブ化 / DEFERRED stub)。手で編集しない。
import type { CardDef } from '@/engine/types';

import { D10013 } from '../ct-d10/D10013.js';
import { D10014 } from '../ct-d10/D10014.js';
import { B01097 } from '../ct-p01/B01097.js';
import { B01097P } from '../ct-p01/B01097P.js';
import { B01098 } from '../ct-p01/B01098.js';
import { B01098P } from '../ct-p01/B01098P.js';
import { B03017 } from '../ct-p03/B03017.js';
import { B03034 } from '../ct-p03/B03034.js';
import { B03039 } from '../ct-p03/B03039.js';
import { B05010 } from '../ct-p05/B05010.js';
import { B05036 } from '../ct-p05/B05036.js';
import { B05040 } from '../ct-p05/B05040.js';
import { B05070 } from '../ct-p05/B05070.js';
import { B05095 } from '../ct-p05/B05095.js';
import { B05096 } from '../ct-p05/B05096.js';
import { B05096P } from '../ct-p05/B05096P.js';
import { B06041 } from '../ct-p06/B06041.js';
import { B06050 } from '../ct-p06/B06050.js';
import { B06050P } from '../ct-p06/B06050P.js';
import { B06092 } from '../ct-p06/B06092.js';
import { B07009 } from '../ct-p07/B07009.js';
import { B07009P } from '../ct-p07/B07009P.js';
import { B07085 } from '../ct-p07/B07085.js';
import { B08055 } from '../ct-p08/B08055.js';
import { B08055P } from '../ct-p08/B08055P.js';
import { B09031 } from '../ct-p09/B09031.js';
import { PR050 } from '../pr-01/PR050.js';
import { PR051 } from '../pr-01/PR051.js';
import { PR087 } from '../pr-01/PR087.js';
import { PR093 } from '../pr-01/PR093.js';
import { PR103 } from '../pr-01/PR103.js';
import { PR109 } from '../pr-01/PR109.js';
import { PR169 } from '../pr-01/PR169.js';
import { PR239 } from '../pr-01/PR239.js';
import { PR245 } from '../pr-01/PR245.js';
import { PR287 } from '../pr-01/PR287.js';

export const GENERATED_COMPLEX_CUTINS: CardDef[] = [
  D10013, D10014, B01097, B01097P, B01098, B01098P, B03017, B03034,
  B03039, B05010, B05036, B05040, B05070, B05095, B05096, B05096P,
  B06041, B06050, B06050P, B06092, B07009, B07009P, B07085, B08055,
  B08055P, B09031, PR050, PR051, PR087, PR093, PR103, PR109,
  PR169, PR239, PR245, PR287,
];
