// cards/_generated/partners — auto-generated by scripts/gen-cards/gen-partners.cjs
// 276 件の非MVP partner CardDef (abilities:[] stub) を集約。手で編集しない。
import type { CardDef } from '@/engine/types';

import { D01001 } from '../ct-d01/D01001.js';
import { D02001 } from '../ct-d02/D02001.js';
import { D03001 } from '../ct-d03/D03001.js';
import { D04001 } from '../ct-d04/D04001.js';
import { D05001 } from '../ct-d05/D05001.js';
import { D06001 } from '../ct-d06/D06001.js';
import { D06002 } from '../ct-d06/D06002.js';
import { D07001 } from '../ct-d07/D07001.js';
import { D09001 } from '../ct-d09/D09001.js';
import { D09002 } from '../ct-d09/D09002.js';
import { D09003 } from '../ct-d09/D09003.js';
import { D10001 } from '../ct-d10/D10001.js';
import { D10002 } from '../ct-d10/D10002.js';
import { B01001 } from '../ct-p01/B01001.js';
import { B01001P } from '../ct-p01/B01001P.js';
import { B01001Sec1 } from '../ct-p01/B01001Sec1.js';
import { B01001Sec2 } from '../ct-p01/B01001Sec2.js';
import { B01002 } from '../ct-p01/B01002.js';
import { B01002P } from '../ct-p01/B01002P.js';
import { B01003 } from '../ct-p01/B01003.js';
import { B01003P } from '../ct-p01/B01003P.js';
import { B01004 } from '../ct-p01/B01004.js';
import { B01004P } from '../ct-p01/B01004P.js';
import { B01025 } from '../ct-p01/B01025.js';
import { B01025P } from '../ct-p01/B01025P.js';
import { B01026 } from '../ct-p01/B01026.js';
import { B01026P } from '../ct-p01/B01026P.js';
import { B01042 } from '../ct-p01/B01042.js';
import { B01042P } from '../ct-p01/B01042P.js';
import { B01043 } from '../ct-p01/B01043.js';
import { B01043P } from '../ct-p01/B01043P.js';
import { B01060 } from '../ct-p01/B01060.js';
import { B01060P } from '../ct-p01/B01060P.js';
import { B01061 } from '../ct-p01/B01061.js';
import { B01061P } from '../ct-p01/B01061P.js';
import { B01079 } from '../ct-p01/B01079.js';
import { B01079P } from '../ct-p01/B01079P.js';
import { B01080 } from '../ct-p01/B01080.js';
import { B01080P } from '../ct-p01/B01080P.js';
import { B02001 } from '../ct-p02/B02001.js';
import { B02001P } from '../ct-p02/B02001P.js';
import { B02016 } from '../ct-p02/B02016.js';
import { B02016P } from '../ct-p02/B02016P.js';
import { B02016Sec1 } from '../ct-p02/B02016Sec1.js';
import { B02016Sec2 } from '../ct-p02/B02016Sec2.js';
import { B02017 } from '../ct-p02/B02017.js';
import { B02017P } from '../ct-p02/B02017P.js';
import { B02035 } from '../ct-p02/B02035.js';
import { B02035P } from '../ct-p02/B02035P.js';
import { B02035Sec1 } from '../ct-p02/B02035Sec1.js';
import { B02035Sec2 } from '../ct-p02/B02035Sec2.js';
import { B02036 } from '../ct-p02/B02036.js';
import { B02036P } from '../ct-p02/B02036P.js';
import { B02037 } from '../ct-p02/B02037.js';
import { B02037P } from '../ct-p02/B02037P.js';
import { B02055 } from '../ct-p02/B02055.js';
import { B02055P } from '../ct-p02/B02055P.js';
import { B02056 } from '../ct-p02/B02056.js';
import { B02056P } from '../ct-p02/B02056P.js';
import { B02070 } from '../ct-p02/B02070.js';
import { B02070P } from '../ct-p02/B02070P.js';
import { B02071 } from '../ct-p02/B02071.js';
import { B02071P } from '../ct-p02/B02071P.js';
import { B03001 } from '../ct-p03/B03001.js';
import { B03001P } from '../ct-p03/B03001P.js';
import { B03027 } from '../ct-p03/B03027.js';
import { B03027P } from '../ct-p03/B03027P.js';
import { B03044 } from '../ct-p03/B03044.js';
import { B03045 } from '../ct-p03/B03045.js';
import { B03065 } from '../ct-p03/B03065.js';
import { B03065P } from '../ct-p03/B03065P.js';
import { B03083 } from '../ct-p03/B03083.js';
import { B03083P } from '../ct-p03/B03083P.js';
import { B03106 } from '../ct-p03/B03106.js';
import { B03106P } from '../ct-p03/B03106P.js';
import { B03107 } from '../ct-p03/B03107.js';
import { B03107P } from '../ct-p03/B03107P.js';
import { B03108 } from '../ct-p03/B03108.js';
import { B03108P } from '../ct-p03/B03108P.js';
import { B03109 } from '../ct-p03/B03109.js';
import { B03139Sec1 } from '../ct-p03/B03139Sec1.js';
import { B03139Sec2 } from '../ct-p03/B03139Sec2.js';
import { B03140Sec1 } from '../ct-p03/B03140Sec1.js';
import { B03140Sec2 } from '../ct-p03/B03140Sec2.js';
import { B04001 } from '../ct-p04/B04001.js';
import { B04001P } from '../ct-p04/B04001P.js';
import { B04001Sec1 } from '../ct-p04/B04001Sec1.js';
import { B04001Sec2 } from '../ct-p04/B04001Sec2.js';
import { B04002 } from '../ct-p04/B04002.js';
import { B04002P } from '../ct-p04/B04002P.js';
import { B04002Sec1 } from '../ct-p04/B04002Sec1.js';
import { B04002Sec2 } from '../ct-p04/B04002Sec2.js';
import { B04016 } from '../ct-p04/B04016.js';
import { B04016P } from '../ct-p04/B04016P.js';
import { B04029 } from '../ct-p04/B04029.js';
import { B04029P } from '../ct-p04/B04029P.js';
import { B04043 } from '../ct-p04/B04043.js';
import { B04043P } from '../ct-p04/B04043P.js';
import { B04044 } from '../ct-p04/B04044.js';
import { B04044P } from '../ct-p04/B04044P.js';
import { B04045 } from '../ct-p04/B04045.js';
import { B04045P } from '../ct-p04/B04045P.js';
import { B04065 } from '../ct-p04/B04065.js';
import { B04065P } from '../ct-p04/B04065P.js';
import { B04066 } from '../ct-p04/B04066.js';
import { B04066P } from '../ct-p04/B04066P.js';
import { B04067 } from '../ct-p04/B04067.js';
import { B04067P } from '../ct-p04/B04067P.js';
import { B04087 } from '../ct-p04/B04087.js';
import { B04087P } from '../ct-p04/B04087P.js';
import { B05001 } from '../ct-p05/B05001.js';
import { B05001P } from '../ct-p05/B05001P.js';
import { B05002 } from '../ct-p05/B05002.js';
import { B05002P } from '../ct-p05/B05002P.js';
import { B05003 } from '../ct-p05/B05003.js';
import { B05003P } from '../ct-p05/B05003P.js';
import { B05004 } from '../ct-p05/B05004.js';
import { B05004P } from '../ct-p05/B05004P.js';
import { B05025 } from '../ct-p05/B05025.js';
import { B05025P } from '../ct-p05/B05025P.js';
import { B05026 } from '../ct-p05/B05026.js';
import { B05026P } from '../ct-p05/B05026P.js';
import { B05043 } from '../ct-p05/B05043.js';
import { B05043P } from '../ct-p05/B05043P.js';
import { B05044 } from '../ct-p05/B05044.js';
import { B05044P } from '../ct-p05/B05044P.js';
import { B05064 } from '../ct-p05/B05064.js';
import { B05064P } from '../ct-p05/B05064P.js';
import { B05065 } from '../ct-p05/B05065.js';
import { B05065P } from '../ct-p05/B05065P.js';
import { B05084 } from '../ct-p05/B05084.js';
import { B05084P } from '../ct-p05/B05084P.js';
import { B05084Sec1 } from '../ct-p05/B05084Sec1.js';
import { B05084Sec2 } from '../ct-p05/B05084Sec2.js';
import { B05085 } from '../ct-p05/B05085.js';
import { B05085P } from '../ct-p05/B05085P.js';
import { B05085Sec1 } from '../ct-p05/B05085Sec1.js';
import { B05085Sec2 } from '../ct-p05/B05085Sec2.js';
import { B05104 } from '../ct-p05/B05104.js';
import { B05104P } from '../ct-p05/B05104P.js';
import { B05105 } from '../ct-p05/B05105.js';
import { B05105P } from '../ct-p05/B05105P.js';
import { B06001Sec1 } from '../ct-p06/B06001Sec1.js';
import { B06001Sec2 } from '../ct-p06/B06001Sec2.js';
import { B06002 } from '../ct-p06/B06002.js';
import { B06002P } from '../ct-p06/B06002P.js';
import { B06014 } from '../ct-p06/B06014.js';
import { B06014P } from '../ct-p06/B06014P.js';
import { B06015 } from '../ct-p06/B06015.js';
import { B06015P } from '../ct-p06/B06015P.js';
import { B06044 } from '../ct-p06/B06044.js';
import { B06044P } from '../ct-p06/B06044P.js';
import { B06044Sec1 } from '../ct-p06/B06044Sec1.js';
import { B06044Sec2 } from '../ct-p06/B06044Sec2.js';
import { B06045 } from '../ct-p06/B06045.js';
import { B06045P } from '../ct-p06/B06045P.js';
import { B06073 } from '../ct-p06/B06073.js';
import { B06073P } from '../ct-p06/B06073P.js';
import { B06083 } from '../ct-p06/B06083.js';
import { B06083P } from '../ct-p06/B06083P.js';
import { B06096 } from '../ct-p06/B06096.js';
import { B06096P } from '../ct-p06/B06096P.js';
import { B06097 } from '../ct-p06/B06097.js';
import { B06097P } from '../ct-p06/B06097P.js';
import { B07027 } from '../ct-p07/B07027.js';
import { B07027P } from '../ct-p07/B07027P.js';
import { B07027Sec1 } from '../ct-p07/B07027Sec1.js';
import { B07027Sec2 } from '../ct-p07/B07027Sec2.js';
import { B07028 } from '../ct-p07/B07028.js';
import { B07028P } from '../ct-p07/B07028P.js';
import { B07028Sec1 } from '../ct-p07/B07028Sec1.js';
import { B07028Sec2 } from '../ct-p07/B07028Sec2.js';
import { B07029 } from '../ct-p07/B07029.js';
import { B07029P } from '../ct-p07/B07029P.js';
import { B07078 } from '../ct-p07/B07078.js';
import { B07078P } from '../ct-p07/B07078P.js';
import { B07092 } from '../ct-p07/B07092.js';
import { B07092P } from '../ct-p07/B07092P.js';
import { B08001Sec1 } from '../ct-p08/B08001Sec1.js';
import { B08001Sec2 } from '../ct-p08/B08001Sec2.js';
import { B08018 } from '../ct-p08/B08018.js';
import { B08018P } from '../ct-p08/B08018P.js';
import { B08031 } from '../ct-p08/B08031.js';
import { B08031P } from '../ct-p08/B08031P.js';
import { B08045 } from '../ct-p08/B08045.js';
import { B08045P } from '../ct-p08/B08045P.js';
import { B08061 } from '../ct-p08/B08061.js';
import { B08061P } from '../ct-p08/B08061P.js';
import { B08077Sec1 } from '../ct-p08/B08077Sec1.js';
import { B08077Sec2 } from '../ct-p08/B08077Sec2.js';
import { B09001 } from '../ct-p09/B09001.js';
import { B09001P } from '../ct-p09/B09001P.js';
import { B09020 } from '../ct-p09/B09020.js';
import { B09020P } from '../ct-p09/B09020P.js';
import { B09035 } from '../ct-p09/B09035.js';
import { B09035P } from '../ct-p09/B09035P.js';
import { B09053 } from '../ct-p09/B09053.js';
import { B09053P } from '../ct-p09/B09053P.js';
import { B09068 } from '../ct-p09/B09068.js';
import { B09068P } from '../ct-p09/B09068P.js';
import { B09068Sec1 } from '../ct-p09/B09068Sec1.js';
import { B09068Sec2 } from '../ct-p09/B09068Sec2.js';
import { B09069 } from '../ct-p09/B09069.js';
import { B09069P } from '../ct-p09/B09069P.js';
import { B09069Sec1 } from '../ct-p09/B09069Sec1.js';
import { B09069Sec2 } from '../ct-p09/B09069Sec2.js';
import { B09091 } from '../ct-p09/B09091.js';
import { B09091P } from '../ct-p09/B09091P.js';
import { PR001 } from '../pr-01/PR001.js';
import { PR002 } from '../pr-01/PR002.js';
import { PR003 } from '../pr-01/PR003.js';
import { PR004 } from '../pr-01/PR004.js';
import { PR005 } from '../pr-01/PR005.js';
import { PR007 } from '../pr-01/PR007.js';
import { PR008 } from '../pr-01/PR008.js';
import { PR009 } from '../pr-01/PR009.js';
import { PR010 } from '../pr-01/PR010.js';
import { PR011 } from '../pr-01/PR011.js';
import { PR022 } from '../pr-01/PR022.js';
import { PR069 } from '../pr-01/PR069.js';
import { PR070 } from '../pr-01/PR070.js';
import { PR071 } from '../pr-01/PR071.js';
import { PR072 } from '../pr-01/PR072.js';
import { PR074 } from '../pr-01/PR074.js';
import { PR075 } from '../pr-01/PR075.js';
import { PR076 } from '../pr-01/PR076.js';
import { PR077 } from '../pr-01/PR077.js';
import { PR078 } from '../pr-01/PR078.js';
import { PR079 } from '../pr-01/PR079.js';
import { PR110 } from '../pr-01/PR110.js';
import { PR111 } from '../pr-01/PR111.js';
import { PR112 } from '../pr-01/PR112.js';
import { PR113 } from '../pr-01/PR113.js';
import { PR119 } from '../pr-01/PR119.js';
import { PR120 } from '../pr-01/PR120.js';
import { PR121 } from '../pr-01/PR121.js';
import { PR122 } from '../pr-01/PR122.js';
import { PR123 } from '../pr-01/PR123.js';
import { PR124 } from '../pr-01/PR124.js';
import { PR125 } from '../pr-01/PR125.js';
import { PR126 } from '../pr-01/PR126.js';
import { PR127 } from '../pr-01/PR127.js';
import { PR128 } from '../pr-01/PR128.js';
import { PR129 } from '../pr-01/PR129.js';
import { PR130 } from '../pr-01/PR130.js';
import { PR190 } from '../pr-01/PR190.js';
import { PR191 } from '../pr-01/PR191.js';
import { PR214 } from '../pr-01/PR214.js';
import { PR215 } from '../pr-01/PR215.js';
import { PR216 } from '../pr-01/PR216.js';
import { PR217 } from '../pr-01/PR217.js';
import { PR219 } from '../pr-01/PR219.js';
import { PR220 } from '../pr-01/PR220.js';
import { PR221 } from '../pr-01/PR221.js';
import { PR222 } from '../pr-01/PR222.js';
import { PR223 } from '../pr-01/PR223.js';
import { PR224 } from '../pr-01/PR224.js';
import { PR225 } from '../pr-01/PR225.js';
import { PR226 } from '../pr-01/PR226.js';
import { PR227 } from '../pr-01/PR227.js';
import { PR228 } from '../pr-01/PR228.js';
import { PR229 } from '../pr-01/PR229.js';
import { PR248 } from '../pr-01/PR248.js';
import { PR249 } from '../pr-01/PR249.js';
import { PR250 } from '../pr-01/PR250.js';
import { PR251 } from '../pr-01/PR251.js';
import { PR252 } from '../pr-01/PR252.js';
import { PR253 } from '../pr-01/PR253.js';
import { PR254 } from '../pr-01/PR254.js';
import { PR255 } from '../pr-01/PR255.js';
import { PR256 } from '../pr-01/PR256.js';
import { PR257 } from '../pr-01/PR257.js';
import { PR258 } from '../pr-01/PR258.js';
import { PR259 } from '../pr-01/PR259.js';
import { PR260 } from '../pr-01/PR260.js';
import { PR261 } from '../pr-01/PR261.js';

export const GENERATED_PARTNERS: CardDef[] = [
  { ...D01001, standardPartnerActions: true }, { ...D02001, standardPartnerActions: true }, { ...D03001, standardPartnerActions: true }, { ...D04001, standardPartnerActions: true }, { ...D05001, standardPartnerActions: true }, { ...D06001, standardPartnerActions: true }, { ...D06002, standardPartnerActions: true }, { ...D07001, standardPartnerActions: true },
  { ...D09001, standardPartnerActions: true }, { ...D09002, standardPartnerActions: true }, { ...D09003, standardPartnerActions: true }, { ...D10001, standardPartnerActions: true }, { ...D10002, standardPartnerActions: true }, { ...B01001, standardPartnerActions: true }, { ...B01001P, standardPartnerActions: true }, { ...B01001Sec1, standardPartnerActions: true },
  { ...B01001Sec2, standardPartnerActions: true }, { ...B01002, standardPartnerActions: true }, { ...B01002P, standardPartnerActions: true }, { ...B01003, standardPartnerActions: true }, { ...B01003P, standardPartnerActions: true }, { ...B01004, standardPartnerActions: true }, { ...B01004P, standardPartnerActions: true }, { ...B01025, standardPartnerActions: true },
  { ...B01025P, standardPartnerActions: true }, { ...B01026, standardPartnerActions: true }, { ...B01026P, standardPartnerActions: true }, { ...B01042, standardPartnerActions: true }, { ...B01042P, standardPartnerActions: true }, { ...B01043, standardPartnerActions: true }, { ...B01043P, standardPartnerActions: true }, { ...B01060, standardPartnerActions: true },
  { ...B01060P, standardPartnerActions: true }, { ...B01061, standardPartnerActions: true }, { ...B01061P, standardPartnerActions: true }, { ...B01079, standardPartnerActions: true }, { ...B01079P, standardPartnerActions: true }, { ...B01080, standardPartnerActions: true }, { ...B01080P, standardPartnerActions: true }, { ...B02001, standardPartnerActions: true },
  { ...B02001P, standardPartnerActions: true }, { ...B02016, standardPartnerActions: true }, { ...B02016P, standardPartnerActions: true }, { ...B02016Sec1, standardPartnerActions: true }, { ...B02016Sec2, standardPartnerActions: true }, { ...B02017, standardPartnerActions: true }, { ...B02017P, standardPartnerActions: true }, { ...B02035, standardPartnerActions: true },
  { ...B02035P, standardPartnerActions: true }, { ...B02035Sec1, standardPartnerActions: true }, { ...B02035Sec2, standardPartnerActions: true }, { ...B02036, standardPartnerActions: true }, { ...B02036P, standardPartnerActions: true }, { ...B02037, standardPartnerActions: true }, { ...B02037P, standardPartnerActions: true }, { ...B02055, standardPartnerActions: true },
  { ...B02055P, standardPartnerActions: true }, { ...B02056, standardPartnerActions: true }, { ...B02056P, standardPartnerActions: true }, { ...B02070, standardPartnerActions: true }, { ...B02070P, standardPartnerActions: true }, { ...B02071, standardPartnerActions: true }, { ...B02071P, standardPartnerActions: true }, { ...B03001, standardPartnerActions: true },
  { ...B03001P, standardPartnerActions: true }, { ...B03027, standardPartnerActions: true }, { ...B03027P, standardPartnerActions: true }, { ...B03044, standardPartnerActions: true }, { ...B03045, standardPartnerActions: true }, { ...B03065, standardPartnerActions: true }, { ...B03065P, standardPartnerActions: true }, { ...B03083, standardPartnerActions: true },
  { ...B03083P, standardPartnerActions: true }, { ...B03106, standardPartnerActions: true }, { ...B03106P, standardPartnerActions: true }, { ...B03107, standardPartnerActions: true }, { ...B03107P, standardPartnerActions: true }, { ...B03108, standardPartnerActions: true }, { ...B03108P, standardPartnerActions: true }, { ...B03109, standardPartnerActions: true },
  { ...B03139Sec1, standardPartnerActions: true }, { ...B03139Sec2, standardPartnerActions: true }, { ...B03140Sec1, standardPartnerActions: true }, { ...B03140Sec2, standardPartnerActions: true }, { ...B04001, standardPartnerActions: true }, { ...B04001P, standardPartnerActions: true }, { ...B04001Sec1, standardPartnerActions: true }, { ...B04001Sec2, standardPartnerActions: true },
  { ...B04002, standardPartnerActions: true }, { ...B04002P, standardPartnerActions: true }, { ...B04002Sec1, standardPartnerActions: true }, { ...B04002Sec2, standardPartnerActions: true }, { ...B04016, standardPartnerActions: true }, { ...B04016P, standardPartnerActions: true }, { ...B04029, standardPartnerActions: true }, { ...B04029P, standardPartnerActions: true },
  { ...B04043, standardPartnerActions: true }, { ...B04043P, standardPartnerActions: true }, { ...B04044, standardPartnerActions: true }, { ...B04044P, standardPartnerActions: true }, { ...B04045, standardPartnerActions: true }, { ...B04045P, standardPartnerActions: true }, { ...B04065, standardPartnerActions: true }, { ...B04065P, standardPartnerActions: true },
  { ...B04066, standardPartnerActions: true }, { ...B04066P, standardPartnerActions: true }, { ...B04067, standardPartnerActions: true }, { ...B04067P, standardPartnerActions: true }, { ...B04087, standardPartnerActions: true }, { ...B04087P, standardPartnerActions: true }, { ...B05001, standardPartnerActions: true }, { ...B05001P, standardPartnerActions: true },
  { ...B05002, standardPartnerActions: true }, { ...B05002P, standardPartnerActions: true }, { ...B05003, standardPartnerActions: true }, { ...B05003P, standardPartnerActions: true }, { ...B05004, standardPartnerActions: true }, { ...B05004P, standardPartnerActions: true }, { ...B05025, standardPartnerActions: true }, { ...B05025P, standardPartnerActions: true },
  { ...B05026, standardPartnerActions: true }, { ...B05026P, standardPartnerActions: true }, { ...B05043, standardPartnerActions: true }, { ...B05043P, standardPartnerActions: true }, { ...B05044, standardPartnerActions: true }, { ...B05044P, standardPartnerActions: true }, { ...B05064, standardPartnerActions: true }, { ...B05064P, standardPartnerActions: true },
  { ...B05065, standardPartnerActions: true }, { ...B05065P, standardPartnerActions: true }, { ...B05084, standardPartnerActions: true }, { ...B05084P, standardPartnerActions: true }, { ...B05084Sec1, standardPartnerActions: true }, { ...B05084Sec2, standardPartnerActions: true }, { ...B05085, standardPartnerActions: true }, { ...B05085P, standardPartnerActions: true },
  { ...B05085Sec1, standardPartnerActions: true }, { ...B05085Sec2, standardPartnerActions: true }, { ...B05104, standardPartnerActions: true }, { ...B05104P, standardPartnerActions: true }, { ...B05105, standardPartnerActions: true }, { ...B05105P, standardPartnerActions: true }, { ...B06001Sec1, standardPartnerActions: true }, { ...B06001Sec2, standardPartnerActions: true },
  { ...B06002, standardPartnerActions: true }, { ...B06002P, standardPartnerActions: true }, { ...B06014, standardPartnerActions: true }, { ...B06014P, standardPartnerActions: true }, { ...B06015, standardPartnerActions: true }, { ...B06015P, standardPartnerActions: true }, { ...B06044, standardPartnerActions: true }, { ...B06044P, standardPartnerActions: true },
  { ...B06044Sec1, standardPartnerActions: true }, { ...B06044Sec2, standardPartnerActions: true }, { ...B06045, standardPartnerActions: true }, { ...B06045P, standardPartnerActions: true }, { ...B06073, standardPartnerActions: true }, { ...B06073P, standardPartnerActions: true }, { ...B06083, standardPartnerActions: true }, { ...B06083P, standardPartnerActions: true },
  { ...B06096, standardPartnerActions: true }, { ...B06096P, standardPartnerActions: true }, { ...B06097, standardPartnerActions: true }, { ...B06097P, standardPartnerActions: true }, { ...B07027, standardPartnerActions: true }, { ...B07027P, standardPartnerActions: true }, { ...B07027Sec1, standardPartnerActions: true }, { ...B07027Sec2, standardPartnerActions: true },
  { ...B07028, standardPartnerActions: true }, { ...B07028P, standardPartnerActions: true }, { ...B07028Sec1, standardPartnerActions: true }, { ...B07028Sec2, standardPartnerActions: true }, { ...B07029, standardPartnerActions: true }, { ...B07029P, standardPartnerActions: true }, { ...B07078, standardPartnerActions: true }, { ...B07078P, standardPartnerActions: true },
  { ...B07092, standardPartnerActions: true }, { ...B07092P, standardPartnerActions: true }, { ...B08001Sec1, standardPartnerActions: true }, { ...B08001Sec2, standardPartnerActions: true }, { ...B08018, standardPartnerActions: true }, { ...B08018P, standardPartnerActions: true }, { ...B08031, standardPartnerActions: true }, { ...B08031P, standardPartnerActions: true },
  { ...B08045, standardPartnerActions: true }, { ...B08045P, standardPartnerActions: true }, { ...B08061, standardPartnerActions: true }, { ...B08061P, standardPartnerActions: true }, { ...B08077Sec1, standardPartnerActions: true }, { ...B08077Sec2, standardPartnerActions: true }, { ...B09001, standardPartnerActions: true }, { ...B09001P, standardPartnerActions: true },
  { ...B09020, standardPartnerActions: true }, { ...B09020P, standardPartnerActions: true }, { ...B09035, standardPartnerActions: true }, { ...B09035P, standardPartnerActions: true }, { ...B09053, standardPartnerActions: true }, { ...B09053P, standardPartnerActions: true }, { ...B09068, standardPartnerActions: true }, { ...B09068P, standardPartnerActions: true },
  { ...B09068Sec1, standardPartnerActions: true }, { ...B09068Sec2, standardPartnerActions: true }, { ...B09069, standardPartnerActions: true }, { ...B09069P, standardPartnerActions: true }, { ...B09069Sec1, standardPartnerActions: true }, { ...B09069Sec2, standardPartnerActions: true }, { ...B09091, standardPartnerActions: true }, { ...B09091P, standardPartnerActions: true },
  { ...PR001, standardPartnerActions: true }, { ...PR002, standardPartnerActions: true }, { ...PR003, standardPartnerActions: true }, { ...PR004, standardPartnerActions: true }, { ...PR005, standardPartnerActions: true }, { ...PR007, standardPartnerActions: true }, { ...PR008, standardPartnerActions: true }, { ...PR009, standardPartnerActions: true },
  { ...PR010, standardPartnerActions: true }, { ...PR011, standardPartnerActions: true }, { ...PR022, standardPartnerActions: true, partnerAssistFileThreshold: 8 }, { ...PR069, standardPartnerActions: true }, { ...PR070, standardPartnerActions: true }, { ...PR071, standardPartnerActions: true }, { ...PR072, standardPartnerActions: true }, { ...PR074, standardPartnerActions: true },
  { ...PR075, standardPartnerActions: true }, { ...PR076, standardPartnerActions: true }, { ...PR077, standardPartnerActions: true }, { ...PR078, standardPartnerActions: true }, { ...PR079, standardPartnerActions: true }, { ...PR110, standardPartnerActions: true }, { ...PR111, standardPartnerActions: true }, { ...PR112, standardPartnerActions: true },
  { ...PR113, standardPartnerActions: true }, { ...PR119, standardPartnerActions: true }, { ...PR120, standardPartnerActions: true }, { ...PR121, standardPartnerActions: true }, { ...PR122, standardPartnerActions: true }, { ...PR123, standardPartnerActions: true }, { ...PR124, standardPartnerActions: true }, { ...PR125, standardPartnerActions: true },
  { ...PR126, standardPartnerActions: true }, { ...PR127, standardPartnerActions: true }, { ...PR128, standardPartnerActions: true }, { ...PR129, standardPartnerActions: true }, { ...PR130, standardPartnerActions: true }, { ...PR190, standardPartnerActions: true }, { ...PR191, standardPartnerActions: true }, { ...PR214, standardPartnerActions: true },
  { ...PR215, standardPartnerActions: true }, { ...PR216, standardPartnerActions: true }, { ...PR217, standardPartnerActions: true }, { ...PR219, standardPartnerActions: true }, { ...PR220, standardPartnerActions: true }, { ...PR221, standardPartnerActions: true }, { ...PR222, standardPartnerActions: true }, { ...PR223, standardPartnerActions: true },
  { ...PR224, standardPartnerActions: true }, { ...PR225, standardPartnerActions: true }, { ...PR226, standardPartnerActions: true }, { ...PR227, standardPartnerActions: true }, { ...PR228, standardPartnerActions: true }, { ...PR229, standardPartnerActions: true }, { ...PR248, standardPartnerActions: true }, { ...PR249, standardPartnerActions: true },
  { ...PR250, standardPartnerActions: true }, { ...PR251, standardPartnerActions: true }, { ...PR252, standardPartnerActions: true }, { ...PR253, standardPartnerActions: true }, { ...PR254, standardPartnerActions: true }, { ...PR255, standardPartnerActions: true }, { ...PR256, standardPartnerActions: true }, { ...PR257, standardPartnerActions: true },
  { ...PR258, standardPartnerActions: true }, { ...PR259, standardPartnerActions: true }, { ...PR260, standardPartnerActions: true }, { ...PR261, standardPartnerActions: true },
];
