// cards/_generated/partners — auto-generated by scripts/gen-cards/gen-partners.cjs
// 276 件の非MVP partner CardDef (abilities:[] stub) を集約。手で編集しない。
import type { CardDef } from '@/engine/types';

import { D01001 } from '../ct-d01/D01001.js';
import { D02001 } from '../ct-d02/D02001.js';
import { D03001 } from '../ct-d03/D03001.js';
import { D04001 } from '../ct-d04/D04001.js';
import { D05001 } from '../ct-d05/D05001.js';
import { D06001 } from '../ct-d06/D06001.js';
import { D06002 } from '../ct-d06/D06002.js';
import { D07001 } from '../ct-d07/D07001.js';
import { D09001 } from '../ct-d09/D09001.js';
import { D09002 } from '../ct-d09/D09002.js';
import { D09003 } from '../ct-d09/D09003.js';
import { D10001 } from '../ct-d10/D10001.js';
import { D10002 } from '../ct-d10/D10002.js';
import { B01001 } from '../ct-p01/B01001.js';
import { B01001P } from '../ct-p01/B01001P.js';
import { B01001Sec1 } from '../ct-p01/B01001Sec1.js';
import { B01001Sec2 } from '../ct-p01/B01001Sec2.js';
import { B01002 } from '../ct-p01/B01002.js';
import { B01002P } from '../ct-p01/B01002P.js';
import { B01003 } from '../ct-p01/B01003.js';
import { B01003P } from '../ct-p01/B01003P.js';
import { B01004 } from '../ct-p01/B01004.js';
import { B01004P } from '../ct-p01/B01004P.js';
import { B01025 } from '../ct-p01/B01025.js';
import { B01025P } from '../ct-p01/B01025P.js';
import { B01026 } from '../ct-p01/B01026.js';
import { B01026P } from '../ct-p01/B01026P.js';
import { B01042 } from '../ct-p01/B01042.js';
import { B01042P } from '../ct-p01/B01042P.js';
import { B01043 } from '../ct-p01/B01043.js';
import { B01043P } from '../ct-p01/B01043P.js';
import { B01060 } from '../ct-p01/B01060.js';
import { B01060P } from '../ct-p01/B01060P.js';
import { B01061 } from '../ct-p01/B01061.js';
import { B01061P } from '../ct-p01/B01061P.js';
import { B01079 } from '../ct-p01/B01079.js';
import { B01079P } from '../ct-p01/B01079P.js';
import { B01080 } from '../ct-p01/B01080.js';
import { B01080P } from '../ct-p01/B01080P.js';
import { B02001 } from '../ct-p02/B02001.js';
import { B02001P } from '../ct-p02/B02001P.js';
import { B02016 } from '../ct-p02/B02016.js';
import { B02016P } from '../ct-p02/B02016P.js';
import { B02016Sec1 } from '../ct-p02/B02016Sec1.js';
import { B02016Sec2 } from '../ct-p02/B02016Sec2.js';
import { B02017 } from '../ct-p02/B02017.js';
import { B02017P } from '../ct-p02/B02017P.js';
import { B02035 } from '../ct-p02/B02035.js';
import { B02035P } from '../ct-p02/B02035P.js';
import { B02035Sec1 } from '../ct-p02/B02035Sec1.js';
import { B02035Sec2 } from '../ct-p02/B02035Sec2.js';
import { B02036 } from '../ct-p02/B02036.js';
import { B02036P } from '../ct-p02/B02036P.js';
import { B02037 } from '../ct-p02/B02037.js';
import { B02037P } from '../ct-p02/B02037P.js';
import { B02055 } from '../ct-p02/B02055.js';
import { B02055P } from '../ct-p02/B02055P.js';
import { B02056 } from '../ct-p02/B02056.js';
import { B02056P } from '../ct-p02/B02056P.js';
import { B02070 } from '../ct-p02/B02070.js';
import { B02070P } from '../ct-p02/B02070P.js';
import { B02071 } from '../ct-p02/B02071.js';
import { B02071P } from '../ct-p02/B02071P.js';
import { B03001 } from '../ct-p03/B03001.js';
import { B03001P } from '../ct-p03/B03001P.js';
import { B03027 } from '../ct-p03/B03027.js';
import { B03027P } from '../ct-p03/B03027P.js';
import { B03044 } from '../ct-p03/B03044.js';
import { B03045 } from '../ct-p03/B03045.js';
import { B03065 } from '../ct-p03/B03065.js';
import { B03065P } from '../ct-p03/B03065P.js';
import { B03083 } from '../ct-p03/B03083.js';
import { B03083P } from '../ct-p03/B03083P.js';
import { B03106 } from '../ct-p03/B03106.js';
import { B03106P } from '../ct-p03/B03106P.js';
import { B03107 } from '../ct-p03/B03107.js';
import { B03107P } from '../ct-p03/B03107P.js';
import { B03108 } from '../ct-p03/B03108.js';
import { B03108P } from '../ct-p03/B03108P.js';
import { B03109 } from '../ct-p03/B03109.js';
import { B03139Sec1 } from '../ct-p03/B03139Sec1.js';
import { B03139Sec2 } from '../ct-p03/B03139Sec2.js';
import { B03140Sec1 } from '../ct-p03/B03140Sec1.js';
import { B03140Sec2 } from '../ct-p03/B03140Sec2.js';
import { B04001 } from '../ct-p04/B04001.js';
import { B04001P } from '../ct-p04/B04001P.js';
import { B04001Sec1 } from '../ct-p04/B04001Sec1.js';
import { B04001Sec2 } from '../ct-p04/B04001Sec2.js';
import { B04002 } from '../ct-p04/B04002.js';
import { B04002P } from '../ct-p04/B04002P.js';
import { B04002Sec1 } from '../ct-p04/B04002Sec1.js';
import { B04002Sec2 } from '../ct-p04/B04002Sec2.js';
import { B04016 } from '../ct-p04/B04016.js';
import { B04016P } from '../ct-p04/B04016P.js';
import { B04029 } from '../ct-p04/B04029.js';
import { B04029P } from '../ct-p04/B04029P.js';
import { B04043 } from '../ct-p04/B04043.js';
import { B04043P } from '../ct-p04/B04043P.js';
import { B04044 } from '../ct-p04/B04044.js';
import { B04044P } from '../ct-p04/B04044P.js';
import { B04045 } from '../ct-p04/B04045.js';
import { B04045P } from '../ct-p04/B04045P.js';
import { B04065 } from '../ct-p04/B04065.js';
import { B04065P } from '../ct-p04/B04065P.js';
import { B04066 } from '../ct-p04/B04066.js';
import { B04066P } from '../ct-p04/B04066P.js';
import { B04067 } from '../ct-p04/B04067.js';
import { B04067P } from '../ct-p04/B04067P.js';
import { B04087 } from '../ct-p04/B04087.js';
import { B04087P } from '../ct-p04/B04087P.js';
import { B05001 } from '../ct-p05/B05001.js';
import { B05001P } from '../ct-p05/B05001P.js';
import { B05002 } from '../ct-p05/B05002.js';
import { B05002P } from '../ct-p05/B05002P.js';
import { B05003 } from '../ct-p05/B05003.js';
import { B05003P } from '../ct-p05/B05003P.js';
import { B05004 } from '../ct-p05/B05004.js';
import { B05004P } from '../ct-p05/B05004P.js';
import { B05025 } from '../ct-p05/B05025.js';
import { B05025P } from '../ct-p05/B05025P.js';
import { B05026 } from '../ct-p05/B05026.js';
import { B05026P } from '../ct-p05/B05026P.js';
import { B05043 } from '../ct-p05/B05043.js';
import { B05043P } from '../ct-p05/B05043P.js';
import { B05044 } from '../ct-p05/B05044.js';
import { B05044P } from '../ct-p05/B05044P.js';
import { B05064 } from '../ct-p05/B05064.js';
import { B05064P } from '../ct-p05/B05064P.js';
import { B05065 } from '../ct-p05/B05065.js';
import { B05065P } from '../ct-p05/B05065P.js';
import { B05084 } from '../ct-p05/B05084.js';
import { B05084P } from '../ct-p05/B05084P.js';
import { B05084Sec1 } from '../ct-p05/B05084Sec1.js';
import { B05084Sec2 } from '../ct-p05/B05084Sec2.js';
import { B05085 } from '../ct-p05/B05085.js';
import { B05085P } from '../ct-p05/B05085P.js';
import { B05085Sec1 } from '../ct-p05/B05085Sec1.js';
import { B05085Sec2 } from '../ct-p05/B05085Sec2.js';
import { B05104 } from '../ct-p05/B05104.js';
import { B05104P } from '../ct-p05/B05104P.js';
import { B05105 } from '../ct-p05/B05105.js';
import { B05105P } from '../ct-p05/B05105P.js';
import { B06001Sec1 } from '../ct-p06/B06001Sec1.js';
import { B06001Sec2 } from '../ct-p06/B06001Sec2.js';
import { B06002 } from '../ct-p06/B06002.js';
import { B06002P } from '../ct-p06/B06002P.js';
import { B06014 } from '../ct-p06/B06014.js';
import { B06014P } from '../ct-p06/B06014P.js';
import { B06015 } from '../ct-p06/B06015.js';
import { B06015P } from '../ct-p06/B06015P.js';
import { B06044 } from '../ct-p06/B06044.js';
import { B06044P } from '../ct-p06/B06044P.js';
import { B06044Sec1 } from '../ct-p06/B06044Sec1.js';
import { B06044Sec2 } from '../ct-p06/B06044Sec2.js';
import { B06045 } from '../ct-p06/B06045.js';
import { B06045P } from '../ct-p06/B06045P.js';
import { B06073 } from '../ct-p06/B06073.js';
import { B06073P } from '../ct-p06/B06073P.js';
import { B06083 } from '../ct-p06/B06083.js';
import { B06083P } from '../ct-p06/B06083P.js';
import { B06096 } from '../ct-p06/B06096.js';
import { B06096P } from '../ct-p06/B06096P.js';
import { B06097 } from '../ct-p06/B06097.js';
import { B06097P } from '../ct-p06/B06097P.js';
import { B07027 } from '../ct-p07/B07027.js';
import { B07027P } from '../ct-p07/B07027P.js';
import { B07027Sec1 } from '../ct-p07/B07027Sec1.js';
import { B07027Sec2 } from '../ct-p07/B07027Sec2.js';
import { B07028 } from '../ct-p07/B07028.js';
import { B07028P } from '../ct-p07/B07028P.js';
import { B07028Sec1 } from '../ct-p07/B07028Sec1.js';
import { B07028Sec2 } from '../ct-p07/B07028Sec2.js';
import { B07029 } from '../ct-p07/B07029.js';
import { B07029P } from '../ct-p07/B07029P.js';
import { B07078 } from '../ct-p07/B07078.js';
import { B07078P } from '../ct-p07/B07078P.js';
import { B07092 } from '../ct-p07/B07092.js';
import { B07092P } from '../ct-p07/B07092P.js';
import { B08001Sec1 } from '../ct-p08/B08001Sec1.js';
import { B08001Sec2 } from '../ct-p08/B08001Sec2.js';
import { B08018 } from '../ct-p08/B08018.js';
import { B08018P } from '../ct-p08/B08018P.js';
import { B08031 } from '../ct-p08/B08031.js';
import { B08031P } from '../ct-p08/B08031P.js';
import { B08045 } from '../ct-p08/B08045.js';
import { B08045P } from '../ct-p08/B08045P.js';
import { B08061 } from '../ct-p08/B08061.js';
import { B08061P } from '../ct-p08/B08061P.js';
import { B08077Sec1 } from '../ct-p08/B08077Sec1.js';
import { B08077Sec2 } from '../ct-p08/B08077Sec2.js';
import { B09001 } from '../ct-p09/B09001.js';
import { B09001P } from '../ct-p09/B09001P.js';
import { B09020 } from '../ct-p09/B09020.js';
import { B09020P } from '../ct-p09/B09020P.js';
import { B09035 } from '../ct-p09/B09035.js';
import { B09035P } from '../ct-p09/B09035P.js';
import { B09053 } from '../ct-p09/B09053.js';
import { B09053P } from '../ct-p09/B09053P.js';
import { B09068 } from '../ct-p09/B09068.js';
import { B09068P } from '../ct-p09/B09068P.js';
import { B09068Sec1 } from '../ct-p09/B09068Sec1.js';
import { B09068Sec2 } from '../ct-p09/B09068Sec2.js';
import { B09069 } from '../ct-p09/B09069.js';
import { B09069P } from '../ct-p09/B09069P.js';
import { B09069Sec1 } from '../ct-p09/B09069Sec1.js';
import { B09069Sec2 } from '../ct-p09/B09069Sec2.js';
import { B09091 } from '../ct-p09/B09091.js';
import { B09091P } from '../ct-p09/B09091P.js';
import { PR001 } from '../pr-01/PR001.js';
import { PR002 } from '../pr-01/PR002.js';
import { PR003 } from '../pr-01/PR003.js';
import { PR004 } from '../pr-01/PR004.js';
import { PR005 } from '../pr-01/PR005.js';
import { PR007 } from '../pr-01/PR007.js';
import { PR008 } from '../pr-01/PR008.js';
import { PR009 } from '../pr-01/PR009.js';
import { PR010 } from '../pr-01/PR010.js';
import { PR011 } from '../pr-01/PR011.js';
import { PR022 } from '../pr-01/PR022.js';
import { PR069 } from '../pr-01/PR069.js';
import { PR070 } from '../pr-01/PR070.js';
import { PR071 } from '../pr-01/PR071.js';
import { PR072 } from '../pr-01/PR072.js';
import { PR074 } from '../pr-01/PR074.js';
import { PR075 } from '../pr-01/PR075.js';
import { PR076 } from '../pr-01/PR076.js';
import { PR077 } from '../pr-01/PR077.js';
import { PR078 } from '../pr-01/PR078.js';
import { PR079 } from '../pr-01/PR079.js';
import { PR110 } from '../pr-01/PR110.js';
import { PR111 } from '../pr-01/PR111.js';
import { PR112 } from '../pr-01/PR112.js';
import { PR113 } from '../pr-01/PR113.js';
import { PR119 } from '../pr-01/PR119.js';
import { PR120 } from '../pr-01/PR120.js';
import { PR121 } from '../pr-01/PR121.js';
import { PR122 } from '../pr-01/PR122.js';
import { PR123 } from '../pr-01/PR123.js';
import { PR124 } from '../pr-01/PR124.js';
import { PR125 } from '../pr-01/PR125.js';
import { PR126 } from '../pr-01/PR126.js';
import { PR127 } from '../pr-01/PR127.js';
import { PR128 } from '../pr-01/PR128.js';
import { PR129 } from '../pr-01/PR129.js';
import { PR130 } from '../pr-01/PR130.js';
import { PR190 } from '../pr-01/PR190.js';
import { PR191 } from '../pr-01/PR191.js';
import { PR214 } from '../pr-01/PR214.js';
import { PR215 } from '../pr-01/PR215.js';
import { PR216 } from '../pr-01/PR216.js';
import { PR217 } from '../pr-01/PR217.js';
import { PR219 } from '../pr-01/PR219.js';
import { PR220 } from '../pr-01/PR220.js';
import { PR221 } from '../pr-01/PR221.js';
import { PR222 } from '../pr-01/PR222.js';
import { PR223 } from '../pr-01/PR223.js';
import { PR224 } from '../pr-01/PR224.js';
import { PR225 } from '../pr-01/PR225.js';
import { PR226 } from '../pr-01/PR226.js';
import { PR227 } from '../pr-01/PR227.js';
import { PR228 } from '../pr-01/PR228.js';
import { PR229 } from '../pr-01/PR229.js';
import { PR248 } from '../pr-01/PR248.js';
import { PR249 } from '../pr-01/PR249.js';
import { PR250 } from '../pr-01/PR250.js';
import { PR251 } from '../pr-01/PR251.js';
import { PR252 } from '../pr-01/PR252.js';
import { PR253 } from '../pr-01/PR253.js';
import { PR254 } from '../pr-01/PR254.js';
import { PR255 } from '../pr-01/PR255.js';
import { PR256 } from '../pr-01/PR256.js';
import { PR257 } from '../pr-01/PR257.js';
import { PR258 } from '../pr-01/PR258.js';
import { PR259 } from '../pr-01/PR259.js';
import { PR260 } from '../pr-01/PR260.js';
import { PR261 } from '../pr-01/PR261.js';

export const GENERATED_PARTNERS: CardDef[] = [
  D01001, D02001, D03001, D04001, D05001, D06001, D06002, D07001,
  D09001, D09002, D09003, D10001, D10002, B01001, B01001P, B01001Sec1,
  B01001Sec2, B01002, B01002P, B01003, B01003P, B01004, B01004P, B01025,
  B01025P, B01026, B01026P, B01042, B01042P, B01043, B01043P, B01060,
  B01060P, B01061, B01061P, B01079, B01079P, B01080, B01080P, B02001,
  B02001P, B02016, B02016P, B02016Sec1, B02016Sec2, B02017, B02017P, B02035,
  B02035P, B02035Sec1, B02035Sec2, B02036, B02036P, B02037, B02037P, B02055,
  B02055P, B02056, B02056P, B02070, B02070P, B02071, B02071P, B03001,
  B03001P, B03027, B03027P, B03044, B03045, B03065, B03065P, B03083,
  B03083P, B03106, B03106P, B03107, B03107P, B03108, B03108P, B03109,
  B03139Sec1, B03139Sec2, B03140Sec1, B03140Sec2, B04001, B04001P, B04001Sec1, B04001Sec2,
  B04002, B04002P, B04002Sec1, B04002Sec2, B04016, B04016P, B04029, B04029P,
  B04043, B04043P, B04044, B04044P, B04045, B04045P, B04065, B04065P,
  B04066, B04066P, B04067, B04067P, B04087, B04087P, B05001, B05001P,
  B05002, B05002P, B05003, B05003P, B05004, B05004P, B05025, B05025P,
  B05026, B05026P, B05043, B05043P, B05044, B05044P, B05064, B05064P,
  B05065, B05065P, B05084, B05084P, B05084Sec1, B05084Sec2, B05085, B05085P,
  B05085Sec1, B05085Sec2, B05104, B05104P, B05105, B05105P, B06001Sec1, B06001Sec2,
  B06002, B06002P, B06014, B06014P, B06015, B06015P, B06044, B06044P,
  B06044Sec1, B06044Sec2, B06045, B06045P, B06073, B06073P, B06083, B06083P,
  B06096, B06096P, B06097, B06097P, B07027, B07027P, B07027Sec1, B07027Sec2,
  B07028, B07028P, B07028Sec1, B07028Sec2, B07029, B07029P, B07078, B07078P,
  B07092, B07092P, B08001Sec1, B08001Sec2, B08018, B08018P, B08031, B08031P,
  B08045, B08045P, B08061, B08061P, B08077Sec1, B08077Sec2, B09001, B09001P,
  B09020, B09020P, B09035, B09035P, B09053, B09053P, B09068, B09068P,
  B09068Sec1, B09068Sec2, B09069, B09069P, B09069Sec1, B09069Sec2, B09091, B09091P,
  PR001, PR002, PR003, PR004, PR005, PR007, PR008, PR009,
  PR010, PR011, PR022, PR069, PR070, PR071, PR072, PR074,
  PR075, PR076, PR077, PR078, PR079, PR110, PR111, PR112,
  PR113, PR119, PR120, PR121, PR122, PR123, PR124, PR125,
  PR126, PR127, PR128, PR129, PR130, PR190, PR191, PR214,
  PR215, PR216, PR217, PR219, PR220, PR221, PR222, PR223,
  PR224, PR225, PR226, PR227, PR228, PR229, PR248, PR249,
  PR250, PR251, PR252, PR253, PR254, PR255, PR256, PR257,
  PR258, PR259, PR260, PR261,
];
