// cards/_generated/simple-cards — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// 213 件の単純カード (simple cut-in / keyword-only / case no-ability) を集約。手で編集しない。
import type { CardDef } from '@/engine/types';

import { D01002 } from '../ct-d01/D01002.js';
import { D01005 } from '../ct-d01/D01005.js';
import { D01007 } from '../ct-d01/D01007.js';
import { D01009 } from '../ct-d01/D01009.js';
import { D01011 } from '../ct-d01/D01011.js';
import { D01016 } from '../ct-d01/D01016.js';
import { D02003 } from '../ct-d02/D02003.js';
import { D02006 } from '../ct-d02/D02006.js';
import { D02007 } from '../ct-d02/D02007.js';
import { D02010 } from '../ct-d02/D02010.js';
import { D02012 } from '../ct-d02/D02012.js';
import { D02016 } from '../ct-d02/D02016.js';
import { D03003 } from '../ct-d03/D03003.js';
import { D03005 } from '../ct-d03/D03005.js';
import { D03006 } from '../ct-d03/D03006.js';
import { D03008 } from '../ct-d03/D03008.js';
import { D03012 } from '../ct-d03/D03012.js';
import { D03016 } from '../ct-d03/D03016.js';
import { D04003 } from '../ct-d04/D04003.js';
import { D04006 } from '../ct-d04/D04006.js';
import { D04009 } from '../ct-d04/D04009.js';
import { D04012 } from '../ct-d04/D04012.js';
import { D04013 } from '../ct-d04/D04013.js';
import { D04016 } from '../ct-d04/D04016.js';
import { D05003 } from '../ct-d05/D05003.js';
import { D05008 } from '../ct-d05/D05008.js';
import { D05009 } from '../ct-d05/D05009.js';
import { D05010 } from '../ct-d05/D05010.js';
import { D05013 } from '../ct-d05/D05013.js';
import { D05016 } from '../ct-d05/D05016.js';
import { D06007 } from '../ct-d06/D06007.js';
import { D06008 } from '../ct-d06/D06008.js';
import { D06014 } from '../ct-d06/D06014.js';
import { D07002 } from '../ct-d07/D07002.js';
import { D07003 } from '../ct-d07/D07003.js';
import { D07006 } from '../ct-d07/D07006.js';
import { D07007 } from '../ct-d07/D07007.js';
import { D07012 } from '../ct-d07/D07012.js';
import { D07013 } from '../ct-d07/D07013.js';
import { D07020 } from '../ct-d07/D07020.js';
import { D07021 } from '../ct-d07/D07021.js';
import { D09012 } from '../ct-d09/D09012.js';
import { D09013 } from '../ct-d09/D09013.js';
import { D09018 } from '../ct-d09/D09018.js';
import { D09019 } from '../ct-d09/D09019.js';
import { D09021 } from '../ct-d09/D09021.js';
import { D09024 } from '../ct-d09/D09024.js';
import { D10015 } from '../ct-d10/D10015.js';
import { D10016 } from '../ct-d10/D10016.js';
import { D10017 } from '../ct-d10/D10017.js';
import { D10018 } from '../ct-d10/D10018.js';
import { D10019 } from '../ct-d10/D10019.js';
import { B01019 } from '../ct-p01/B01019.js';
import { B01019P } from '../ct-p01/B01019P.js';
import { B01024 } from '../ct-p01/B01024.js';
import { B01024P } from '../ct-p01/B01024P.js';
import { B01033 } from '../ct-p01/B01033.js';
import { B01033P } from '../ct-p01/B01033P.js';
import { B01041 } from '../ct-p01/B01041.js';
import { B01041P } from '../ct-p01/B01041P.js';
import { B01056 } from '../ct-p01/B01056.js';
import { B01059 } from '../ct-p01/B01059.js';
import { B01059P } from '../ct-p01/B01059P.js';
import { B01073 } from '../ct-p01/B01073.js';
import { B01073P } from '../ct-p01/B01073P.js';
import { B01078 } from '../ct-p01/B01078.js';
import { B01078P } from '../ct-p01/B01078P.js';
import { B01086 } from '../ct-p01/B01086.js';
import { B01086P } from '../ct-p01/B01086P.js';
import { B01096 } from '../ct-p01/B01096.js';
import { B01096P } from '../ct-p01/B01096P.js';
import { B02007 } from '../ct-p02/B02007.js';
import { B02011 } from '../ct-p02/B02011.js';
import { B02011P } from '../ct-p02/B02011P.js';
import { B02015 } from '../ct-p02/B02015.js';
import { B02015P } from '../ct-p02/B02015P.js';
import { B02024 } from '../ct-p02/B02024.js';
import { B02024P } from '../ct-p02/B02024P.js';
import { B02027 } from '../ct-p02/B02027.js';
import { B02028 } from '../ct-p02/B02028.js';
import { B02029 } from '../ct-p02/B02029.js';
import { B02029P } from '../ct-p02/B02029P.js';
import { B02034 } from '../ct-p02/B02034.js';
import { B02034P } from '../ct-p02/B02034P.js';
import { B02042 } from '../ct-p02/B02042.js';
import { B02042P } from '../ct-p02/B02042P.js';
import { B02048 } from '../ct-p02/B02048.js';
import { B02048P } from '../ct-p02/B02048P.js';
import { B02054 } from '../ct-p02/B02054.js';
import { B02054P } from '../ct-p02/B02054P.js';
import { B02059 } from '../ct-p02/B02059.js';
import { B02059P } from '../ct-p02/B02059P.js';
import { B02064 } from '../ct-p02/B02064.js';
import { B02064P } from '../ct-p02/B02064P.js';
import { B02065 } from '../ct-p02/B02065.js';
import { B02069 } from '../ct-p02/B02069.js';
import { B02069P } from '../ct-p02/B02069P.js';
import { B02078 } from '../ct-p02/B02078.js';
import { B02078P } from '../ct-p02/B02078P.js';
import { B02081 } from '../ct-p02/B02081.js';
import { B02085 } from '../ct-p02/B02085.js';
import { B02085P } from '../ct-p02/B02085P.js';
import { B03071 } from '../ct-p03/B03071.js';
import { B03071P } from '../ct-p03/B03071P.js';
import { B03072 } from '../ct-p03/B03072.js';
import { B03090 } from '../ct-p03/B03090.js';
import { B03090P } from '../ct-p03/B03090P.js';
import { B03117 } from '../ct-p03/B03117.js';
import { B03119 } from '../ct-p03/B03119.js';
import { B03121 } from '../ct-p03/B03121.js';
import { B03123 } from '../ct-p03/B03123.js';
import { B03123P } from '../ct-p03/B03123P.js';
import { B04006 } from '../ct-p04/B04006.js';
import { B04006P } from '../ct-p04/B04006P.js';
import { B04021 } from '../ct-p04/B04021.js';
import { B04033 } from '../ct-p04/B04033.js';
import { B04053 } from '../ct-p04/B04053.js';
import { B04057 } from '../ct-p04/B04057.js';
import { B04076 } from '../ct-p04/B04076.js';
import { B04076P } from '../ct-p04/B04076P.js';
import { B04078 } from '../ct-p04/B04078.js';
import { B04095 } from '../ct-p04/B04095.js';
import { B05053 } from '../ct-p05/B05053.js';
import { B05054 } from '../ct-p05/B05054.js';
import { B05100 } from '../ct-p05/B05100.js';
import { B05113 } from '../ct-p05/B05113.js';
import { B05113P } from '../ct-p05/B05113P.js';
import { B06022 } from '../ct-p06/B06022.js';
import { B06024 } from '../ct-p06/B06024.js';
import { B06054 } from '../ct-p06/B06054.js';
import { B06055 } from '../ct-p06/B06055.js';
import { B06059 } from '../ct-p06/B06059.js';
import { B06061 } from '../ct-p06/B06061.js';
import { B06089 } from '../ct-p06/B06089.js';
import { B06089P } from '../ct-p06/B06089P.js';
import { B07006 } from '../ct-p07/B07006.js';
import { B08013 } from '../ct-p08/B08013.js';
import { B08053 } from '../ct-p08/B08053.js';
import { B09012 } from '../ct-p09/B09012.js';
import { B09012P } from '../ct-p09/B09012P.js';
import { B09030 } from '../ct-p09/B09030.js';
import { B09030P } from '../ct-p09/B09030P.js';
import { B09043 } from '../ct-p09/B09043.js';
import { B09043P } from '../ct-p09/B09043P.js';
import { B09045 } from '../ct-p09/B09045.js';
import { B09059 } from '../ct-p09/B09059.js';
import { B09059P } from '../ct-p09/B09059P.js';
import { B09077 } from '../ct-p09/B09077.js';
import { B09077P } from '../ct-p09/B09077P.js';
import { B09087 } from '../ct-p09/B09087.js';
import { B09087P } from '../ct-p09/B09087P.js';
import { B09098 } from '../ct-p09/B09098.js';
import { B09098P } from '../ct-p09/B09098P.js';
import { PR024 } from '../pr-01/PR024.js';
import { PR025 } from '../pr-01/PR025.js';
import { PR034 } from '../pr-01/PR034.js';
import { PR037 } from '../pr-01/PR037.js';
import { PR038 } from '../pr-01/PR038.js';
import { PR040 } from '../pr-01/PR040.js';
import { PR044 } from '../pr-01/PR044.js';
import { PR048 } from '../pr-01/PR048.js';
import { PR052 } from '../pr-01/PR052.js';
import { PR058 } from '../pr-01/PR058.js';
import { PR068 } from '../pr-01/PR068.js';
import { PR073 } from '../pr-01/PR073.js';
import { PR081 } from '../pr-01/PR081.js';
import { PR082 } from '../pr-01/PR082.js';
import { PR083 } from '../pr-01/PR083.js';
import { PR088 } from '../pr-01/PR088.js';
import { PR089 } from '../pr-01/PR089.js';
import { PR095 } from '../pr-01/PR095.js';
import { PR097 } from '../pr-01/PR097.js';
import { PR102 } from '../pr-01/PR102.js';
import { PR108 } from '../pr-01/PR108.js';
import { PR114 } from '../pr-01/PR114.js';
import { PR115 } from '../pr-01/PR115.js';
import { PR116 } from '../pr-01/PR116.js';
import { PR134 } from '../pr-01/PR134.js';
import { PR139 } from '../pr-01/PR139.js';
import { PR140 } from '../pr-01/PR140.js';
import { PR145 } from '../pr-01/PR145.js';
import { PR146 } from '../pr-01/PR146.js';
import { PR153 } from '../pr-01/PR153.js';
import { PR159 } from '../pr-01/PR159.js';
import { PR160 } from '../pr-01/PR160.js';
import { PR165 } from '../pr-01/PR165.js';
import { PR166 } from '../pr-01/PR166.js';
import { PR167 } from '../pr-01/PR167.js';
import { PR168 } from '../pr-01/PR168.js';
import { PR171 } from '../pr-01/PR171.js';
import { PR172 } from '../pr-01/PR172.js';
import { PR176 } from '../pr-01/PR176.js';
import { PR182 } from '../pr-01/PR182.js';
import { PR183 } from '../pr-01/PR183.js';
import { PR188 } from '../pr-01/PR188.js';
import { PR189 } from '../pr-01/PR189.js';
import { PR203 } from '../pr-01/PR203.js';
import { PR204 } from '../pr-01/PR204.js';
import { PR209 } from '../pr-01/PR209.js';
import { PR210 } from '../pr-01/PR210.js';
import { PR211 } from '../pr-01/PR211.js';
import { PR212 } from '../pr-01/PR212.js';
import { PR218 } from '../pr-01/PR218.js';
import { PR232 } from '../pr-01/PR232.js';
import { PR233 } from '../pr-01/PR233.js';
import { PR238 } from '../pr-01/PR238.js';
import { PR244 } from '../pr-01/PR244.js';
import { PR246 } from '../pr-01/PR246.js';
import { PR247 } from '../pr-01/PR247.js';
import { PR266 } from '../pr-01/PR266.js';
import { PR267 } from '../pr-01/PR267.js';
import { PR272 } from '../pr-01/PR272.js';
import { PR273 } from '../pr-01/PR273.js';

export const GENERATED_SIMPLE_CARDS: CardDef[] = [
  D01002, D01005, D01007, D01009, D01011, D01016, D02003, D02006,
  D02007, D02010, D02012, D02016, D03003, D03005, D03006, D03008,
  D03012, D03016, D04003, D04006, D04009, D04012, D04013, D04016,
  D05003, D05008, D05009, D05010, D05013, D05016, D06007, D06008,
  D06014, D07002, D07003, D07006, D07007, D07012, D07013, D07020,
  D07021, D09012, D09013, D09018, D09019, D09021, D09024, D10015,
  D10016, D10017, D10018, D10019, B01019, B01019P, B01024, B01024P,
  B01033, B01033P, B01041, B01041P, B01056, B01059, B01059P, B01073,
  B01073P, B01078, B01078P, B01086, B01086P, B01096, B01096P, B02007,
  B02011, B02011P, B02015, B02015P, B02024, B02024P, B02027, B02028,
  B02029, B02029P, B02034, B02034P, B02042, B02042P, B02048, B02048P,
  B02054, B02054P, B02059, B02059P, B02064, B02064P, B02065, B02069,
  B02069P, B02078, B02078P, B02081, B02085, B02085P, B03071, B03071P,
  B03072, B03090, B03090P, B03117, B03119, B03121, B03123, B03123P,
  B04006, B04006P, B04021, B04033, B04053, B04057, B04076, B04076P,
  B04078, B04095, B05053, B05054, B05100, B05113, B05113P, B06022,
  B06024, B06054, B06055, B06059, B06061, B06089, B06089P, B07006,
  B08013, B08053, B09012, B09012P, B09030, B09030P, B09043, B09043P,
  B09045, B09059, B09059P, B09077, B09077P, B09087, B09087P, B09098,
  B09098P, PR024, PR025, PR034, PR037, PR038, PR040, PR044,
  PR048, PR052, PR058, PR068, PR073, PR081, PR082, PR083,
  PR088, PR089, PR095, PR097, PR102, PR108, PR114, PR115,
  PR116, PR134, PR139, PR140, PR145, PR146, PR153, PR159,
  PR160, PR165, PR166, PR167, PR168, PR171, PR172, PR176,
  PR182, PR183, PR188, PR189, PR203, PR204, PR209, PR210,
  PR211, PR212, PR218, PR232, PR233, PR238, PR244, PR246,
  PR247, PR266, PR267, PR272, PR273,
];
