// cards/pr-01/PR005 江戸川コナン＆工藤新一 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR005: CardDef = {
  id: 'PR005',
  no: 'P014/PR005',
  kind: 'partner',
  names: ['江戸川コナン＆工藤新一', '江戸川コナン', '工藤新一'], // rules/19 複数名カード (BUG-185 一括分割 2026-07-10)
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1714013177232657.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
