// cards/pr-01/PR003 服部平次＆怪盗キッド (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR003: CardDef = {
  id: 'PR003',
  no: 'P002/PR003',
  kind: 'partner',
  names: ['服部平次＆怪盗キッド', '服部平次', '怪盗キッド'], // rules/19 複数名カード (BUG-185 一括分割 2026-07-10)
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1714013177227349.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
