// cards/pr-01/PR003 服部平次＆怪盗キッド (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const PR003: CardDef = {
  id: 'PR003',
  no: 'P002/PR003',
  kind: 'partner',
  names: ['服部平次＆怪盗キッド'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1714013177227349.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
