// cards/pr-01/PR011 安室透 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR011: CardDef = {
  id: 'PR011',
  no: 'P006/PR011',
  kind: 'partner',
  names: ['安室透'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1714013177249236.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
