// cards/pr-01/PR037 平成のホームズ (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const PR037: CardDef = {
  id: 'PR037',
  no: '0258/PR037',
  kind: 'case',
  names: ['平成のホームズ'],
  colors: ['青'],
  traits: [],
  rarity: 'PR',
  imageUrl: '1917d986bfa1d0.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
