// cards/pr-01/PR079 ジン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR079: CardDef = {
  id: 'PR079',
  no: 'P028/PR079',
  kind: 'partner',
  names: ['ジン'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1753702551234465.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
