// cards/pr-01/PR073 「またまたわたしの勝ちね！」 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const PR073: CardDef = {
  id: 'PR073',
  no: '0479/PR073',
  kind: 'case',
  names: ['「またまたわたしの勝ちね！」'],
  colors: ['青'],
  traits: [],
  rarity: 'PR',
  imageUrl: '1753702551194984.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
