// cards/pr-01/PR087 バーボン (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 15-abilities-effects.md, 17-icons.md, 22-qa-action-contact.md
//
// 公式テキスト(カットイン): 【カットイン】【解決編】カードを1枚引く。【黒】のキャラに【カットイン】する場合、AP＋1000（コンタクト中に手札からリムーブして使う）

import type { AbilityDef, CardDef } from '@/engine/types';
import { contactTargetMatches } from '../_shared/index.js';

const a1: AbilityDef = {
  id: 'a1',
  type: 'triggered',
  scope: 'on-hand',
  trigger: { hook: 'effect:declared', optional: true, selfOnly: true }, // 【カットイン】(コンタクト中に手札から使用)
  condition: { kind: 'caseStatus', status: '解決編' }, // 【解決編】(leading icon = 能力全体ゲート, rules/17)
  effect: {
    kind: 'sequence',
    steps: [
      // カードを1枚引く
      { kind: 'atom', verb: 'draw', args: { player: 'self', n: 1 } },
      // 【黒】のキャラに【カットイン】する場合、AP＋1000
      { kind: 'conditional', if: contactTargetMatches({ colors: ['黒'] }), then: { kind: 'atom', verb: 'charModifyAP', args: { uid: '$contact.byUid', delta: 1000, scope: 'contact' } } },
    ],
  },
  description: '【カットイン】【解決編】カードを1枚引く。黒キャラにカットインする場合AP＋1000。',
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};

export const PR087: CardDef = {
  id: 'PR087',
  no: '0483/PR087',
  kind: 'character',
  names: ['バーボン'],
  colors: ['黒'],
  level: 6,
  ap: 6000,
  lp: 1,
  traits: ['黒ずくめの組織'],
  keywords: [],
  rarity: 'PR',
  imageUrl: '1737462993162503.jpg',
  abilities: [a1],
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
