// cards/pr-01/PR110 江戸川コナン＆毛利蘭＆毛利小五郎 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const PR110: CardDef = {
  id: 'PR110',
  no: 'P045/PR110',
  kind: 'partner',
  names: ['江戸川コナン＆毛利蘭＆毛利小五郎'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1743742688663362.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
