// cards/pr-01/PR113 大和敢助＆諸伏高明＆上原由衣 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR113: CardDef = {
  id: 'PR113',
  no: 'P046/PR113',
  kind: 'partner',
  names: ['大和敢助＆諸伏高明＆上原由衣', '大和敢助', '諸伏高明', '上原由衣'], // rules/19 複数名カード (BUG-185 一括分割 2026-07-10)
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1743742688680560.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
