// cards/pr-01/PR127 安室透 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const PR127: CardDef = {
  id: 'PR127',
  no: 'P006/PR127',
  kind: 'partner',
  names: ['安室透'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1747874027808422.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
