// cards/pr-01/PR122 毛利小五郎 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR122: CardDef = {
  id: 'PR122',
  no: 'P009/PR122',
  kind: 'partner',
  names: ['毛利小五郎'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1747874027775961.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
