// cards/pr-01/PR123 灰原哀 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR123: CardDef = {
  id: 'PR123',
  no: 'P008/PR123',
  kind: 'partner',
  names: ['灰原哀'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1747874027782568.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
