// cards/pr-01/PR125 怪盗キッド (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR125: CardDef = {
  id: 'PR125',
  no: 'P004/PR125',
  kind: 'partner',
  names: ['怪盗キッド'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1747874027795564.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
