// cards/pr-01/PR129 諸伏高明 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR129: CardDef = {
  id: 'PR129',
  no: 'P043/PR129',
  kind: 'partner',
  names: ['諸伏高明'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1747874027823556.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
