// cards/pr-01/PR130 上原由衣 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR130: CardDef = {
  id: 'PR130',
  no: 'P044/PR130',
  kind: 'partner',
  names: ['上原由衣'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1747874027830956.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
