// cards/pr-01/PR190 毛利蘭 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const PR190: CardDef = {
  id: 'PR190',
  no: 'P031/PR190',
  kind: 'partner',
  names: ['毛利蘭'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1761913346576814.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
