// cards/pr-01/PR191 小泉紅子 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR191: CardDef = {
  id: 'PR191',
  no: 'P067/PR191',
  kind: 'partner',
  names: ['小泉紅子'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1761913346584461.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
