// cards/pr-01/PR219 毛利蘭 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR219: CardDef = {
  id: 'PR219',
  no: 'P031/PR219',
  kind: 'partner',
  names: ['毛利蘭'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1769159336007836.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
