// cards/pr-01/PR218 「この勝負、もろたで工藤!!!」 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const PR218: CardDef = {
  id: 'PR218',
  no: '0837/PR218',
  kind: 'case',
  names: ['「この勝負、もろたで工藤!!!」'],
  colors: ['緑'],
  traits: [],
  rarity: 'PR',
  imageUrl: '1769159336001063.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
