// cards/pr-01/PR223 佐藤美和子 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR223: CardDef = {
  id: 'PR223',
  no: 'P021/PR223',
  kind: 'partner',
  names: ['佐藤美和子'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1769159336031230.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
