// cards/pr-01/PR221 鈴木園子 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR221: CardDef = {
  id: 'PR221',
  no: 'P033/PR221',
  kind: 'partner',
  names: ['鈴木園子'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1769159336019686.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
