// cards/pr-01/PR226 服部平次 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR226: CardDef = {
  id: 'PR226',
  no: 'P003/PR226',
  kind: 'partner',
  names: ['服部平次'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1769159336048094.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
