// cards/pr-01/PR224 ベルモット (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR224: CardDef = {
  id: 'PR224',
  no: 'P029/PR224',
  kind: 'partner',
  names: ['ベルモット'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1769159336037352.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
