// cards/pr-01/PR227 怪盗キッド (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR227: CardDef = {
  id: 'PR227',
  no: 'P004/PR227',
  kind: 'partner',
  names: ['怪盗キッド'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1769159336054768.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
