// cards/pr-01/PR228 赤井秀一 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR228: CardDef = {
  id: 'PR228',
  no: 'P005/PR228',
  kind: 'partner',
  names: ['赤井秀一'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1769159336060752.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
