// cards/pr-01/PR249 遠山和葉 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR249: CardDef = {
  id: 'PR249',
  no: 'P032/PR249',
  kind: 'partner',
  names: ['遠山和葉'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1776333828559436.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
