// cards/pr-01/PR248 江戸川コナン&毛利蘭 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR248: CardDef = {
  id: 'PR248',
  no: 'P078/PR248',
  kind: 'partner',
  names: ['江戸川コナン&毛利蘭', '江戸川コナン', '毛利蘭'], // rules/19 複数名カード (BUG-185 一括分割 2026-07-10)
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1776333828548361.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
