// cards/pr-01/PR258 江戸川コナン＆世良真純 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR258: CardDef = {
  id: 'PR258',
  no: 'P080/PR258',
  kind: 'partner',
  names: ['江戸川コナン＆世良真純', '江戸川コナン', '世良真純'], // rules/19 複数名カード (BUG-185 一括分割 2026-07-10)
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1776331415751744.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
