// cards/pr-01/PR255 萩原研二 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR255: CardDef = {
  id: 'PR255',
  no: 'P079/PR255',
  kind: 'partner',
  names: ['萩原研二'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1776333828612677.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
