// cards/pr-01/PR253 横溝重悟 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR253: CardDef = {
  id: 'PR253',
  no: 'P077/PR253',
  kind: 'partner',
  names: ['横溝重悟'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1776333828596829.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
