// cards/pr-01/PR256 ジン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR256: CardDef = {
  id: 'PR256',
  no: 'P028/PR256',
  kind: 'partner',
  names: ['ジン'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1776333828621452.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
