// cards/pr-01/PR257 ベルモット (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const PR257: CardDef = {
  id: 'PR257',
  no: 'P029/PR257',
  kind: 'partner',
  names: ['ベルモット'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1776333828629825.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
