// cards/pr-01/PR252 萩原千速 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const PR252: CardDef = {
  id: 'PR252',
  no: 'P076/PR252',
  kind: 'partner',
  names: ['萩原千速'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1776333828586414.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
