// cards/pr-01/PR261 萩原千速＆横溝重悟＆萩原研二＆松田陣平 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const PR261: CardDef = {
  id: 'PR261',
  no: 'P081/PR261',
  kind: 'partner',
  names: ['萩原千速＆横溝重悟＆萩原研二＆松田陣平', '萩原千速', '横溝重悟', '萩原研二', '松田陣平'], // rules/19 複数名カード (BUG-185 一括分割 2026-07-10)
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'PR',
  imageUrl: '1776331415776369.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
