// cards/ct-p02/B02016Sec2 服部平次 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B02016Sec2: CardDef = {
  id: 'B02016Sec2',
  no: 'P003/B02016Sec2',
  kind: 'partner',
  names: ['服部平次'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '19444a898943be.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
