// cards/ct-p02/B02085 囚われた刑事 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const B02085: CardDef = {
  id: 'B02085',
  no: '0246/B02085',
  kind: 'case',
  names: ['囚われた刑事'],
  colors: ['黄'],
  traits: [],
  rarity: 'C',
  imageUrl: '1721357284560440.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
