// cards/ct-p02/B02055 沖矢昴 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B02055: CardDef = {
  id: 'B02055',
  no: 'P018/B02055',
  kind: 'partner',
  names: ['沖矢昴'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1721357250068375.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
