// cards/ct-p02/B02016 服部平次 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B02016: CardDef = {
  id: 'B02016',
  no: 'P003/B02016',
  kind: 'partner',
  names: ['服部平次'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1721357188592267.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
