// cards/ct-p02/B02071 佐藤美和子 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B02071: CardDef = {
  id: 'B02071',
  no: 'P021/B02071',
  kind: 'partner',
  names: ['佐藤美和子'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1721357267361314.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
