// cards/ct-p02/B02056 羽田秀𠮷 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B02056: CardDef = {
  id: 'B02056',
  no: 'P019/B02056',
  kind: 'partner',
  names: ['羽田秀𠮷'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1721357250075326.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
