// cards/ct-p02/B02037P 工藤優作 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B02037P: CardDef = {
  id: 'B02037P',
  no: 'P017/B02037P',
  kind: 'partner',
  names: ['工藤優作'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1721357230941979.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
