// cards/ct-p02/B02016Sec1 服部平次 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B02016Sec1: CardDef = {
  id: 'B02016Sec1',
  no: 'P003/B02016Sec1',
  kind: 'partner',
  names: ['服部平次'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '19444a9e764d5.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
