// cards/ct-p02/B02017 伊織無我 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B02017: CardDef = {
  id: 'B02017',
  no: 'P015/B02017',
  kind: 'partner',
  names: ['伊織無我'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1721357188605252.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
