// cards/ct-p02/B02036P 黒羽盗一 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B02036P: CardDef = {
  id: 'B02036P',
  no: 'P016/B02036P',
  kind: 'partner',
  names: ['黒羽盗一'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1721357230932350.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
