// cards/ct-p02/B02035Sec1 怪盗キッド (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B02035Sec1: CardDef = {
  id: 'B02035Sec1',
  no: 'P004/B02035Sec1',
  kind: 'partner',
  names: ['怪盗キッド'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '19444aaee99231.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
