// cards/ct-p02/B02034 浪花の連続殺人事件 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const B02034: CardDef = {
  id: 'B02034',
  no: '0204/B02034',
  kind: 'case',
  names: ['浪花の連続殺人事件'],
  colors: ['緑'],
  traits: [],
  rarity: 'C',
  imageUrl: '1721357211041042.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
