// cards/ct-p02/B02065 メアリー (キャラ) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 13-keywords.md, 17-icons.md, 24-qa-naming-stun.md
//
// 公式テキスト: 【解決編】〚ブレット〛（このキャラのアクションはガードできない）

import type { CardDef } from '@/engine/types';

export const B02065: CardDef = {
  id: 'B02065',
  no: '0228/B02065',
  kind: 'character',
  names: ['メアリー'],
  colors: ['赤'],
  level: 3,
  ap: 3000,
  lp: 1,
  traits: ['赤井家'],
  keywords: [],
  rarity: 'C',
  imageUrl: '1721357267323953.jpg',
  abilities: [
  {
    id: 'a1',
    type: 'continuous',
    scope: 'on-scene',
    condition: { kind: 'caseStatus', status: '解決編' },
    continuousModifier: { grantKeywords: () => ['ブレット'], printedKeywordWhenIconValid: true },
    description: '【解決編】〚ブレット〛',
    ruleRefs: ['rules/13-keywords.md', 'rules/17-icons.md'],
  },
  ],
  ruleRefs: ['rules/13-keywords.md', 'rules/17-icons.md'],
};
