// cards/ct-p02/B02054 怪盗キッドvs.最強金庫 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const B02054: CardDef = {
  id: 'B02054',
  no: '0219/B02054',
  kind: 'case',
  names: ['怪盗キッドvs.最強金庫'],
  colors: ['白'],
  traits: [],
  rarity: 'C',
  imageUrl: '1721357250061249.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
