// cards/ct-p02/B02015 水色の想い出 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const B02015: CardDef = {
  id: 'B02015',
  no: '0187/B02015',
  kind: 'case',
  names: ['水色の想い出'],
  colors: ['青'],
  traits: [],
  rarity: 'C',
  imageUrl: '1721357188585921.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
