// cards/ct-p02/B02035P 怪盗キッド (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B02035P: CardDef = {
  id: 'B02035P',
  no: 'P004/B02035P',
  kind: 'partner',
  names: ['怪盗キッド'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1721357211050194.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
