// cards/ct-p02/B02070 降谷零 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B02070: CardDef = {
  id: 'B02070',
  no: 'P020/B02070',
  kind: 'partner',
  names: ['降谷零'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1721357267349626.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
