// cards/ct-p02/B02037P 工藤優作 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B02037P: CardDef = {
  id: 'B02037P',
  no: 'P017/B02037P',
  kind: 'partner',
  names: ['工藤優作'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1721357230941979.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
