// cards/ct-p02/B02016P 服部平次 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B02016P: CardDef = {
  id: 'B02016P',
  no: 'P003/B02016P',
  kind: 'partner',
  names: ['服部平次'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1721357188595551.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
