// cards/ct-p06/B06044Sec1 鉄刃 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06044Sec1: CardDef = {
  id: 'B06044Sec1',
  no: 'P061/B06044Sec1',
  kind: 'partner',
  names: ['鉄刃'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1751616655281703.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
