// cards/ct-p06/B06045P 峰さやか (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06045P: CardDef = {
  id: 'B06045P',
  no: 'P062/B06045P',
  kind: 'partner',
  names: ['峰さやか'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1755684948573756.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
