// cards/ct-p06/B06002P 阿笠博士 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06002P: CardDef = {
  id: 'B06002P',
  no: 'P059/B06002P',
  kind: 'partner',
  names: ['阿笠博士'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1755684931812032.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
