// cards/ct-p06/B06044Sec2 鉄刃 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06044Sec2: CardDef = {
  id: 'B06044Sec2',
  no: 'P061/B06044Sec2',
  kind: 'partner',
  names: ['鉄刃'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1755762456860657.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
