// cards/ct-p06/B06041 服部静華 (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 15-abilities-effects.md, 17-icons.md, 22-qa-action-contact.md
//
// 公式テキスト(カットイン): 【カットイン】AP＋1000、〚カード名［服部平次］〛か〚［服部平蔵］〛か〚［遠山和葉］〛に【カットイン】した場合、カードを1枚引く。

import type { AbilityDef, CardDef } from '@/engine/types';
import { contactTargetMatches } from '../_shared/index.js';

const a1: AbilityDef = {
  id: 'a1',
  type: 'triggered',
  scope: 'on-hand',
  trigger: { hook: 'effect:declared', optional: true, selfOnly: true }, // 【カットイン】(コンタクト中に手札から使用)
  effect: {
    kind: 'sequence',
    steps: [
      // AP＋1000
      { kind: 'atom', verb: 'charModifyAP', args: { uid: '$contact.byUid', delta: 1000, scope: 'contact' } },
      // [服部平次]か[服部平蔵]か[遠山和葉]に【カットイン】した場合、カードを1枚引く
      { kind: 'conditional', if: contactTargetMatches({ names: ['服部平次', '服部平蔵', '遠山和葉'] }), then: { kind: 'atom', verb: 'draw', args: { player: 'self', n: 1 } } },
    ],
  },
  description: '【カットイン】AP＋1000、[服部平次]か[服部平蔵]か[遠山和葉]にカットインした場合カードを1枚引く。',
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/22-qa-action-contact.md'],
};

export const B06041: CardDef = {
  id: 'B06041',
  no: '0664/B06041',
  kind: 'character',
  names: ['服部静華'],
  colors: ['緑'],
  level: 2,
  ap: 1000,
  lp: 1,
  traits: [],
  keywords: [],
  rarity: 'C',
  imageUrl: '1754285189510053.jpg',
  abilities: [a1],
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
