// cards/ct-p06/B06092 金丸嶺太 (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 15-abilities-effects.md, 17-icons.md, 22-qa-action-contact.md
//
// 公式テキスト(カットイン): 【カットイン】AP＋1000、〚特徴［喫茶ポアロ］〛のキャラに【カットイン】した場合、カードを1枚引く。

import type { AbilityDef, CardDef } from '@/engine/types';
import { contactTargetMatches } from '../_shared/index.js';

const a1: AbilityDef = {
  id: 'a1',
  type: 'triggered',
  scope: 'on-hand',
  trigger: { hook: 'effect:declared', optional: true, selfOnly: true }, // 【カットイン】(コンタクト中に手札から使用)
  effect: {
    kind: 'sequence',
    steps: [
      // AP＋1000
      { kind: 'atom', verb: 'charModifyAP', args: { uid: '$contact.byUid', delta: 1000, scope: 'contact' } },
      // [喫茶ポアロ]に【カットイン】した場合、カードを1枚引く
      { kind: 'conditional', if: contactTargetMatches({ traits: ['喫茶ポアロ'] }), then: { kind: 'atom', verb: 'draw', args: { player: 'self', n: 1 } } },
    ],
  },
  description: '【カットイン】AP＋1000、[喫茶ポアロ]にカットインした場合カードを1枚引く。',
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/22-qa-action-contact.md'],
};

export const B06092: CardDef = {
  id: 'B06092',
  no: '0711/B06092',
  kind: 'character',
  names: ['金丸嶺太'],
  colors: ['黄'],
  level: 2,
  ap: 1000,
  lp: 1,
  traits: ['喫茶ポアロ'],
  keywords: [],
  rarity: 'C',
  imageUrl: '1754285264338497.jpg',
  abilities: [a1],
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
