// cards/ct-p06/B06097 コルン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06097: CardDef = {
  id: 'B06097',
  no: 'P066/B06097',
  kind: 'partner',
  names: ['コルン'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1754285264367517.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
