// cards/ct-p06/B06014P 鬼丸猛 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06014P: CardDef = {
  id: 'B06014P',
  no: 'P060/B06014P',
  kind: 'partner',
  names: ['鬼丸猛'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1755684931864984.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
