// cards/ct-p06/B06045 峰さやか (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06045: CardDef = {
  id: 'B06045',
  no: 'P062/B06045',
  kind: 'partner',
  names: ['峰さやか'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1751538660420596.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
