// cards/ct-p06/B06073P 赤井務武 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06073P: CardDef = {
  id: 'B06073P',
  no: 'P063/B06073P',
  kind: 'partner',
  names: ['赤井務武'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1755684967077377.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
