// cards/ct-p06/B06001Sec2 江戸川コナン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06001Sec2: CardDef = {
  id: 'B06001Sec2',
  no: 'P001/B06001Sec2',
  kind: 'partner',
  names: ['江戸川コナン'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1755762456838517.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
