// cards/ct-p06/B06097P コルン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06097P: CardDef = {
  id: 'B06097P',
  no: 'P066/B06097P',
  kind: 'partner',
  names: ['コルン'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1755684985567266.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
