// cards/ct-p06/B06015 鬼丸猛 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06015: CardDef = {
  id: 'B06015',
  no: 'P060/B06015',
  kind: 'partner',
  names: ['鬼丸猛'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1754284680603288.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
