// cards/ct-p06/B06096 キャンティ (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06096: CardDef = {
  id: 'B06096',
  no: 'P065/B06096',
  kind: 'partner',
  names: ['キャンティ'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1754285264361099.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
