// cards/ct-p06/B06083P 白鳥任三郎 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06083P: CardDef = {
  id: 'B06083P',
  no: 'P064/B06083P',
  kind: 'partner',
  names: ['白鳥任三郎'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1755684967111018.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
