// cards/ct-p06/B06096 キャンティ (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B06096: CardDef = {
  id: 'B06096',
  no: 'P065/B06096',
  kind: 'partner',
  names: ['キャンティ'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1754285264361099.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
