// cards/ct-p06/B06050 宮本武蔵 (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 17-icons.md
//
// 公式テキスト(カットイン): 【カットイン】【自分ターン中】AP＋2000 / 【カットイン】【事件YAIBA】自分のリムーブエリアにある〚特徴［YAIBA］〛のイベントを1枚まで選び、手札に加える。
//
// ⚠ DEFERRED (BUG-114): 1カードの複数カットイン(択一)を engine が個別解決できない (BUG-114)
//   → カード自体は vanilla キャラとして使用可。カットイン効果のみ未実装 (abilities:[])。

import type { CardDef } from '@/engine/types';

export const B06050: CardDef = {
  id: 'B06050',
  no: '0671/B06050',
  kind: 'character',
  names: ['宮本武蔵'],
  colors: ['白'],
  level: 2,
  ap: 1000,
  lp: 1,
  traits: ['YAIBA'],
  keywords: [],
  rarity: 'R',
  imageUrl: '1754285220467964.jpg',
  abilities: [], // DEFERRED (BUG-114): カットイン効果は engine 未対応
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
