// cards/ct-p06/B06044Sec2 鉄刃 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B06044Sec2: CardDef = {
  id: 'B06044Sec2',
  no: 'P061/B06044Sec2',
  kind: 'partner',
  names: ['鉄刃'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1755762456860657.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
