// cards/ct-p06/B06055 カゲトラ (キャラ) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 13-keywords.md, 17-icons.md, 24-qa-naming-stun.md
//
// 公式テキスト: 【パートナー白】〚突撃〛（登場したターンからすぐにアクションできる）

import type { CardDef } from '@/engine/types';
import { partnerColorKeyword } from '../_shared/index.js';

export const B06055: CardDef = {
  id: 'B06055',
  no: '0676/B06055',
  kind: 'character',
  names: ['カゲトラ'],
  colors: ['白'],
  level: 5,
  ap: 5000,
  lp: 0,
  traits: ['YAIBA'],
  keywords: [],
  rarity: 'C',
  imageUrl: '1754285220495941.jpg',
  abilities: [
  partnerColorKeyword({ color: '白', kw: '突撃', abilityId: 'a1' }),
  ],
  ruleRefs: ['rules/13-keywords.md', 'rules/17-icons.md'],
};
