// cards/ct-p06/B06002 阿笠博士 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B06002: CardDef = {
  id: 'B06002',
  no: 'P059/B06002',
  kind: 'partner',
  names: ['阿笠博士'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1754284680520862.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
