// cards/ct-p04/B04001P 工藤新一 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04001P: CardDef = {
  id: 'B04001P',
  no: 'P007/B04001P',
  kind: 'partner',
  names: ['工藤新一'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '19406fd335230a.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
