// cards/ct-p04/B04002P 毛利蘭 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04002P: CardDef = {
  id: 'B04002P',
  no: 'P031/B04002P',
  kind: 'partner',
  names: ['毛利蘭'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1735287656193320.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
