// cards/ct-p04/B04065P 高木渉 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04065P: CardDef = {
  id: 'B04065P',
  no: 'P037/B04065P',
  kind: 'partner',
  names: ['高木渉'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1735287801293945.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
