// cards/ct-p04/B04043P アンドレ・キャメル (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04043P: CardDef = {
  id: 'B04043P',
  no: 'P034/B04043P',
  kind: 'partner',
  names: ['アンドレ・キャメル'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1735287759536399.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
