// cards/ct-p04/B04066P 松田陣平 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04066P: CardDef = {
  id: 'B04066P',
  no: 'P038/B04066P',
  kind: 'partner',
  names: ['松田陣平'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1735287801303339.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
