// cards/ct-p04/B04045 水無怜奈 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04045: CardDef = {
  id: 'B04045',
  no: 'P036/B04045',
  kind: 'partner',
  names: ['水無怜奈'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1735287781697558.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
