// cards/ct-p04/B04066P 松田陣平 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B04066P: CardDef = {
  id: 'B04066P',
  no: 'P038/B04066P',
  kind: 'partner',
  names: ['松田陣平'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1735287801303339.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
