// cards/ct-p04/B04016P 遠山和葉 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04016P: CardDef = {
  id: 'B04016P',
  no: 'P032/B04016P',
  kind: 'partner',
  names: ['遠山和葉'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1735287737362689.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
