// cards/ct-p04/B04029P 鈴木園子 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04029P: CardDef = {
  id: 'B04029P',
  no: 'P033/B04029P',
  kind: 'partner',
  names: ['鈴木園子'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1735287737445867.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
