// cards/ct-p04/B04066 松田陣平 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04066: CardDef = {
  id: 'B04066',
  no: 'P038/B04066',
  kind: 'partner',
  names: ['松田陣平'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1735287801298172.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
