// cards/ct-p04/B04002Sec1 毛利蘭 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04002Sec1: CardDef = {
  id: 'B04002Sec1',
  no: 'P031/B04002Sec1',
  kind: 'partner',
  names: ['毛利蘭'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1740028685632220.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
