// cards/ct-p04/B04001 工藤新一 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04001: CardDef = {
  id: 'B04001',
  no: 'P007/B04001',
  kind: 'partner',
  names: ['工藤新一'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '19406fa26901ef.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
