// cards/ct-p04/B04067 目暮十三 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04067: CardDef = {
  id: 'B04067',
  no: 'P039/B04067',
  kind: 'partner',
  names: ['目暮十三'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1735287801307662.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
