// cards/ct-p04/B04001Sec1 工藤新一 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04001Sec1: CardDef = {
  id: 'B04001Sec1',
  no: 'P007/B04001Sec1',
  kind: 'partner',
  names: ['工藤新一'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1740028685620889.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
