// cards/ct-p04/B04043 アンドレ・キャメル (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04043: CardDef = {
  id: 'B04043',
  no: 'P034/B04043',
  kind: 'partner',
  names: ['アンドレ・キャメル'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1735287759532723.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
