// cards/ct-p04/B04044P メアリー (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04044P: CardDef = {
  id: 'B04044P',
  no: 'P035/B04044P',
  kind: 'partner',
  names: ['メアリー'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1735287781692875.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
