// cards/ct-p04/B04087P ウォッカ (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B04087P: CardDef = {
  id: 'B04087P',
  no: 'P040/B04087P',
  kind: 'partner',
  names: ['ウォッカ'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1735287841286336.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
