// cards/ct-p01/B01024 大阪“3つのK”事件 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const B01024: CardDef = {
  id: 'B01024',
  no: '0020/B01024',
  kind: 'case',
  names: ['大阪“3つのK”事件'],
  colors: ['青'],
  traits: [],
  rarity: 'C',
  imageUrl: '1714012985544152.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
