// cards/ct-p01/B01097 ウォッカ (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 15-abilities-effects.md, 17-icons.md, 22-qa-action-contact.md
//
// 公式テキスト(カットイン): 【カットイン】カードを2枚引き、手札を1枚リムーブする。（コンタクト中に手札からリムーブして使う）

import type { AbilityDef, CardDef } from '@/engine/types';

const a1: AbilityDef = {
  id: 'a1',
  type: 'triggered',
  scope: 'on-hand',
  trigger: { hook: 'effect:declared', optional: true, selfOnly: true }, // 【カットイン】(コンタクト中に手札から使用)
  effect: {
    kind: 'sequence',
    steps: [
      // カードを2枚引く
      { kind: 'atom', verb: 'draw', args: { player: 'self', n: 2 } },
      // 手札を1枚選びリムーブする
      { kind: 'atom', verb: 'discard', args: { player: 'self', n: 1 } },
    ],
  },
  description: '【カットイン】カードを2枚引き、手札を1枚リムーブする。',
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/14-refresh.md'],
};

export const B01097: CardDef = {
  id: 'B01097',
  no: '0085/B01097',
  kind: 'character',
  names: ['ウォッカ'],
  colors: ['黒'],
  level: 4,
  ap: 5000,
  lp: 0,
  traits: ['黒ずくめの組織'],
  keywords: [],
  rarity: 'C',
  imageUrl: '1714013082063255.jpg',
  abilities: [a1],
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
