// cards/ct-p01/B01003P 灰原哀 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B01003P: CardDef = {
  id: 'B01003P',
  no: 'P008/B01003P',
  kind: 'partner',
  names: ['灰原哀'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1734349765536267.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
