// cards/ct-p01/B01001Sec1 江戸川コナン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B01001Sec1: CardDef = {
  id: 'B01001Sec1',
  no: 'P001/B01001Sec1',
  kind: 'partner',
  names: ['江戸川コナン'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '194400fcb7d2fc.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
