// cards/ct-p01/B01041 コナンと平次 恋の暗号 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const B01041: CardDef = {
  id: 'B01041',
  no: '0035/B01041',
  kind: 'case',
  names: ['コナンと平次 恋の暗号'],
  colors: ['緑'],
  traits: [],
  rarity: 'C',
  imageUrl: '1714013020290747.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
