// cards/ct-p01/B01080P 風見裕也 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B01080P: CardDef = {
  id: 'B01080P',
  no: 'P013/B01080P',
  kind: 'partner',
  names: ['風見裕也'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1714013067512548.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
