// cards/ct-p01/B01003 灰原哀 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B01003: CardDef = {
  id: 'B01003',
  no: 'P008/B01003',
  kind: 'partner',
  names: ['灰原哀'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1734349765531663.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
