// cards/ct-p01/B01001P 江戸川コナン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B01001P: CardDef = {
  id: 'B01001P',
  no: 'P001/B01001P',
  kind: 'partner',
  names: ['江戸川コナン'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1734349765505926.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
