// cards/ct-p01/B01096 ギスギスしたお茶会 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const B01096: CardDef = {
  id: 'B01096',
  no: '0084/B01096',
  kind: 'case',
  names: ['ギスギスしたお茶会'],
  colors: ['黄'],
  traits: [],
  rarity: 'C',
  imageUrl: '1714013082058918.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
