// cards/ct-p01/B01002 工藤新一 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B01002: CardDef = {
  id: 'B01002',
  no: 'P007/B01002',
  kind: 'partner',
  names: ['工藤新一'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1734349765520391.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
