// cards/ct-p01/B01059 怪盗キッドの瞬間移動魔術 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const B01059: CardDef = {
  id: 'B01059',
  no: '0051/B01059',
  kind: 'case',
  names: ['怪盗キッドの瞬間移動魔術'],
  colors: ['白'],
  traits: [],
  rarity: 'C',
  imageUrl: '1714013041185453.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
