// cards/ct-p01/B01026 服部平蔵 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B01026: CardDef = {
  id: 'B01026',
  no: 'P010/B01026',
  kind: 'partner',
  names: ['服部平蔵'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1714013000973538.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
