// cards/ct-p01/B01004 毛利小五郎 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B01004: CardDef = {
  id: 'B01004',
  no: 'P009/B01004',
  kind: 'partner',
  names: ['毛利小五郎'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1734349765541322.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
