// cards/ct-p01/B01078 17年前と同じ現場 (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const B01078: CardDef = {
  id: 'B01078',
  no: '0068/B01078',
  kind: 'case',
  names: ['17年前と同じ現場'],
  colors: ['赤'],
  traits: [],
  rarity: 'C',
  imageUrl: '1714013053546952.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
