// cards/ct-p01/B01043 白馬探 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B01043: CardDef = {
  id: 'B01043',
  no: 'P011/B01043',
  kind: 'partner',
  names: ['白馬探'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1714013020300151.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
