// cards/ct-p01/B01042 怪盗キッド (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B01042: CardDef = {
  id: 'B01042',
  no: 'P004/B01042',
  kind: 'partner',
  names: ['怪盗キッド'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1714013020295439.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
