// cards/ct-p01/B01079 安室透 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B01079: CardDef = {
  id: 'B01079',
  no: 'P006/B01079',
  kind: 'partner',
  names: ['安室透'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1714013067503590.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
