// cards/ct-p01/B01060 赤井秀一 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B01060: CardDef = {
  id: 'B01060',
  no: 'P005/B01060',
  kind: 'partner',
  names: ['赤井秀一'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1714013041191479.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
