// cards/ct-p01/B01061P 世良真純 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B01061P: CardDef = {
  id: 'B01061P',
  no: 'P012/B01061P',
  kind: 'partner',
  names: ['世良真純'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1714013041200963.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
