// cards/ct-p01/B01098 ジン (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 15-abilities-effects.md, 17-icons.md, 22-qa-action-contact.md
//
// 公式テキスト(カットイン): 【カットイン】【自分ターン中】（自分のターンのコンタクト中に手札からリムーブすることで発動する）コンタクト中のすべてのキャラをリムーブする。

import type { AbilityDef, CardDef } from '@/engine/types';

const a1: AbilityDef = {
  id: 'a1',
  type: 'triggered',
  scope: 'on-hand',
  trigger: { hook: 'effect:declared', optional: true, selfOnly: true }, // 【カットイン】(コンタクト中に手札から使用)
  condition: { kind: 'turn', player: 'self' }, // 【自分ターン中】
  effect: {
    kind: 'sequence',
    steps: [
      // コンタクト中のすべてのキャラ (相手側 → 自分側) をリムーブする
      { kind: 'atom', verb: 'sceneRemove', args: { uid: '$contact.targetUid', cause: 'effect' } },
      { kind: 'atom', verb: 'sceneRemove', args: { uid: '$contact.byUid', cause: 'effect' } },
    ],
  },
  description: '【カットイン】【自分ターン中】コンタクト中のすべてのキャラをリムーブする。',
  ruleRefs: ['rules/08-contact.md', 'rules/09-cutin-disguise.md'],
};

export const B01098: CardDef = {
  id: 'B01098',
  no: '0086/B01098',
  kind: 'character',
  names: ['ジン'],
  colors: ['黒'],
  level: 6,
  ap: 6000,
  lp: 1,
  traits: ['黒ずくめの組織'],
  keywords: [],
  rarity: 'R',
  imageUrl: '1714013082069934.jpg',
  abilities: [a1],
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
