// cards/ct-p09/B09053P 世良真純 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B09053P: CardDef = {
  id: 'B09053P',
  no: 'P012/B09053P',
  kind: 'partner',
  names: ['世良真純'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1775608872685399.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
