// cards/ct-p09/B09091 ジン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B09091: CardDef = {
  id: 'B09091',
  no: 'P028/B09091',
  kind: 'partner',
  names: ['ジン'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1775608926405785.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
