// cards/ct-p09/B09001 江戸川コナン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B09001: CardDef = {
  id: 'B09001',
  no: 'P001/B09001',
  kind: 'partner',
  names: ['江戸川コナン'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1775608802525878.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
