// cards/ct-p09/B09053 世良真純 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B09053: CardDef = {
  id: 'B09053',
  no: 'P012/B09053',
  kind: 'partner',
  names: ['世良真純'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1775608872676497.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
