// cards/ct-p09/B09031 松田左文字 (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 15-abilities-effects.md, 17-icons.md, 22-qa-action-contact.md
//
// 公式テキスト(カットイン): 【カットイン】【自分ターン中】自分の現場にいる〚特徴［探偵］〛のキャラ1枚につき、AP＋1000（自分のターンのコンタクト中に手札からリムーブして使う）

import type { AbilityDef, CardDef } from '@/engine/types';

const a1: AbilityDef = {
  id: 'a1',
  type: 'triggered',
  scope: 'on-hand',
  trigger: { hook: 'effect:declared', optional: true, selfOnly: true }, // 【カットイン】(コンタクト中に手札から使用)
  condition: { kind: 'turn', player: 'self' }, // 【自分ターン中】
  // 自分の現場の[探偵]1枚につき AP＋1000 (D08007 dyn 同型)
  effect: { kind: 'atom', verb: 'charModifyAP', args: { uid: '$contact.byUid', delta: { dyn: '$self.sceneTrait.探偵 * 1000' }, scope: 'contact' } },
  description: '【カットイン】【自分ターン中】自分の現場の[探偵]1枚につきAP＋1000',
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/22-qa-action-contact.md'],
};

export const B09031: CardDef = {
  id: 'B09031',
  no: '0975/B09031',
  kind: 'character',
  names: ['松田左文字'],
  colors: ['緑'],
  level: 2,
  ap: 1000,
  lp: 1,
  traits: ['探偵'],
  keywords: [],
  rarity: 'C',
  imageUrl: '1775608835830982.jpg',
  abilities: [a1],
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
