// cards/ct-p09/B09069Sec1 横溝重悟 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B09069Sec1: CardDef = {
  id: 'B09069Sec1',
  no: 'P077/B09069Sec1',
  kind: 'partner',
  names: ['横溝重悟'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1775693378085053.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
