// cards/ct-p09/B09068 萩原千速 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B09068: CardDef = {
  id: 'B09068',
  no: 'P076/B09068',
  kind: 'partner',
  names: ['萩原千速'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1775608890068159.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
