import type { AbilityDef, CardDef } from '@/engine/types';

const a1: AbilityDef = { id: 'a1', type: 'triggered', scope: 'on-scene', trigger: { hook: 'enter', selfOnly: true }, condition: { kind: 'and', cs: [{ kind: 'caseColor', color: ['赤', '黒'], combine: 'and' }, { kind: 'caseStatus', status: '事件編' }] }, effect: { kind: 'chain', steps: [
  { kind: 'atom', verb: 'sceneRemove', args: { player: 'self', max: 1, side: 'opp', cause: 'effect', filter: { levelMin: 7 }, bind: '$removed' } },
  { kind: 'atom', verb: 'deckRevealUntil', args: { player: 'opp', maxN: 10, visibility: 'public', viewer: 'all', stopAtFirstMatch: true, filter: { cardNameAnyBound: '$removed' }, bind: '$revealed' } },
  { kind: 'atom', verb: 'boundToRemove', args: { player: 'opp', bindKey: '$revealed' } },
] }, description: '【事件赤＆黒】【登場時】相手の現場にいるレベル7以上のキャラを1枚まで選び、リムーブする。リムーブした場合、相手はデッキのカードを上からリムーブしたキャラと同じカード名のキャラが出るか、カードを10枚公開するまで1枚ずつ公開し、公開したカードをすべてリムーブエリアに移す。', ruleRefs: ['rules/15-abilities-effects.md', 'rules/17-icons.md', 'rules/19-special-rules.md'] };
const a2: AbilityDef = { id: 'a2', type: 'declared', scope: 'on-partner-area', limit: { kind: 'turn', n: 1 }, effect: { kind: 'sequence', steps: [{ kind: 'atom', verb: 'draw', args: { player: 'self', n: 1 } }, { kind: 'choice', chooser: 'self', options: [{ kind: 'atom', verb: 'discard', args: { player: 'self', n: 1 } }, { kind: 'atom', verb: 'sceneRemove', args: { uid: '$self', cause: 'effect' } }] }] }, description: '【宣言】【ターン1】カードを1枚引く。手札を1枚リムーブするか、このキャラをリムーブする。この能力はパートナーエリアでも宣言できる。', ruleRefs: ['rules/15-abilities-effects.md', 'rules/18-mr.md', 'rules/21-declared-ability-cost.md'] };
const a3: AbilityDef = { id: 'a3', type: 'triggered', scope: 'on-hand', trigger: { hook: 'effect:declared', optional: true, selfOnly: true }, effect: { kind: 'atom', verb: 'charModifyAP', args: { uid: '$contact.byUid', delta: 2000, scope: 'contact' } }, description: '【カットイン】AP＋2000', ruleRefs: ['rules/09-cutin-disguise.md', 'rules/22-qa-action-contact.md'] };
export const B09110: CardDef = { id: 'B09110', no: '1049/B09110', kind: 'character', names: ['赤井秀一&ジン', '赤井秀一', 'ジン'], colors: ['赤', '黒'], level: 9, ap: 8000, lp: 2, traits: ['FBI', '赤井家', '黒ずくめの組織'], keywords: [], rarity: 'MR', imageUrl: '1775608962342732.jpg', abilities: [a1, a2, a3], ruleRefs: ['rules/15-abilities-effects.md', 'rules/17-icons.md', 'rules/18-mr.md', 'rules/19-special-rules.md', 'rules/21-declared-ability-cost.md'] };
