// cards/ct-p07/B07009 小林澄子 (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 15-abilities-effects.md, 17-icons.md, 22-qa-action-contact.md
//
// 公式テキスト(カットイン): 【カットイン】AP＋1000、〚カード名［白鳥任三郎］〛か〚特徴［少年探偵団］〛のキャラに【カットイン】した場合、カードを1枚引く。（コンタクト中に手札からリムーブして使う）

import type { AbilityDef, CardDef } from '@/engine/types';
import { contactTargetMatches } from '../_shared/index.js';

const a1: AbilityDef = {
  id: 'a1',
  type: 'triggered',
  scope: 'on-hand',
  trigger: { hook: 'effect:declared', optional: true, selfOnly: true }, // 【カットイン】(コンタクト中に手札から使用)
  effect: {
    kind: 'sequence',
    steps: [
      // AP＋1000
      { kind: 'atom', verb: 'charModifyAP', args: { uid: '$contact.byUid', delta: 1000, scope: 'contact' } },
      // [白鳥任三郎]か[少年探偵団]に【カットイン】した場合、カードを1枚引く
      { kind: 'conditional', if: contactTargetMatches({ names: ['白鳥任三郎'], traits: ['少年探偵団'] }), then: { kind: 'atom', verb: 'draw', args: { player: 'self', n: 1 } } },
    ],
  },
  description: '【カットイン】AP＋1000、[白鳥任三郎]か[少年探偵団]にカットインした場合カードを1枚引く。',
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/22-qa-action-contact.md'],
};

export const B07009: CardDef = {
  id: 'B07009',
  no: '0741/B07009',
  kind: 'character',
  names: ['小林澄子'],
  colors: ['青'],
  level: 2,
  ap: 1000,
  lp: 1,
  traits: ['教師'],
  keywords: [],
  rarity: 'C',
  imageUrl: '1762413976090100.jpg',
  abilities: [a1],
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
