// cards/ct-p07/B07092P ライ (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B07092P: CardDef = {
  id: 'B07092P',
  no: 'P069/B07092P',
  kind: 'partner',
  names: ['ライ'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1763546840456569.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
