// cards/ct-p07/B07085 榎本梓 (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 15-abilities-effects.md, 17-icons.md, 22-qa-action-contact.md
//
// 公式テキスト(カットイン): 【カットイン】【自分ターン中】自分の現場にいる〚特徴［喫茶ポアロ］〛のキャラ1枚につき、AP＋1000（自分のターンのコンタクト中に手札からリムーブして使う）

import type { AbilityDef, CardDef } from '@/engine/types';

const a1: AbilityDef = {
  id: 'a1',
  type: 'triggered',
  scope: 'on-hand',
  trigger: { hook: 'effect:declared', optional: true, selfOnly: true }, // 【カットイン】(コンタクト中に手札から使用)
  condition: { kind: 'turn', player: 'self' }, // 【自分ターン中】
  // 自分の現場の[喫茶ポアロ]1枚につき AP＋1000 (D08007 dyn 同型)
  effect: { kind: 'atom', verb: 'charModifyAP', args: { uid: '$contact.byUid', delta: { dyn: '$self.sceneTrait.喫茶ポアロ * 1000' }, scope: 'contact' } },
  description: '【カットイン】【自分ターン中】自分の現場の[喫茶ポアロ]1枚につきAP＋1000',
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/22-qa-action-contact.md'],
};

export const B07085: CardDef = {
  id: 'B07085',
  no: '0813/B07085',
  kind: 'character',
  names: ['榎本梓'],
  colors: ['黄'],
  level: 2,
  ap: 1000,
  lp: 1,
  traits: ['喫茶ポアロ'],
  keywords: [],
  rarity: 'C',
  imageUrl: '1762414027401624.jpg',
  abilities: [a1],
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
