// cards/ct-p07/B07028Sec1 中森青子 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B07028Sec1: CardDef = {
  id: 'B07028Sec1',
  no: 'P054/B07028Sec1',
  kind: 'partner',
  names: ['中森青子'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1759154512388424.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
