// cards/ct-p07/B07078P 目暮みどり (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B07078P: CardDef = {
  id: 'B07078P',
  no: 'P068/B07078P',
  kind: 'partner',
  names: ['目暮みどり'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1763546825806433.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
