// cards/ct-p07/B07027Sec2 小泉紅子 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B07027Sec2: CardDef = {
  id: 'B07027Sec2',
  no: 'P067/B07027Sec2',
  kind: 'partner',
  names: ['小泉紅子'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1763546798363870.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
