// cards/ct-p07/B07092 ライ (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B07092: CardDef = {
  id: 'B07092',
  no: 'P069/B07092',
  kind: 'partner',
  names: ['ライ'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1762414027512335.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
