// cards/ct-p07/B07078 目暮みどり (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B07078: CardDef = {
  id: 'B07078',
  no: 'P068/B07078',
  kind: 'partner',
  names: ['目暮みどり'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1762414027335333.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
