// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B05052  |  scenarios: 5  |  fixtures: 6

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B05052 } from '@/cards/ct-p05/B05052';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_levelMax",
    "no": "__DE_0_levelMax",
    "kind": "character",
    "names": [
      "__DE_0_levelMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 4,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_kind",
    "no": "__DE_0_kind",
    "kind": "event",
    "names": [
      "__DE_0_kind"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__COND_BOND__",
    "no": "__COND_BOND__",
    "kind": "character",
    "names": [
      "工藤新一"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__COST_HAND_0_0",
    "no": "__COST_HAND_0_0",
    "kind": "character",
    "names": [
      "__COST_HAND_0_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__COST_SET_0_0",
    "no": "__COST_SET_0_0",
    "kind": "character",
    "names": [
      "__COST_SET_0_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B05052 happy-path (cost choice 0) (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B05052",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__COND_BOND__",
          "uid": "__COND_BOND___u",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [
        "__COST_HAND_0_0"
      ],
      "remove": [
        "__IN_0",
        "__DE_0_levelMax",
        "__DE_0_kind"
      ],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a2",
      "costParams": {
        "costChoice": 0
      }
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_levelMax"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_kind"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "self",
        "present": true
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "remove",
        "side": "self",
        "present": false
      },
      {
        "kind": "zone",
        "cardId": "__COST_HAND_0_0",
        "zone": "hand",
        "side": "self",
        "present": false
      },
      {
        "kind": "zone",
        "cardId": "__COST_HAND_0_0",
        "zone": "remove",
        "side": "self",
        "present": true
      }
    ]
  },
  {
    "name": "B05052 happy-path (cost choice 1) (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B05052",
          "uid": "__CARRIER__",
          "state": "active",
          "setCards": [
            {
              "cardId": "__COST_SET_0_0",
              "instanceId": "set:__CARRIER__:0:0",
              "faceUp": true
            }
          ]
        },
        {
          "cardId": "__COND_BOND__",
          "uid": "__COND_BOND___u",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [],
      "remove": [
        "__IN_0",
        "__DE_0_levelMax",
        "__DE_0_kind"
      ],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a2",
      "costParams": {
        "costChoice": 1,
        "removeSetCard": {
          "hostUids": [
            "__CARRIER__"
          ],
          "instanceIds": [
            "set:__CARRIER__:0:0"
          ]
        }
      }
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_levelMax"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_kind"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "self",
        "present": true
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "remove",
        "side": "self",
        "present": false
      },
      {
        "kind": "zone",
        "cardId": "__COST_SET_0_0",
        "zone": "remove",
        "side": "self",
        "present": true
      }
    ]
  },
  {
    "name": "B05052 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B05052",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__COND_BOND__",
          "uid": "__COND_BOND___u",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [
        "__COST_HAND_0_0"
      ],
      "remove": [
        "__IN_0",
        "__DE_0_levelMax",
        "__DE_0_kind"
      ],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a2"
    },
    "script": [
      "pick:skip"
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "remove",
        "side": "self",
        "present": true
      }
    ]
  },
  {
    "name": "B05052 cost-gate (cost choice 0): removeFromHand unpayable (empty hand) -> canPay=false",
    "setup": {
      "selfScene": [
        {
          "cardId": "B05052",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__COND_BOND__",
          "uid": "__COND_BOND___u",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [],
      "remove": [
        "__IN_0",
        "__DE_0_levelMax",
        "__DE_0_kind"
      ],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "cost-gate",
      "uid": "__CARRIER__",
      "abilityId": "a2",
      "expectCanPay": false
    },
    "script": [],
    "expect": []
  },
  {
    "name": "B05052 cost-gate (cost choice 1): removeSetCard unpayable (no eligible set card) -> canPay=false",
    "setup": {
      "selfScene": [
        {
          "cardId": "B05052",
          "uid": "__CARRIER__",
          "state": "active",
          "setCards": []
        },
        {
          "cardId": "__COND_BOND__",
          "uid": "__COND_BOND___u",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [],
      "remove": [
        "__IN_0",
        "__DE_0_levelMax",
        "__DE_0_kind"
      ],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "cost-gate",
      "uid": "__CARRIER__",
      "abilityId": "a2",
      "expectCanPay": false
    },
    "script": [],
    "expect": []
  }
];

describe('B05052 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B05052, FIXTURES, sc);
    });
  }
});
