// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B07036  |  scenarios: 4  |  fixtures: 5

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B07036 } from '@/cards/ct-p07/B07036';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "白"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_color",
    "no": "__DE_0_color",
    "kind": "character",
    "names": [
      "__DE_0_color"
    ],
    "colors": [
      "黒"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__IN_1",
    "no": "__IN_1",
    "kind": "character",
    "names": [
      "__IN_1"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__IN_2",
    "no": "__IN_2",
    "kind": "character",
    "names": [
      "__IN_2"
    ],
    "colors": [
      "赤"
    ],
    "level": 7,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_2_levelMax",
    "no": "__DE_2_levelMax",
    "kind": "character",
    "names": [
      "__DE_2_levelMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 8,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B07036 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07036",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_color",
          "uid": "__DE_0_color_u",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_2",
          "uid": "__INU_2",
          "state": "active"
        },
        {
          "cardId": "__DE_2_levelMax",
          "uid": "__DE_2_levelMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__IN_1"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "enter",
      "cardId": "B07036",
      "uid": "__CARRIER__",
      "side": "self"
    },
    "script": [
      "optional:take",
      {
        "pickCardId": "__IN_0"
      },
      {
        "pickCardId": "__IN_1"
      },
      {
        "pickCardId": "__IN_2"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_color"
      },
      {
        "kind": "state",
        "uid": "__INU_0",
        "state": "sleep"
      },
      {
        "kind": "zone",
        "cardId": "__IN_1",
        "zone": "hand",
        "side": "self",
        "present": false
      },
      {
        "kind": "zone",
        "cardId": "__IN_1",
        "zone": "remove",
        "side": "self",
        "present": true
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 2,
        "cardId": "__DE_2_levelMax"
      },
      {
        "kind": "zone",
        "cardId": "__IN_2",
        "zone": "scene",
        "side": "opp",
        "present": false
      }
    ]
  },
  {
    "name": "B07036 condition-off (caseStatus!=解決編) -> no prompt",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07036",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_color",
          "uid": "__DE_0_color_u",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_2",
          "uid": "__INU_2",
          "state": "active"
        },
        {
          "cardId": "__DE_2_levelMax",
          "uid": "__DE_2_levelMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__IN_1"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "事件編"
    },
    "drive": {
      "kind": "enter",
      "cardId": "B07036",
      "uid": "__CARRIER__",
      "side": "self"
    },
    "script": [],
    "expect": [
      {
        "kind": "noPromptSurfaced"
      }
    ]
  },
  {
    "name": "B07036 optional-decline (inner effect does not fire)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07036",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_color",
          "uid": "__DE_0_color_u",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_2",
          "uid": "__INU_2",
          "state": "active"
        },
        {
          "cardId": "__DE_2_levelMax",
          "uid": "__DE_2_levelMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__IN_1"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "enter",
      "cardId": "B07036",
      "uid": "__CARRIER__",
      "side": "self"
    },
    "script": [
      "optional:decline"
    ],
    "expect": [
      {
        "kind": "state",
        "uid": "__INU_0",
        "state": "active"
      },
      {
        "kind": "zone",
        "cardId": "__IN_1",
        "zone": "hand",
        "side": "self",
        "present": true
      },
      {
        "kind": "zone",
        "cardId": "__IN_2",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  },
  {
    "name": "B07036 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07036",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_color",
          "uid": "__DE_0_color_u",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_2",
          "uid": "__INU_2",
          "state": "active"
        },
        {
          "cardId": "__DE_2_levelMax",
          "uid": "__DE_2_levelMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__IN_1"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "enter",
      "cardId": "B07036",
      "uid": "__CARRIER__",
      "side": "self"
    },
    "script": [
      "optional:take",
      {
        "pickCardId": "__IN_0"
      },
      {
        "pickCardId": "__IN_1"
      },
      "pick:skip"
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_2",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  }
];

describe('B07036 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B07036, FIXTURES, sc);
    });
  }
});
