// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B07032  |  scenarios: 5  |  fixtures: 5

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B07032 } from '@/cards/ct-p07/B07032';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 8000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_apMax",
    "no": "__DE_0_apMax",
    "kind": "character",
    "names": [
      "__DE_0_apMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 9000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__IN_1",
    "no": "__IN_1",
    "kind": "character",
    "names": [
      "__IN_1"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "ビッグジュエル"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_1_trait",
    "no": "__DE_1_trait",
    "kind": "character",
    "names": [
      "__DE_1_trait"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "__DTRAIT__"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__HAND_FODDER__",
    "no": "__HAND_FODDER__",
    "kind": "character",
    "names": [
      "__HAND_FODDER__"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B07032 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07032",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [
        "__IN_1",
        "__DE_1_trait"
      ],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      },
      "optional:take",
      {
        "pickCardId": "__IN_1"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_apMax"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": false
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 1,
        "cardId": "__DE_1_trait"
      },
      {
        "kind": "zone",
        "cardId": "__IN_1",
        "zone": "partner-area",
        "side": "self",
        "present": false
      },
      {
        "kind": "deckDelta",
        "side": "self",
        "n": -2
      }
    ]
  },
  {
    "name": "B07032 optional-decline (inner effect does not fire)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07032",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [
        "__IN_1",
        "__DE_1_trait"
      ],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      "pick:skip",
      "optional:decline"
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_1",
        "zone": "partner-area",
        "side": "self",
        "present": true
      },
      {
        "kind": "deckDelta",
        "side": "self",
        "n": 0
      }
    ]
  },
  {
    "name": "B07032 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07032",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [
        "__IN_1",
        "__DE_1_trait"
      ],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      "pick:skip",
      "optional:take",
      {
        "pickCardId": "__IN_1"
      }
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  },
  {
    "name": "B07032 cost-gate: sleepSelf unpayable (self sleeping) -> canPay=false",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07032",
          "uid": "__CARRIER__",
          "state": "sleep"
        }
      ],
      "hand": [
        "__HAND_FODDER__"
      ],
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "cost-gate",
      "uid": "__CARRIER__",
      "abilityId": "a1",
      "expectCanPay": false
    },
    "script": [],
    "expect": []
  },
  {
    "name": "B07032 cost-gate: removeFromHand unpayable (empty hand) -> canPay=false",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07032",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "hand": [],
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "cost-gate",
      "uid": "__CARRIER__",
      "abilityId": "a1",
      "expectCanPay": false
    },
    "script": [],
    "expect": []
  }
];

describe('B07032 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B07032, FIXTURES, sc);
    });
  }
});
