// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B09089  |  scenarios: 2  |  fixtures: 6

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B09089 } from '@/cards/ct-p09/B09089';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 8000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_apMax",
    "no": "__DE_0_apMax",
    "kind": "character",
    "names": [
      "__DE_0_apMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 9000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__IN_1",
    "no": "__IN_1",
    "kind": "character",
    "names": [
      "__IN_1"
    ],
    "colors": [
      "赤"
    ],
    "level": 4,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "警察"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_1_levelMax",
    "no": "__DE_1_levelMax",
    "kind": "character",
    "names": [
      "__DE_1_levelMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 5,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "警察"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_1_trait",
    "no": "__DE_1_trait",
    "kind": "character",
    "names": [
      "__DE_1_trait"
    ],
    "colors": [
      "赤"
    ],
    "level": 4,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "__DTRAIT__"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_1_kind",
    "no": "__DE_1_kind",
    "kind": "event",
    "names": [
      "__DE_1_kind"
    ],
    "colors": [
      "赤"
    ],
    "level": 4,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "警察"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B09089 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "B09089"
      ],
      "remove": [
        "__IN_1",
        "__DE_1_levelMax",
        "__DE_1_trait",
        "__DE_1_kind"
      ],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseColors": [
        "黄"
      ],
      "fileCount": 7
    },
    "drive": {
      "kind": "event-use",
      "cardId": "B09089"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      },
      {
        "pickCardId": "__IN_1"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_apMax"
      },
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": false
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 1,
        "cardId": "__DE_1_levelMax"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 1,
        "cardId": "__DE_1_trait"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 1,
        "cardId": "__DE_1_kind"
      },
      {
        "kind": "zone",
        "cardId": "__IN_1",
        "zone": "scene",
        "side": "self",
        "present": true
      },
      {
        "kind": "zone",
        "cardId": "__IN_1",
        "zone": "remove",
        "side": "self",
        "present": false
      },
      {
        "kind": "zone",
        "cardId": "B09089",
        "zone": "hand",
        "side": "self",
        "present": false
      }
    ]
  },
  {
    "name": "B09089 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__DE_0_apMax",
          "uid": "__DE_0_apMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "B09089"
      ],
      "remove": [
        "__IN_1",
        "__DE_1_levelMax",
        "__DE_1_trait",
        "__DE_1_kind"
      ],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseColors": [
        "黄"
      ],
      "fileCount": 7
    },
    "drive": {
      "kind": "event-use",
      "cardId": "B09089"
    },
    "script": [
      "pick:skip",
      {
        "pickCardId": "__IN_1"
      }
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  }
];

describe('B09089 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B09089, FIXTURES, sc);
    });
  }
});
