// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B07015  |  scenarios: 3  |  fixtures: 5

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B07015 } from '@/cards/ct-p07/B07015';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "event",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "緑"
    ],
    "level": 5,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_levelMax",
    "no": "__DE_0_levelMax",
    "kind": "event",
    "names": [
      "__DE_0_levelMax"
    ],
    "colors": [
      "緑"
    ],
    "level": 7,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_levelMin",
    "no": "__DE_0_levelMin",
    "kind": "event",
    "names": [
      "__DE_0_levelMin"
    ],
    "colors": [
      "緑"
    ],
    "level": 4,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_0_color",
    "no": "__DE_0_color",
    "kind": "event",
    "names": [
      "__DE_0_color"
    ],
    "colors": [
      "黒"
    ],
    "level": 5,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__HAND_FODDER__",
    "no": "__HAND_FODDER__",
    "kind": "character",
    "names": [
      "__HAND_FODDER__"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B07015 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07015",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [
        "__HAND_FODDER__",
        "__IN_0",
        "__DE_0_levelMax",
        "__DE_0_levelMin",
        "__DE_0_color"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編",
      "fileCount": 6,
      "partnerColors": [
        "緑"
      ]
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      }
    ],
    "expect": [
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_levelMax"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_levelMin"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_0_color"
      }
    ]
  },
  {
    "name": "B07015 condition-off (partnerColor mismatch) -> no prompt",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07015",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [
        "__HAND_FODDER__",
        "__DE_0_levelMax",
        "__DE_0_levelMin",
        "__DE_0_color"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編",
      "partnerColors": [
        "__NOMATCH__"
      ]
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [],
    "expect": [
      {
        "kind": "noPromptSurfaced"
      }
    ]
  },
  {
    "name": "B07015 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07015",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [
        "__HAND_FODDER__",
        "__IN_0",
        "__DE_0_levelMax",
        "__DE_0_levelMin",
        "__DE_0_color"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編",
      "fileCount": 6,
      "partnerColors": [
        "緑"
      ]
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [
      "pick:skip"
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "hand",
        "side": "self",
        "present": true
      }
    ]
  }
];

describe('B07015 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B07015, FIXTURES, sc);
    });
  }
});
