// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B08072  |  scenarios: 2  |  fixtures: 1

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B08072 } from '@/cards/ct-p08/B08072';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__TAKAGI__",
    "no": "__TAKAGI__",
    "kind": "character",
    "names": [
      "高木渉"
    ],
    "colors": [
      "黄"
    ],
    "level": 8,
    "ap": 7000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B08072 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B08072",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__TAKAGI__",
          "uid": "__TAKAGI_U__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        }
      ],
      "hand": [],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "enter",
      "cardId": "B08072",
      "uid": "__CARRIER__",
      "side": "self"
    },
    "script": [
      {
        "pickCardId": "__IN_0"
      }
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": false
      }
    ]
  },
  {
    "name": "B08072 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B08072",
          "uid": "__CARRIER__",
          "state": "active"
        },
        {
          "cardId": "__TAKAGI__",
          "uid": "__TAKAGI_U__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        }
      ],
      "hand": [],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "enter",
      "cardId": "B08072",
      "uid": "__CARRIER__",
      "side": "self"
    },
    "script": [
      "pick:skip"
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  }
];

describe('B08072 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B08072, FIXTURES, sc);
    });
  }
});
