// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B08064  |  scenarios: 4  |  fixtures: 7

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B08064 } from '@/cards/ct-p08/B08064';

const FIXTURES: CardDef[] = [
  {
    "id": "__IN_0",
    "no": "__IN_0",
    "kind": "character",
    "names": [
      "__IN_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__IN_1",
    "no": "__IN_1",
    "kind": "character",
    "names": [
      "__IN_1"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "警視庁"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_1_trait",
    "no": "__DE_1_trait",
    "kind": "character",
    "names": [
      "__DE_1_trait"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "__DTRAIT__"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_1_kind",
    "no": "__DE_1_kind",
    "kind": "event",
    "names": [
      "__DE_1_kind"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "警視庁"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__IN_2",
    "no": "__IN_2",
    "kind": "character",
    "names": [
      "__IN_2"
    ],
    "colors": [
      "赤"
    ],
    "level": 7,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__DE_2_levelMax",
    "no": "__DE_2_levelMax",
    "kind": "character",
    "names": [
      "__DE_2_levelMax"
    ],
    "colors": [
      "赤"
    ],
    "level": 8,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__HAND_FODDER__",
    "no": "__HAND_FODDER__",
    "kind": "character",
    "names": [
      "__HAND_FODDER__"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B08064 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B08064",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__IN_2",
          "uid": "__INU_2",
          "state": "active"
        },
        {
          "cardId": "__DE_2_levelMax",
          "uid": "__DE_2_levelMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__IN_1",
        "__DE_1_trait",
        "__DE_1_kind"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "enter",
      "cardId": "B08064",
      "uid": "__CARRIER__",
      "side": "self"
    },
    "script": [
      "optional:take",
      {
        "pickCardId": "__IN_1"
      },
      {
        "pickCardId": "__IN_2"
      }
    ],
    "expect": [
      {
        "kind": "state",
        "uid": "__CARRIER__",
        "state": "sleep"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_1_trait"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 0,
        "cardId": "__DE_1_kind"
      },
      {
        "kind": "candidatesExclude",
        "pickIndex": 1,
        "cardId": "__DE_2_levelMax"
      },
      {
        "kind": "zone",
        "cardId": "__IN_2",
        "zone": "scene",
        "side": "opp",
        "present": false
      }
    ]
  },
  {
    "name": "B08064 optional-decline (inner effect does not fire)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B08064",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__IN_2",
          "uid": "__INU_2",
          "state": "active"
        },
        {
          "cardId": "__DE_2_levelMax",
          "uid": "__DE_2_levelMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__IN_1",
        "__DE_1_trait",
        "__DE_1_kind"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "enter",
      "cardId": "B08064",
      "uid": "__CARRIER__",
      "side": "self"
    },
    "script": [
      "optional:decline"
    ],
    "expect": [
      {
        "kind": "state",
        "uid": "__INU_0",
        "state": "active"
      },
      {
        "kind": "zone",
        "cardId": "__IN_2",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  },
  {
    "name": "B08064 nMin-0 skip (「1枚まで」= 0枚 legal; target unchanged)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B08064",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [
        {
          "cardId": "__IN_0",
          "uid": "__INU_0",
          "state": "active"
        },
        {
          "cardId": "__IN_2",
          "uid": "__INU_2",
          "state": "active"
        },
        {
          "cardId": "__DE_2_levelMax",
          "uid": "__DE_2_levelMax_u",
          "state": "active"
        }
      ],
      "hand": [
        "__IN_1",
        "__DE_1_trait",
        "__DE_1_kind"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "enter",
      "cardId": "B08064",
      "uid": "__CARRIER__",
      "side": "self"
    },
    "script": [
      "optional:take",
      {
        "pickCardId": "__IN_1"
      },
      "pick:skip"
    ],
    "expect": [
      {
        "kind": "zone",
        "cardId": "__IN_0",
        "zone": "scene",
        "side": "opp",
        "present": true
      },
      {
        "kind": "zone",
        "cardId": "__IN_2",
        "zone": "scene",
        "side": "opp",
        "present": true
      }
    ]
  },
  {
    "name": "B08064 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B08064",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a2"
    },
    "script": [],
    "expect": [
      {
        "kind": "handDelta",
        "side": "self",
        "n": 1
      },
      {
        "kind": "deckDelta",
        "side": "self",
        "n": 0
      },
      {
        "kind": "zone",
        "cardId": "B08064",
        "zone": "scene",
        "side": "self",
        "present": false
      },
      {
        "kind": "zone",
        "cardId": "B08064",
        "zone": "deck",
        "side": "self",
        "present": true
      }
    ]
  }
];

describe('B08064 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B08064, FIXTURES, sc);
    });
  }
});
