// cards/ct-d02/D02003 服部平次 (キャラ) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 13-keywords.md, 17-icons.md, 24-qa-naming-stun.md
//
// 公式テキスト: 【パートナー緑】〚迅速〛（登場したターンからすぐに推理かアクションできる）

import type { CardDef } from '@/engine/types';
import { partnerColorKeyword } from '../_shared/index.js';

export const D02003: CardDef = {
  id: 'D02003',
  no: '0106/D02003',
  kind: 'character',
  names: ['服部平次'],
  colors: ['緑'],
  level: 7,
  ap: 6000,
  lp: 1,
  traits: ['探偵', '高校生'],
  keywords: [],
  rarity: 'D',
  imageUrl: '1714013100447862.jpg',
  abilities: [
  partnerColorKeyword({ color: '緑', kw: '迅速', abilityId: 'a1' }),
  ],
  ruleRefs: ['rules/13-keywords.md', 'rules/17-icons.md'],
};
