// cards/ct-d02/D02010 伊織無我 (キャラ) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 09-cutin-disguise.md, 15-abilities-effects.md, 17-icons.md, 22-qa-action-contact.md
//
// 公式テキスト(カットイン): 【カットイン】AP＋1000（コンタクト中に手札からリムーブして使う）

import type { AbilityDef, CardDef } from '@/engine/types';

const a1: AbilityDef = {
  id: 'a1',
  type: 'triggered',
  scope: 'on-hand',
  trigger: { hook: 'effect:declared', optional: true, selfOnly: true }, // 【カットイン】(コンタクト中に手札から使用)
  // 【カットイン】AP＋1000 — コンタクト中の攻撃キャラ ($contact.byUid) を contact scope で加算 (D08015 a2 同型)
  effect: { kind: 'atom', verb: 'charModifyAP', args: { uid: '$contact.byUid', delta: 1000, scope: 'contact' } },
  description: '【カットイン】AP＋1000',
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/22-qa-action-contact.md'],
};

export const D02010: CardDef = {
  id: 'D02010',
  no: '0113/D02010',
  kind: 'character',
  names: ['伊織無我'],
  colors: ['緑'],
  level: 4,
  ap: 4000,
  lp: 1,
  traits: ['執事'],
  keywords: [],
  rarity: 'D',
  imageUrl: '1714013117376760.jpg',
  abilities: [a1],
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
