// cards/ct-d02/D02007 沖田総司 (キャラ) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 13-keywords.md, 17-icons.md, 24-qa-naming-stun.md
//
// 公式テキスト: 【パートナー緑】〚突撃〛（登場したターンからすぐにアクションできる）

import type { CardDef } from '@/engine/types';
import { partnerColorKeyword } from '../_shared/index.js';

export const D02007: CardDef = {
  id: 'D02007',
  no: '0110/D02007',
  kind: 'character',
  names: ['沖田総司'],
  colors: ['緑'],
  level: 5,
  ap: 5000,
  lp: 0,
  traits: ['高校生'],
  keywords: [],
  rarity: 'D',
  imageUrl: '1714013117368858.jpg',
  abilities: [
  partnerColorKeyword({ color: '緑', kw: '突撃', abilityId: 'a1' }),
  ],
  ruleRefs: ['rules/13-keywords.md', 'rules/17-icons.md'],
};
