// cards/ct-d02/D02016 そして人魚はいなくなった (事件) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 01-victory-conditions.md, 06-card-types.md
//
// 能力テキストなしの事件カード。caseTraits は公式データに特徴列が無いため [] (推測補完しない / CLAUDE.md)。

import type { CardDef } from '@/engine/types';

export const D02016: CardDef = {
  id: 'D02016',
  no: '0118/D02016',
  kind: 'case',
  names: ['そして人魚はいなくなった'],
  colors: ['緑'],
  traits: [],
  rarity: 'D',
  imageUrl: '1714013117392321.jpg',
  caseLevel: 7,
  caseTraits: [],
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/06-card-types.md'],
};
