// cards/ct-d09/D09003 上原由衣 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const D09003: CardDef = {
  id: 'D09003',
  no: 'P044/D09003',
  kind: 'partner',
  names: ['上原由衣'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'D',
  imageUrl: '1743742875146763.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
