// cards/ct-d09/D09002 諸伏高明 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const D09002: CardDef = {
  id: 'D09002',
  no: 'P043/D09002',
  kind: 'partner',
  names: ['諸伏高明'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'D',
  imageUrl: '1743742875141973.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
