// cards/ct-d09/D09002 諸伏高明 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const D09002: CardDef = {
  id: 'D09002',
  no: 'P043/D09002',
  kind: 'partner',
  names: ['諸伏高明'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'D',
  imageUrl: '1743742875141973.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
