// cards/ct-d09/D09003 上原由衣 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const D09003: CardDef = {
  id: 'D09003',
  no: 'P044/D09003',
  kind: 'partner',
  names: ['上原由衣'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'D',
  imageUrl: '1743742875146763.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
