// cards/ct-d09/D09001 大和敢助 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const D09001: CardDef = {
  id: 'D09001',
  no: 'P042/D09001',
  kind: 'partner',
  names: ['大和敢助'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'D',
  imageUrl: '1743742875134533.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
