// cards/ct-p03/B03017 東尾マリア (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 15-abilities-effects.md, 17-icons.md, 22-qa-action-contact.md
//
// 公式テキスト(カットイン): 【カットイン】【相手ターン中】（相手のターンのコンタクト中に手札からリムーブすることで発動する）〚特徴［少年探偵団］〛のキャラを1枚まで選び、アクティブにする。

import type { AbilityDef, CardDef } from '@/engine/types';

const a1: AbilityDef = {
  id: 'a1',
  type: 'triggered',
  scope: 'on-hand',
  trigger: { hook: 'effect:declared', optional: true, selfOnly: true }, // 【カットイン】(コンタクト中に手札から使用)
  condition: { kind: 'turn', player: 'opp' }, // 【相手ターン中】
  // [少年探偵団]のキャラを1枚まで選び、アクティブにする (side 既定 either, max:1=0可)
  effect: { kind: 'atom', verb: 'sceneSetState', args: { player: 'self', max: 1, state: 'active', filter: { trait: '少年探偵団' } } },
  description: '【カットイン】【相手ターン中】[少年探偵団]のキャラを1枚までアクティブにする。',
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/15-abilities-effects.md'],
};

export const B03017: CardDef = {
  id: 'B03017',
  no: '0275/B03017',
  kind: 'character',
  names: ['東尾マリア'],
  colors: ['青'],
  level: 3,
  ap: 3000,
  lp: 1,
  traits: [],
  keywords: [],
  rarity: 'C',
  imageUrl: '1729133201226873.jpg',
  abilities: [a1],
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
