// cards/ct-p03/B03034 稲尾一久 (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 17-icons.md
//
// 公式テキスト(カットイン): 【カットイン】AP＋1000、相手の現場にいるコンタクト中のキャラを1枚まで選び、相手のデッキのカードを上から1枚裏向きでセットする。（コンタクト中に手札からリムーブして使う）
//
// ⚠ DEFERRED (BUG-114): 相手デッキ上のカードを裏向きセットする verb が未実装 (engine gap, BUG-114)
//   → カード自体は vanilla キャラとして使用可。カットイン効果のみ未実装 (abilities:[])。

import type { CardDef } from '@/engine/types';

export const B03034: CardDef = {
  id: 'B03034',
  no: '0291/B03034',
  kind: 'character',
  names: ['稲尾一久'],
  colors: ['緑'],
  level: 3,
  ap: 3000,
  lp: 0,
  traits: ['高校生'],
  keywords: [],
  rarity: 'C',
  imageUrl: '1729133249309915.jpg',
  abilities: [], // DEFERRED (BUG-114): カットイン効果は engine 未対応
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
