// cards/ct-p03/B03027P 越水七槻 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03027P: CardDef = {
  id: 'B03027P',
  no: 'P022/B03027P',
  kind: 'partner',
  names: ['越水七槻'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1729133201302124.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
