// cards/ct-p03/B03065 ジョディ・スターリング (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03065: CardDef = {
  id: 'B03065',
  no: 'P025/B03065',
  kind: 'partner',
  names: ['ジョディ・スターリング'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1729133406818436.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
