// cards/ct-p03/B03045 茂木遥史 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03045: CardDef = {
  id: 'B03045',
  no: 'P024/B03045',
  kind: 'partner',
  names: ['茂木遥史'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1729133385743897.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
