// cards/ct-p03/B03083 諸伏景光 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03083: CardDef = {
  id: 'B03083',
  no: 'P026/B03083',
  kind: 'partner',
  names: ['諸伏景光'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1729133424928590.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
