// cards/ct-p03/B03039 長島茂雄 (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 17-icons.md
//
// 公式テキスト(カットイン): 【カットイン】AP＋1000、相手の現場にいるキャラに裏向きでセットされているカードを1枚選び、リムーブしてもよい。そうした場合、代わりにAP＋3000（コンタクト中に手札からリムーブして使う）
//
// ⚠ DEFERRED (BUG-114): 裏向きセットカードを個別選択リムーブする verb が未実装 (engine gap, BUG-114)
//   → カード自体は vanilla キャラとして使用可。カットイン効果のみ未実装 (abilities:[])。

import type { CardDef } from '@/engine/types';

export const B03039: CardDef = {
  id: 'B03039',
  no: '0296/B03039',
  kind: 'character',
  names: ['長島茂雄'],
  colors: ['緑'],
  level: 4,
  ap: 4000,
  lp: 0,
  traits: ['高校生'],
  keywords: [],
  rarity: 'C',
  imageUrl: '1729133249341593.jpg',
  abilities: [], // DEFERRED (BUG-114): カットイン効果は engine 未対応
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
