// cards/ct-p03/B03045 茂木遥史 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B03045: CardDef = {
  id: 'B03045',
  no: 'P024/B03045',
  kind: 'partner',
  names: ['茂木遥史'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1729133385743897.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
