// cards/ct-p03/B03044 槍田郁美 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03044: CardDef = {
  id: 'B03044',
  no: 'P023/B03044',
  kind: 'partner',
  names: ['槍田郁美'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1729133385737525.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
