// cards/ct-p03/B03027 越水七槻 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03027: CardDef = {
  id: 'B03027',
  no: 'P022/B03027',
  kind: 'partner',
  names: ['越水七槻'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1729133201296686.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
