// cards/ct-p03/B03044 槍田郁美 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B03044: CardDef = {
  id: 'B03044',
  no: 'P023/B03044',
  kind: 'partner',
  names: ['槍田郁美'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1729133385737525.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
