// cards/ct-p03/B03065P ジョディ・スターリング (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03065P: CardDef = {
  id: 'B03065P',
  no: 'P025/B03065P',
  kind: 'partner',
  names: ['ジョディ・スターリング'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1729133406825231.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
