// cards/ct-p03/B03106 シェリー (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03106: CardDef = {
  id: 'B03106',
  no: 'P027/B03106',
  kind: 'partner',
  names: ['シェリー'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1729133463347392.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
