// cards/ct-p03/B03139Sec2 赤井秀一 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03139Sec2: CardDef = {
  id: 'B03139Sec2',
  no: 'P005/B03139Sec2',
  kind: 'partner',
  names: ['赤井秀一'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '19444aba57f284.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
