// cards/ct-p03/B03107 ジン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03107: CardDef = {
  id: 'B03107',
  no: 'P028/B03107',
  kind: 'partner',
  names: ['ジン'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1729133463358520.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
