// cards/ct-p03/B03106P シェリー (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03106P: CardDef = {
  id: 'B03106P',
  no: 'P027/B03106P',
  kind: 'partner',
  names: ['シェリー'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1729133463352991.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
