// cards/ct-p03/B03108 ベルモット (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03108: CardDef = {
  id: 'B03108',
  no: 'P029/B03108',
  kind: 'partner',
  names: ['ベルモット'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1729133463368378.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
