// cards/ct-p03/B03109 ラム (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03109: CardDef = {
  id: 'B03109',
  no: 'P030/B03109',
  kind: 'partner',
  names: ['ラム'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1729133482935161.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
