// cards/ct-p03/B03107P ジン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B03107P: CardDef = {
  id: 'B03107P',
  no: 'P028/B03107P',
  kind: 'partner',
  names: ['ジン'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1729133463363763.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
