import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { ALL_CARDS } from '../src/cards/index';
import type { CardDef as EngineCardDef } from '../src/engine/types';
import { CASE_DIFFICULTIES_BY_NUM } from '../meta-app/src/data/caseDifficulties.generated';
import type { CardColor, CardDef } from '../meta-app/src/data/types';

const outputPath = resolve(import.meta.dirname, '../meta-app/src/data/cardCatalog.generated.ts');

const COLOR_MAP: Record<string, CardColor> = {
  '青': 'blue', '黄': 'yellow', '赤': 'red', '緑': 'green', '紫': 'purple', '黒': 'black', '白': 'white',
  blue: 'blue', yellow: 'yellow', red: 'red', green: 'green', purple: 'purple', black: 'black', white: 'white',
};

function officialCardId(no: string): string {
  const slash = no.indexOf('/');
  return slash > 0 ? no.slice(0, slash) : no;
}

function cardSetCode(num: string): string {
  const booster = /^B(\d{2})/i.exec(num);
  if (booster) return `CT-P${booster[1]}`;
  const deck = /^D(\d{2})/i.exec(num);
  if (deck) return `CT-D${deck[1]}`;
  if (/^PR/i.test(num)) return 'PR';
  return 'その他';
}

function deriveKeywords(card: EngineCardDef): string[] {
  const keywords = new Set<string>(card.keywords ?? []);
  if (card.kind === 'partner') keywords.add('アシスト');
  const text = (card.abilities ?? []).map((ability) => ability.description ?? '').join(' ');
  if (text.includes('カットイン')) keywords.add('カットイン');
  if (text.includes('ヒラメキ')) keywords.add('ヒラメキ');
  if (text.includes('変装')) keywords.add('変装');
  if (text.includes('突撃')) keywords.add('突撃');
  if (text.includes('迅速')) keywords.add('迅速');
  if (text.includes('【宣言】') || (card.abilities ?? []).some((ability) => ability.type === 'declared')) keywords.add('宣言');
  if (text.includes('疾風')) keywords.add('疾風');
  if (text.includes('ミスリード')) keywords.add('ミスリード');
  if (text.includes('ブレット')) keywords.add('ブレット');
  if (text.includes('捜査')) keywords.add('捜査');
  if (text.includes('痕跡')) keywords.add('痕跡');
  return [...keywords];
}

export function metaCardFromEngine(card: EngineCardDef): CardDef {
  const playLevel = card.kind === 'character' || card.kind === 'event' ? card.level : undefined;
  const colors = [...new Set((card.colors ?? []).map((color) => COLOR_MAP[color] ?? 'blue'))];
  const color: CardColor = colors[0] ?? 'blue';
  const caseDifficulty = card.kind === 'case' ? CASE_DIFFICULTIES_BY_NUM[card.id] : undefined;
  if (card.kind === 'case' && !caseDifficulty) {
    throw new Error(`official case difficulty is missing for ${card.id}`);
  }

  return {
    num: card.id,
    id: officialCardId(card.no),
    setCode: cardSetCode(card.id),
    name: card.names[0] ?? card.id,
    type: card.kind,
    color,
    colors: colors.length ? colors : [color],
    cost: playLevel,
    ap: card.ap,
    lp: card.lp,
    level: card.kind === 'case' ? (card.caseLevel ?? card.level) : playLevel,
    difficultyFirst: caseDifficulty?.first,
    difficultySecond: caseDifficulty?.second,
    rarity: card.rarity,
    features: card.kind === 'case' ? (card.caseTraits ?? card.traits) : card.traits,
    keywords: deriveKeywords(card),
    effectShort: (card.abilities ?? []).map((ability) => ability.description).filter(Boolean).join('\n'),
    imagePath: card.imageUrl ?? null,
    deckLimit: card.deckLimit,
  };
}

export function renderMetaCardCatalog(cards: readonly EngineCardDef[]): string {
  const catalog = cards.map(metaCardFromEngine);
  return `// Generated by scripts/gen-meta-card-catalog.ts. Do not edit.\n\nimport type { CardDef } from './types';\n\nexport const CARD_CATALOG: readonly CardDef[] = ${JSON.stringify(catalog, null, 2)};\n`;
}

async function main() {
  await writeFile(outputPath, renderMetaCardCatalog(ALL_CARDS), 'utf8');
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(import.meta.filename)) {
  await main();
}
