import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { ALL_CARDS } from "../src/cards/index";
import {
  BUG_274_PARTNER_CARD,
  BUG_274_PARTNER_ID,
} from "../meta-app/src/data/bug274ValidationDeck";

type IdentitySource = {
  id: string;
  kind: string;
  names: readonly string[];
  colors?: readonly string[];
  imageUrl?: string;
};

const outputPath = resolve(
  import.meta.dirname,
  "../meta-app/src/data/cardIdentities.generated.ts",
);

function defaultCaseFor(colors: readonly string[] | undefined): string {
  return colors?.includes("黄") || colors?.includes("yellow")
    ? "D11021"
    : "D08026";
}

export function renderMetaCardIdentities(
  cards: readonly IdentitySource[],
): string {
  const identities = Object.fromEntries(
    cards
      .filter((card) => card.kind === "partner" || card.kind === "case")
      .sort((left, right) => left.id.localeCompare(right.id))
      .map((card) => [
        card.id,
        {
          num: card.id,
          name: card.names[0] ?? card.id,
          kind: card.kind,
          imagePath: card.imageUrl ?? null,
          ...(card.kind === "partner"
            ? { defaultCase: defaultCaseFor(card.colors) }
            : {}),
        },
      ]),
  );

  return `// Generated by scripts/gen-meta-card-identities.ts. Do not edit.\n\nexport type CardIdentityKind = "partner" | "case";\n\nexport interface CardIdentity {\n  num: string;\n  name: string;\n  kind: CardIdentityKind;\n  imagePath: string | null;\n  defaultCase?: string;\n}\n\nexport const CARD_IDENTITIES = ${JSON.stringify(identities, null, 2)} as const satisfies Readonly<Record<string, CardIdentity>>;\n\nexport function cardIdentityFor(num: string): CardIdentity | undefined {\n  return (CARD_IDENTITIES as Readonly<Record<string, CardIdentity>>)[num];\n}\n\nexport function isDeckIdentityCard(num: string): boolean {\n  return cardIdentityFor(num) !== undefined;\n}\n\nexport function defaultCaseForPartner(partnerNum: string): string {\n  const identity = cardIdentityFor(partnerNum);\n  return identity?.kind === "partner" ? (identity.defaultCase ?? "D08026") : "D08026";\n}\n`;
}

export async function writeMetaCardIdentitiesIfChanged(
  targetPath: string,
  rendered: string,
): Promise<boolean> {
  try {
    const current = await readFile(targetPath, "utf8");
    if (current.replace(/\r\n?/g, "\n") === rendered.replace(/\r\n?/g, "\n")) {
      return false;
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }

  await writeFile(targetPath, rendered, "utf8");
  return true;
}

async function main() {
  const publicRegressionIdentities: IdentitySource[] = [{
    id: BUG_274_PARTNER_ID,
    kind: BUG_274_PARTNER_CARD.type,
    names: [BUG_274_PARTNER_CARD.name],
    colors: BUG_274_PARTNER_CARD.colors,
  }];
  await writeMetaCardIdentitiesIfChanged(
    outputPath,
    renderMetaCardIdentities([...ALL_CARDS, ...publicRegressionIdentities]),
  );
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(import.meta.filename)) {
  await main();
}
