import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { ALL_CARDS } from "../src/cards/index";

type DeckLegalitySource = {
  id: string;
  no: string;
  kind: "character" | "event" | "partner" | "case";
  deckLimit?: number | "unlimited";
};

const outputPath = resolve(import.meta.dirname, "../src/shared/deck-legality-catalog.generated.ts");

function officialId(card: DeckLegalitySource): string {
  const slash = card.no.indexOf("/");
  return slash === -1 ? card.no : card.no.slice(0, slash);
}

export function renderDeckLegalityCatalog(cards: readonly DeckLegalitySource[]): string {
  const seen = new Set<string>();
  const officialMetadata = new Map<string, { kind: DeckLegalitySource["kind"]; deckLimit: number | "unlimited" }>();
  const entries = cards.map((card) => {
    if (seen.has(card.id)) throw new Error(`duplicate printing ID: ${card.id}`);
    seen.add(card.id);
    const id = officialId(card);
    const metadata = { kind: card.kind, deckLimit: card.deckLimit ?? 3 } as const;
    const prior = officialMetadata.get(id);
    if (prior && (prior.kind !== metadata.kind || prior.deckLimit !== metadata.deckLimit)) {
      throw new Error(`conflicting metadata for official ID ${id}`);
    }
    officialMetadata.set(id, metadata);
    return [card.id, [id, metadata.kind, metadata.deckLimit]] as const;
  }).sort(([left], [right]) => left.localeCompare(right));

  return `// Generated by scripts/gen-deck-legality-catalog.ts. Do not edit.\n\nimport type { DeckCardResolver, ResolvedDeckCard } from "./deck-legality";\n\ntype DeckLegalityCatalogEntry = readonly [officialId: string, kind: ResolvedDeckCard["kind"], deckLimit: ResolvedDeckCard["deckLimit"]];\n\nexport const DECK_LEGALITY_CATALOG = ${JSON.stringify(Object.fromEntries(entries), null, 2)} as const satisfies Readonly<Record<string, DeckLegalityCatalogEntry>>;\n\nexport function deckLegalityCardFor(printingId: string): ResolvedDeckCard | undefined {\n  const entry = DECK_LEGALITY_CATALOG[printingId as keyof typeof DECK_LEGALITY_CATALOG];\n  return entry ? { printingId, officialId: entry[0], kind: entry[1], deckLimit: entry[2] } : undefined;\n}\n\nexport const deckLegalityCatalogResolver: DeckCardResolver = deckLegalityCardFor;\n`;
}

function normalizeLineEndings(value: string): string {
  return value.replace(/\r\n?/g, "\n");
}

export function deckLegalityCatalogIsCurrent(current: string, rendered: string): boolean {
  return normalizeLineEndings(current) === normalizeLineEndings(rendered);
}

export async function writeDeckLegalityCatalogIfChanged(targetPath: string, rendered: string): Promise<boolean> {
  try {
    const current = await readFile(targetPath, "utf8");
    if (deckLegalityCatalogIsCurrent(current, rendered)) return false;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  await writeFile(targetPath, rendered, "utf8");
  return true;
}

export async function assertDeckLegalityCatalogCurrent(
  targetPath: string,
  rendered: string,
): Promise<void> {
  let current: string;
  try {
    current = await readFile(targetPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    throw new Error(
      "deck-legality catalog is missing; run npm run gen:deck-legality-catalog",
      { cause: error },
    );
  }
  if (!deckLegalityCatalogIsCurrent(current, rendered)) {
    throw new Error("deck-legality catalog is stale; run npm run gen:deck-legality-catalog");
  }
}

async function main() {
  const rendered = renderDeckLegalityCatalog(ALL_CARDS);
  if (process.argv.includes("--check")) {
    await assertDeckLegalityCatalogCurrent(outputPath, rendered);
    return;
  }
  await writeDeckLegalityCatalogIfChanged(outputPath, rendered);
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(import.meta.filename)) await main();
