// cards/ct-d07/D07012 ウォッカ (キャラ) — auto-generated by scripts/gen-cards/gen-simple-cards.cjs
// rules: 13-keywords.md, 17-icons.md, 24-qa-naming-stun.md
//
// 公式テキスト: 【パートナー黒】〚突撃〛（登場したターンからすぐにアクションできる）

import type { CardDef } from '@/engine/types';
import { partnerColorKeyword } from '../_shared/index.js';

export const D07012: CardDef = {
  id: 'D07012',
  no: '0393/D07012',
  kind: 'character',
  names: ['ウォッカ'],
  colors: ['黒'],
  level: 5,
  ap: 5000,
  lp: 0,
  traits: ['黒ずくめの組織'],
  keywords: [],
  rarity: 'D',
  imageUrl: '1729865282035249.jpg',
  abilities: [
  partnerColorKeyword({ color: '黒', kw: '突撃', abilityId: 'a1' }),
  ],
  ruleRefs: ['rules/13-keywords.md', 'rules/17-icons.md'],
};
