// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B04038  |  scenarios: 1  |  fixtures: 0

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B04038 } from '@/cards/ct-p04/B04038';

const FIXTURES: CardDef[] = [];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B04038 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B04038",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [],
      "remove": [],
      "partnerAreaCards": [],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "enter",
      "cardId": "B04038",
      "uid": "__CARRIER__",
      "side": "self"
    },
    "script": [],
    "expect": []
  }
];

describe('B04038 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B04038, FIXTURES, sc);
    });
  }
});
