// AUTO-GENERATED by scripts/gen-card-probes.cjs — do not hand-edit; regenerate instead.
// card: B07039  |  scenarios: 2  |  fixtures: 2

import { describe, it } from 'vitest';
import { runCardScenario } from '../../helpers/card-probe-harness';
import type { ProbeScenario } from '../../helpers/card-probe-harness';
import type { CardDef } from '@/engine/types';
import { B07039 } from '@/cards/ct-p07/B07039';

const FIXTURES: CardDef[] = [
  {
    "id": "__HAND_FODDER__",
    "no": "__HAND_FODDER__",
    "kind": "character",
    "names": [
      "__HAND_FODDER__"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  },
  {
    "id": "__COST_PA_0_0",
    "no": "__COST_PA_0_0",
    "kind": "character",
    "names": [
      "__COST_PA_0_0"
    ],
    "colors": [
      "赤"
    ],
    "level": 3,
    "ap": 5000,
    "lp": 1,
    "traits": [
      "ビッグジュエル"
    ],
    "keywords": [],
    "rarity": "C",
    "imageUrl": "",
    "abilities": [],
    "ruleRefs": []
  }
];

const SCENARIOS: ProbeScenario[] = [
  {
    "name": "B07039 happy-path (all picks -> in-filter; decoys excluded)",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07039",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [
        "__COST_PA_0_0"
      ],
      "deckSize": 6,
      "caseStatus": "解決編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [],
    "expect": [
      {
        "kind": "deckDelta",
        "side": "self",
        "n": -1
      },
      {
        "kind": "zone",
        "cardId": "__COST_PA_0_0",
        "zone": "partner-area",
        "side": "self",
        "present": false
      },
      {
        "kind": "zone",
        "cardId": "__COST_PA_0_0",
        "zone": "remove",
        "side": "self",
        "present": true
      }
    ]
  },
  {
    "name": "B07039 condition-off (caseStatus!=解決編) -> no prompt",
    "setup": {
      "selfScene": [
        {
          "cardId": "B07039",
          "uid": "__CARRIER__",
          "state": "active"
        }
      ],
      "oppScene": [],
      "hand": [
        "__HAND_FODDER__"
      ],
      "remove": [],
      "partnerAreaCards": [
        "__COST_PA_0_0"
      ],
      "deckSize": 6,
      "caseStatus": "事件編"
    },
    "drive": {
      "kind": "declared",
      "uid": "__CARRIER__",
      "abilityId": "a1"
    },
    "script": [],
    "expect": [
      {
        "kind": "noPromptSurfaced"
      }
    ]
  }
];

describe('B07039 — auto-probe (generated)', () => {
  for (const sc of SCENARIOS) {
    it(sc.name, () => {
      runCardScenario(B07039, FIXTURES, sc);
    });
  }
});
