// cards/ct-p08/B08045 宮野厚司 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B08045: CardDef = {
  id: 'B08045',
  no: 'P074/B08045',
  kind: 'partner',
  names: ['宮野厚司'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1770731222627045.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
