// cards/ct-p08/B08018 服部静華 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B08018: CardDef = {
  id: 'B08018',
  no: 'P072/B08018',
  kind: 'partner',
  names: ['服部静華'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1770731204416808.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
