// cards/ct-p08/B08001Sec1 灰原哀 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B08001Sec1: CardDef = {
  id: 'B08001Sec1',
  no: 'P008/B08001Sec1',
  kind: 'partner',
  names: ['灰原哀'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1766493008936850.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
