// cards/ct-p08/B08031 工藤有希子 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B08031: CardDef = {
  id: 'B08031',
  no: 'P073/B08031',
  kind: 'partner',
  names: ['工藤有希子'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1770731222538778.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
