// cards/ct-p08/B08061P 黒田兵衛 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B08061P: CardDef = {
  id: 'B08061P',
  no: 'P075/B08061P',
  kind: 'partner',
  names: ['黒田兵衛'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1770878984765580.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
