// cards/ct-p08/B08031 工藤有希子 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B08031: CardDef = {
  id: 'B08031',
  no: 'P073/B08031',
  kind: 'partner',
  names: ['工藤有希子'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1770731222538778.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
