// cards/ct-p08/B08018P 服部静華 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B08018P: CardDef = {
  id: 'B08018P',
  no: 'P072/B08018P',
  kind: 'partner',
  names: ['服部静華'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1770878966401101.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
