// cards/ct-p08/B08077Sec1 ジン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B08077Sec1: CardDef = {
  id: 'B08077Sec1',
  no: 'P028/B08077Sec1',
  kind: 'partner',
  names: ['ジン'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1766493008991780.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
