// cards/ct-p08/B08055 本堂瑛海 (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 17-icons.md
//
// 公式テキスト(カットイン): 【カットイン】【自分ターン中】手札からキャラを1枚リムーブしてもよい。そうした場合、リムーブしたキャラのAP1000につき、AP＋1000（自分のターンのコンタクト中に手札からリムーブして使う）
//
// ⚠ DEFERRED (BUG-114): リムーブした手札キャラの AP で AP スケールする dyn root が未実装 (BUG-114)
//   → カード自体は vanilla キャラとして使用可。カットイン効果のみ未実装 (abilities:[])。

import type { CardDef } from '@/engine/types';

export const B08055: CardDef = {
  id: 'B08055',
  no: '0893/B08055',
  kind: 'character',
  names: ['本堂瑛海'],
  colors: ['赤'],
  level: 3,
  ap: 3000,
  lp: 1,
  traits: ['CIA'],
  keywords: [],
  rarity: 'C',
  imageUrl: '1770731238650353.jpg',
  abilities: [], // DEFERRED (BUG-114): カットイン効果は engine 未対応
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
