// cards/ct-p05/B05043 黒羽快斗 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05043: CardDef = {
  id: 'B05043',
  no: 'P053/B05043',
  kind: 'partner',
  names: ['黒羽快斗'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1745322178485108.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
