// cards/ct-p05/B05003P 円谷光彦 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B05003P: CardDef = {
  id: 'B05003P',
  no: 'P049/B05003P',
  kind: 'partner',
  names: ['円谷光彦'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1747231489384610.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
