// cards/ct-p05/B05004 吉田歩美 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05004: CardDef = {
  id: 'B05004',
  no: 'P050/B05004',
  kind: 'partner',
  names: ['吉田歩美'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1743742488521898.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
