// cards/ct-p05/B05084Sec2 大和敢助 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05084Sec2: CardDef = {
  id: 'B05084Sec2',
  no: 'P042/B05084Sec2',
  kind: 'partner',
  names: ['大和敢助'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1747231543238303.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
