// cards/ct-p05/B05085 諸伏高明 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05085: CardDef = {
  id: 'B05085',
  no: 'P043/B05085',
  kind: 'partner',
  names: ['諸伏高明'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1742972384134767.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
