// cards/ct-p05/B05002P 小嶋元太 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05002P: CardDef = {
  id: 'B05002P',
  no: 'P048/B05002P',
  kind: 'partner',
  names: ['小嶋元太'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1747231489379079.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
