// cards/ct-p05/B05004P 吉田歩美 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B05004P: CardDef = {
  id: 'B05004P',
  no: 'P050/B05004P',
  kind: 'partner',
  names: ['吉田歩美'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1747231489390480.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
