// cards/ct-p05/B05064 ジェイムズ・ブラック (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05064: CardDef = {
  id: 'B05064',
  no: 'P055/B05064',
  kind: 'partner',
  names: ['ジェイムズ・ブラック'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1745322205563894.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
