// cards/ct-p05/B05010 江戸川コナン (キャラ) — auto-generated by scripts/gen-cards/gen-complex-cutins.cjs
// rules: 09-cutin-disguise.md, 15-abilities-effects.md, 17-icons.md, 22-qa-action-contact.md
//
// 公式テキスト(カットイン): 【カットイン】【パートナー青】AP＋1000、自分の事件が【青】以外の色を持たない場合、カードを1枚引く。（コンタクト中に手札からリムーブして使う）

import type { AbilityDef, CardDef } from '@/engine/types';
import { caseMonoColor } from '../_shared/index.js';

const a1: AbilityDef = {
  id: 'a1',
  type: 'triggered',
  scope: 'on-hand',
  trigger: { hook: 'effect:declared', optional: true, selfOnly: true }, // 【カットイン】(コンタクト中に手札から使用)
  condition: { kind: 'partnerColor', color: '青' }, // 【パートナー青】
  effect: {
    kind: 'sequence',
    steps: [
      // AP＋1000
      { kind: 'atom', verb: 'charModifyAP', args: { uid: '$contact.byUid', delta: 1000, scope: 'contact' } },
      // 自分の事件が【青】以外の色を持たない場合、カードを1枚引く
      { kind: 'conditional', if: caseMonoColor('青'), then: { kind: 'atom', verb: 'draw', args: { player: 'self', n: 1 } } },
    ],
  },
  description: '【カットイン】【パートナー青】AP＋1000、事件が青単色ならカードを1枚引く。',
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};

export const B05010: CardDef = {
  id: 'B05010',
  no: '0516/B05010',
  kind: 'character',
  names: ['江戸川コナン'],
  colors: ['青'],
  level: 2,
  ap: 1000,
  lp: 1,
  traits: ['探偵', '毛利探偵事務所', '少年探偵団'],
  keywords: [],
  rarity: 'C',
  imageUrl: '1746628061710084.jpg',
  abilities: [a1],
  ruleRefs: ['rules/09-cutin-disguise.md', 'rules/17-icons.md'],
};
