// cards/ct-p05/B05001P 妃英理 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05001P: CardDef = {
  id: 'B05001P',
  no: 'P047/B05001P',
  kind: 'partner',
  names: ['妃英理'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1747231489364878.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
