// cards/ct-p05/B05002 小嶋元太 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B05002: CardDef = {
  id: 'B05002',
  no: 'P048/B05002',
  kind: 'partner',
  names: ['小嶋元太'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1743742488507652.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
