// cards/ct-p05/B05003 円谷光彦 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05003: CardDef = {
  id: 'B05003',
  no: 'P049/B05003',
  kind: 'partner',
  names: ['円谷光彦'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1743742488516856.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
