// cards/ct-p05/B05025 大岡紅葉 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B05025: CardDef = {
  id: 'B05025',
  no: 'P051/B05025',
  kind: 'partner',
  names: ['大岡紅葉'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1745322178425569.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
