// cards/ct-p05/B05085Sec2 諸伏高明 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05085Sec2: CardDef = {
  id: 'B05085Sec2',
  no: 'P043/B05085Sec2',
  kind: 'partner',
  names: ['諸伏高明'],
  colors: ['黄'],
  lp: 1,
  traits: [],
  rarity: 'SEC',
  imageUrl: '1747231543813016.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
