// cards/ct-p05/B05002 小嶋元太 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05002: CardDef = {
  id: 'B05002',
  no: 'P048/B05002',
  kind: 'partner',
  names: ['小嶋元太'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1743742488507652.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
