// cards/ct-p05/B05064P ジェイムズ・ブラック (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05064P: CardDef = {
  id: 'B05064P',
  no: 'P055/B05064P',
  kind: 'partner',
  names: ['ジェイムズ・ブラック'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1747231524171569.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
