// cards/ct-p05/B05044P 中森青子 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05044P: CardDef = {
  id: 'B05044P',
  no: 'P054/B05044P',
  kind: 'partner',
  names: ['中森青子'],
  colors: ['白'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1747231524127234.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
