// cards/ct-p05/B05026 綾小路文麿 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05026: CardDef = {
  id: 'B05026',
  no: 'P052/B05026',
  kind: 'partner',
  names: ['綾小路文麿'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1745322178430018.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
