// cards/ct-p05/B05065P 宮野明美 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05065P: CardDef = {
  id: 'B05065P',
  no: 'P056/B05065P',
  kind: 'partner',
  names: ['宮野明美'],
  colors: ['赤'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1747231524177928.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
