// cards/ct-p05/B05026P 綾小路文麿 (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const B05026P: CardDef = {
  id: 'B05026P',
  no: 'P052/B05026P',
  kind: 'partner',
  names: ['綾小路文麿'],
  colors: ['緑'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1747231489464726.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
