// cards/ct-p05/B05104P スコッチ (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05104P: CardDef = {
  id: 'B05104P',
  no: 'P057/B05104P',
  kind: 'partner',
  names: ['スコッチ'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1747231546566098.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
