// cards/ct-p05/B05104 スコッチ (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05104: CardDef = {
  id: 'B05104',
  no: 'P057/B05104',
  kind: 'partner',
  names: ['スコッチ'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1745322226231045.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
