// cards/ct-p05/B05105 バーボン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05105: CardDef = {
  id: 'B05105',
  no: 'P058/B05105',
  kind: 'partner',
  names: ['バーボン'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'C',
  imageUrl: '1745322226236026.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
