// cards/ct-p05/B05105P バーボン (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const B05105P: CardDef = {
  id: 'B05105P',
  no: 'P058/B05105P',
  kind: 'partner',
  names: ['バーボン'],
  colors: ['黒'],
  lp: 1,
  traits: [],
  rarity: 'CP',
  imageUrl: '1747231561645158.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
