// cards/ct-d10/D10002 ハート姫（毛利蘭） (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const D10002: CardDef = {
  id: 'D10002',
  no: 'P071/D10002',
  kind: 'partner',
  names: ['ハート姫（毛利蘭）'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'D',
  imageUrl: '1761913165169499.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
