// cards/ct-d10/D10001 黒衣の騎士・スペイド（工藤新一） (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
// 全パートナー共通能力 (アシスト / 事件解決) は engine 内蔵。個別能力は未実装 (TODO)。
import type { CardDef } from '@/engine/types';

export const D10001: CardDef = {
  id: 'D10001',
  no: 'P070/D10001',
  kind: 'partner',
  names: ['黒衣の騎士・スペイド（工藤新一）'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'D',
  imageUrl: '1761913165158661.jpg',
  abilities: [], // TODO: 個別能力 (ct-p05 / pr-01 の一部) は後日実装
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
