// cards/ct-d10/D10002 ハート姫（毛利蘭） (パートナー) — auto-generated by scripts/gen-cards/gen-partners.cjs
import type { CardDef } from '@/engine/types';

export const D10002: CardDef = {
  id: 'D10002',
  no: 'P071/D10002',
  kind: 'partner',
  names: ['ハート姫（毛利蘭）'],
  colors: ['青'],
  lp: 1,
  traits: [],
  rarity: 'D',
  imageUrl: '1761913165169499.jpg',
  abilities: [],
  ruleRefs: ['rules/01-victory-conditions.md', 'rules/13-keywords.md'],
};
