import { execFileSync, spawnSync } from 'node:child_process';
import { cpSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import {
  ALL_CARDS,
  GENERATED_COMPLEX_CUTINS,
  GENERATED_PARTNERS,
  GENERATED_SIMPLE_CARDS,
  REUSE_CARDS,
} from '../../src/cards';

const ROOT = resolve(import.meta.dirname, '../..');
const SCRIPT = join(ROOT, 'scripts/gen-cards/gen-partners.cjs');
const temps: string[] = [];

function tempRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'conan-gen-partners-'));
  temps.push(root);
  return root;
}

function runGenerator(cardsData: string, projectRoot: string): string {
  return execFileSync(process.execPath, [join(projectRoot, 'scripts/gen-cards/gen-partners.cjs')], {
    cwd: projectRoot,
    env: { ...process.env, CONAN_CARDS_DATA_DIR: cardsData },
    encoding: 'utf8',
  });
}

afterEach(() => {
  for (const root of temps.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe('partner generator ownership and thresholds', () => {
  it('keeps official printing ownership unique and marks every partner at runtime', () => {
    const ids = ALL_CARDS.map(({ id }) => id);
    expect(ids).toHaveLength(2256);
    expect(new Set(ids).size).toBe(ids.length);

    const generatedIds = new Set([
      ...GENERATED_PARTNERS,
      ...GENERATED_SIMPLE_CARDS,
      ...GENERATED_COMPLEX_CUTINS,
    ].map(({ id }) => id));
    expect(REUSE_CARDS.filter(({ id }) => generatedIds.has(id))).toEqual([]);

    const partners = ALL_CARDS.filter(({ kind }) => kind === 'partner');
    expect(partners).toHaveLength(300);
    expect(partners.every(({ standardPartnerActions }) => standardPartnerActions === true)).toBe(true);
    expect(partners.filter(({ partnerAssistFileThreshold }) => partnerAssistFileThreshold !== undefined)
      .map(({ id, partnerAssistFileThreshold }) => [id, partnerAssistFileThreshold])).toEqual([['PR022', 8]]);
  });

  it('keeps non-MVP assist metadata owned by the generated barrel', () => {
    const rawPr022 = readFileSync(resolve(ROOT, 'src/cards/pr-01/PR022.ts'), 'utf8');
    expect(rawPr022).not.toContain('standardPartnerActions:');
    expect(rawPr022).not.toContain('partnerAssistFileThreshold:');

    const productionPr022 = GENERATED_PARTNERS.find(({ id }) => id === 'PR022');
    expect(productionPr022?.standardPartnerActions).toBe(true);
    expect(productionPr022?.partnerAssistFileThreshold).toBe(8);
  });

  it('classifies exact FILE text, skips CT-P10, preserves sources, and is idempotent', () => {
    const project = tempRoot();
    mkdirSync(join(project, 'scripts/gen-cards'), { recursive: true });
    mkdirSync(join(project, 'scripts/cards'), { recursive: true });
    mkdirSync(join(project, 'src/cards/_generated'), { recursive: true });
    mkdirSync(join(project, 'src/cards/_reuse'), { recursive: true });
    cpSync(SCRIPT, join(project, 'scripts/gen-cards/gen-partners.cjs'));
    cpSync(join(ROOT, 'scripts/cards/official-api.cjs'), join(project, 'scripts/cards/official-api.cjs'));
    writeFileSync(join(project, 'src/cards/_reuse/index.ts'), '', 'utf8');

    const data = join(project, 'cards-data');
    const rows = [
      ['ct-p01', 'B01001', '7'],
      ['pr-01', 'PR022', '8'],
      ['ct-d07', 'D07001', '7'],
      ['ct-d01', 'D01001', ''],
      ['ct-p10', 'B10001', '7'],
    ] as const;
    const printed = (n: string, separator = '\\n') => n
      ? `【解決編】【事件解決】【スリープ】：自分の証拠が事件レベルの数以上ある場合、ゲームに勝利する。${separator}【アシスト】【スリープ】：FILEエリアに移動する。自分のFILEエリアにカードが${n}枚以上ある場合、事件を解決編にする。`
      : '';
    for (const [pkg, id, threshold] of rows) {
      mkdirSync(join(data, pkg), { recursive: true });
      mkdirSync(join(project, 'src/cards', pkg), { recursive: true });
      const effect = id === 'D07001' ? printed(threshold, '<br>') : printed(threshold);
      writeFileSync(join(data, pkg, 'partner.tsv'), `cardNum\teffect\n${id}\t${effect}\n`, 'utf8');
      writeFileSync(join(project, 'src/cards', pkg, `${id}.ts`), `// auto-generated by scripts/gen-cards/gen-partners.cjs\nexport const ${id} = { id: '${id}' };\n`, 'utf8');
    }

    const before = rows.map(([pkg, id]) => readFileSync(join(project, 'src/cards', pkg, `${id}.ts`), 'utf8'));
    runGenerator(data, project);
    const barrel = readFileSync(join(project, 'src/cards/_generated/partners.ts'), 'utf8');
    expect(barrel).toContain('{ ...B01001, standardPartnerActions: true }');
    expect(barrel).toContain('{ ...PR022, standardPartnerActions: true, partnerAssistFileThreshold: 8 }');
    expect(barrel).toContain('{ ...D07001, standardPartnerActions: true }');
    expect(barrel).toContain('{ ...D01001, standardPartnerActions: true }');
    expect(barrel).not.toContain('B10001');
    expect(rows.map(([pkg, id]) => readFileSync(join(project, 'src/cards', pkg, `${id}.ts`), 'utf8'))).toEqual(before);

    runGenerator(data, project);
    expect(readFileSync(join(project, 'src/cards/_generated/partners.ts'), 'utf8')).toBe(barrel);
  });

  it('fails closed for unknown non-empty partner text', () => {
    const project = tempRoot();
    mkdirSync(join(project, 'scripts/gen-cards'), { recursive: true });
    mkdirSync(join(project, 'scripts/cards'), { recursive: true });
    mkdirSync(join(project, 'src/cards/_generated'), { recursive: true });
    mkdirSync(join(project, 'src/cards/_reuse'), { recursive: true });
    cpSync(SCRIPT, join(project, 'scripts/gen-cards/gen-partners.cjs'));
    cpSync(join(ROOT, 'scripts/cards/official-api.cjs'), join(project, 'scripts/cards/official-api.cjs'));
    writeFileSync(join(project, 'src/cards/_reuse/index.ts'), '', 'utf8');
    const data = join(project, 'cards-data/ct-p01');
    mkdirSync(data, { recursive: true });
    mkdirSync(join(project, 'src/cards/ct-p01'), { recursive: true });
    writeFileSync(join(data, 'partner.tsv'), 'cardNum\teffect\nBAD001\tunknown official text\n', 'utf8');
    writeFileSync(join(project, 'src/cards/ct-p01/BAD001.ts'), '// auto-generated by scripts/gen-cards/gen-partners.cjs\n', 'utf8');

    const result = spawnSync(process.execPath, [join(project, 'scripts/gen-cards/gen-partners.cjs')], {
      cwd: project,
      env: { ...process.env, CONAN_CARDS_DATA_DIR: join(project, 'cards-data') },
      encoding: 'utf8',
    });
    expect(result.status).not.toBe(0);
    expect(result.stderr).toMatch(/unrecognized partner assist text/u);
  });
});
