import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { describe, expect, it } from 'vitest';
import { GENERATED_PARTNERS } from '../../src/cards';

const ROOT = resolve(import.meta.dirname, '../..');
const DATA_ROOT = join(ROOT, '.claude/specs/cards-data');
const CARDS_ROOT = join(ROOT, 'src/cards');
const require = createRequire(import.meta.url);
const { PARTNER_BOILERPLATE } = require('../../scripts/compiler/productions.cjs') as {
  PARTNER_BOILERPLATE: Set<string>;
};
const { splitLines, lineKey } = require('../../scripts/compiler/norm.cjs') as {
  splitLines: (text: string) => string[];
  lineKey: (text: string) => string;
};
const SKIP_PACKAGES = new Set(['ct-d08', 'ct-d11', 'ct-p10']);
const STALE_TODO = 'TODO: 個別能力';

type PartnerSource = { id: string; sourcePath: string; effect: string };

function generatedPartnerSources(): PartnerSource[] {
  const sources: PartnerSource[] = [];
  for (const pkg of readdirSync(DATA_ROOT).sort()) {
    if (SKIP_PACKAGES.has(pkg)) continue;
    const tsvPath = join(DATA_ROOT, pkg, 'partner.tsv');
    if (!existsSync(tsvPath)) continue;
    const rows = readFileSync(tsvPath, 'utf8').split(/\r?\n/u).filter(Boolean);
    const header = rows[0].split('\t');
    const idColumn = header.indexOf('cardNum');
    const effectColumn = header.indexOf('effect');
    for (const row of rows.slice(1)) {
      const fields = row.split('\t');
      const id = fields[idColumn];
      if (!id) continue;
      const sourcePath = join(CARDS_ROOT, pkg, `${id}.ts`);
      if (existsSync(sourcePath)
        && readFileSync(sourcePath, 'utf8').includes('auto-generated by scripts/gen-cards/gen-partners.cjs')) {
        sources.push({ id, sourcePath, effect: fields[effectColumn] ?? '' });
      }
    }
  }
  return sources;
}

describe('generated standard-partner source cleanup', () => {
  it('keeps every generated source owned at runtime and limited to official standard boilerplate', () => {
    const sources = generatedPartnerSources();
    expect(sources).toHaveLength(276);

    const runtimePartners = new Map(GENERATED_PARTNERS.map((card) => [card.id, card]));
    for (const { id, effect } of sources) {
      const printedLines = splitLines(effect).map(lineKey);
      expect(printedLines.every((line) => PARTNER_BOILERPLATE.has(line))).toBe(true);
      expect(runtimePartners.get(id)?.standardPartnerActions).toBe(true);
    }
  });

  it('contains no stale individual-ability TODO in generated standard partners', () => {
    const stale = generatedPartnerSources()
      .filter(({ sourcePath }) => readFileSync(sourcePath, 'utf8').includes(STALE_TODO))
      .map(({ id }) => id);
    expect(stale).toEqual([]);
  });
});
